{-# OPTIONS --rewriting --local-confluence-check #-}

-- Generated by gen/agdasubst.py --model=vectors.  DO NOT EDIT.
--
-- The multi-sorted, mode-merged σ-calculus with FIRST-CLASS RENAMINGS,
-- installed as a locally confluent Agda REWRITE system.  Maps are
-- inductive VECTORS, so equality of maps is equality of data and the
-- module assumes NOTHING: no function extensionality, no postulates.

module Languages.FsubPatterns where

open import Relation.Binary.PropositionalEquality
  using (_≡_; refl; sym; cong; trans; module ≡-Reasoning)
open ≡-Reasoning
open import Agda.Builtin.Equality.Rewrite
open import Data.List using (List; []; _∷_)
open import Data.Nat using (ℕ; zero; suc)

cong1 : ∀ {A1 A2 : Set} (f : A1 → A2) {a1 a2} →
  a1 ≡ a2 → f a1 ≡ f a2
cong1 f refl = refl

cong2 : ∀ {A1 A2 A3 : Set} (f : A1 → A2 → A3) {a1 a2 a3 a4} →
  a1 ≡ a2 → a3 ≡ a4 → f a1 a3 ≡ f a2 a4
cong2 f refl refl = refl

cong3 : ∀ {A1 A2 A3 A4 : Set} (f : A1 → A2 → A3 → A4) {a1 a2 a3 a4 a5 a6} →
  a1 ≡ a2 → a3 ≡ a4 → a5 ≡ a6 → f a1 a3 a5 ≡ f a2 a4 a6
cong3 f refl refl refl = refl


Label : Set
Label = ℕ

infixr 5 _⇒_
infixl 6 _·_
infixl 6 _•_
infixl 7 _#_

-- ─── syntax ─────────────────────────────────────────────────────────

data Sort : Set where
  expr type rtype rexpr : Sort
  pat : ℕ → ℕ → Sort
  rpat : ℕ → ℕ → Sort
Scope = List Sort

variable
  s s₁ s₂ s′ : Sort
  S S₁ S₂ S₃ : Scope
  n n₁ n₂ n₃ : ℕ


-- ─── iterated lifting: a binder of VARIABLE ARITY ───────────────────
--
-- `ext* b n S` extends a scope by n copies of ONE sort.  DERIVED and
-- TRANSPARENT: it computes on n, so the rewrite system needs rules only
-- for the case where n is abstract.
--
-- Generalized from gen/Reference/FsubPatterns.agda, which fixes b := expr.

ext* : Sort → ℕ → Scope → Scope
ext* b zero    S = S
ext* b (suc n) S = b ∷ ext* b n S

data Mode : Set where V T : Mode

variable
  m : Mode

data _⊢[_]_ : Scope → Mode → Sort → Set

_⊢_ = _⊢[ T ]_
_∋_ = _⊢[ V ]_

data _⊢[_]_ where
  zero     : (s ∷ S) ∋ s
  suc      : S ∋ s → (s′ ∷ S) ∋ s
  `_       : S ∋ s → S ⊢ s
  Top      : S ⊢ type
  _⇒_      : S ⊢ type → S ⊢ type → S ⊢ type
  ∀[<:_]_  : S ⊢ type → (type ∷ S) ⊢ type → S ⊢ type
  RcdT     : S ⊢ rtype → S ⊢ type
  nilT     : S ⊢ rtype
  consT    : Label → S ⊢ type → S ⊢ rtype → S ⊢ rtype
  λx[_]_   : S ⊢ type → (expr ∷ S) ⊢ expr → S ⊢ expr
  Λα[<:_]_ : S ⊢ type → (type ∷ S) ⊢ expr → S ⊢ expr
  _·_      : S ⊢ expr → S ⊢ expr → S ⊢ expr
  _•_      : S ⊢ expr → S ⊢ type → S ⊢ expr
  RcdE     : S ⊢ rexpr → S ⊢ expr
  _#_      : S ⊢ expr → Label → S ⊢ expr
  letP     : S ⊢ pat 0 n → S ⊢ expr → (ext* expr n S) ⊢ expr → S ⊢ expr
  nilE     : S ⊢ rexpr
  consE    : Label → S ⊢ expr → S ⊢ rexpr → S ⊢ rexpr
  pvar     : S ⊢ type → S ⊢ pat n (suc n)
  prcd     : S ⊢ rpat n₁ n₂ → S ⊢ pat n₁ n₂
  nilP     : S ⊢ rpat n n
  consP    : Label → S ⊢ pat n₁ n₂ → S ⊢ rpat n₂ n₃ → S ⊢ rpat n₁ n₃

variable
  t t₁ t₂ t′ : S ⊢ s
  x x′       : S ∋ s
  x/t x/t′   : S ⊢[ m ] s

variable
  expr0 expr1 : S ⊢ expr
  label0 : Label
  rexpr0 : S ⊢ rexpr
  rtype0 : S ⊢ rtype
  type0 type1 : S ⊢ type

cong-letP : {pat0 pat0′ : S ⊢ pat 0 n} {expr0 expr0′ : S ⊢ expr} {expr1 expr1′ : (ext* expr n S) ⊢ expr} →
  pat0 ≡ pat0′ → expr0 ≡ expr0′ → expr1 ≡ expr1′ → letP pat0 expr0 expr1 ≡ letP pat0′ expr0′ expr1′
cong-letP refl refl refl = refl

cong-pvar : {type0 type0′ : S ⊢ type} →
  type0 ≡ type0′ → pvar {n = n} type0 ≡ pvar {n = n} type0′
cong-pvar refl = refl

cong-prcd : {rpat0 rpat0′ : S ⊢ rpat n₁ n₂} →
  rpat0 ≡ rpat0′ → prcd rpat0 ≡ prcd rpat0′
cong-prcd refl = refl

cong-consP : {label0 : Label} {pat0 pat0′ : S ⊢ pat n₁ n₂} {rpat0 rpat0′ : S ⊢ rpat n₂ n₃} →
  pat0 ≡ pat0′ → rpat0 ≡ rpat0′ → consP label0 pat0 rpat0 ≡ consP label0 pat0′ rpat0′
cong-consP refl refl = refl

-- ─── maps as vectors ────────────────────────────────────────────────

infixr 5 _∙ᴿ_ _∙ˢ_

data _→ᴿ_ : Scope → Scope → Set where
  []   : [] →ᴿ S
  _∙ᴿ_ : S₂ ∋ s → S₁ →ᴿ S₂ → (s ∷ S₁) →ᴿ S₂

data _→ˢ_ : Scope → Scope → Set where
  []   : [] →ˢ S
  _∙ˢ_ : S₂ ⊢ s → S₁ →ˢ S₂ → (s ∷ S₁) →ˢ S₂

variable
  ξ ξ′ ξ₁ ξ₂ ξ₃ : S₁ →ᴿ S₂
  σ σ′ σ₁ σ₂ σ₃ τ ρ : S₁ →ˢ S₂

-- ─── the renaming world ─────────────────────────────────────────────

opaque
  -- post-composition with weakening: the primitive recursion that lets
  -- lifting and the identity be defined without a composition cycle
  wk*ᴿ : ∀ s′ → S₁ →ᴿ S₂ → S₁ →ᴿ (s′ ∷ S₂)
  wk*ᴿ s′ []       = []
  wk*ᴿ s′ (x ∙ᴿ ξ) = suc x ∙ᴿ wk*ᴿ s′ ξ

  idᴿ : S →ᴿ S
  idᴿ {[]}    = []
  idᴿ {s ∷ S} = zero ∙ᴿ wk*ᴿ s idᴿ

  wkᴿ : ∀ s′ → S →ᴿ (s′ ∷ S)
  wkᴿ s′ = wk*ᴿ s′ idᴿ

  _↑ᴿ_ : S₁ →ᴿ S₂ → ∀ s → (s ∷ S₁) →ᴿ (s ∷ S₂)
  ξ ↑ᴿ s = zero ∙ᴿ wk*ᴿ s ξ

-- The n-fold renaming lift.  Derived and transparent, and defined
-- BETWEEN the _↑ᴿ_ block and the _[_]ᴿ block, because the traversal of a
-- variable-arity binder uses it.

_↑ᴿ*[_]_ : S₁ →ᴿ S₂ → ∀ b n → (ext* b n S₁) →ᴿ (ext* b n S₂)
ξ ↑ᴿ*[ b ] zero    = ξ
ξ ↑ᴿ*[ b ] (suc n) = (ξ ↑ᴿ*[ b ] n) ↑ᴿ b

opaque
  unfolding wk*ᴿ idᴿ wkᴿ _↑ᴿ_

  _[_]ᴿ : S₁ ⊢[ m ] s → S₁ →ᴿ S₂ → S₂ ⊢[ m ] s
  zero    [ x ∙ᴿ ξ ]ᴿ = x
  (suc y) [ x ∙ᴿ ξ ]ᴿ = y [ ξ ]ᴿ
  (`_ x) [ ξ ]ᴿ = `_ (x [ ξ ]ᴿ)
  Top                         [ ξ ]ᴿ = Top
  (_⇒_ type0 type1)           [ ξ ]ᴿ = _⇒_ (type0 [ ξ ]ᴿ) (type1 [ ξ ]ᴿ)
  (∀[<:_]_ type0 type1)       [ ξ ]ᴿ = ∀[<:_]_ (type0 [ ξ ]ᴿ) (type1 [ ξ ↑ᴿ type ]ᴿ)
  (RcdT rtype0)               [ ξ ]ᴿ = RcdT (rtype0 [ ξ ]ᴿ)
  nilT                        [ ξ ]ᴿ = nilT
  (consT label0 type0 rtype0) [ ξ ]ᴿ = consT label0 (type0 [ ξ ]ᴿ) (rtype0 [ ξ ]ᴿ)
  (λx[_]_ type0 expr0)        [ ξ ]ᴿ = λx[_]_ (type0 [ ξ ]ᴿ) (expr0 [ ξ ↑ᴿ expr ]ᴿ)
  (Λα[<:_]_ type0 expr0)      [ ξ ]ᴿ = Λα[<:_]_ (type0 [ ξ ]ᴿ) (expr0 [ ξ ↑ᴿ type ]ᴿ)
  (_·_ expr0 expr1)           [ ξ ]ᴿ = _·_ (expr0 [ ξ ]ᴿ) (expr1 [ ξ ]ᴿ)
  (_•_ expr0 type0)           [ ξ ]ᴿ = _•_ (expr0 [ ξ ]ᴿ) (type0 [ ξ ]ᴿ)
  (RcdE rexpr0)               [ ξ ]ᴿ = RcdE (rexpr0 [ ξ ]ᴿ)
  (_#_ expr0 label0)          [ ξ ]ᴿ = _#_ (expr0 [ ξ ]ᴿ) label0
  (letP pat0 expr0 expr1)     [ ξ ]ᴿ = letP (pat0 [ ξ ]ᴿ) (expr0 [ ξ ]ᴿ) (expr1 [ ξ ↑ᴿ*[ expr ] _ ]ᴿ)
  nilE                        [ ξ ]ᴿ = nilE
  (consE label0 expr0 rexpr0) [ ξ ]ᴿ = consE label0 (expr0 [ ξ ]ᴿ) (rexpr0 [ ξ ]ᴿ)
  (pvar type0)                [ ξ ]ᴿ = pvar (type0 [ ξ ]ᴿ)
  (prcd rpat0)                [ ξ ]ᴿ = prcd (rpat0 [ ξ ]ᴿ)
  nilP                        [ ξ ]ᴿ = nilP
  (consP label0 pat0 rpat0)   [ ξ ]ᴿ = consP label0 (pat0 [ ξ ]ᴿ) (rpat0 [ ξ ]ᴿ)

  _⨟ᴿ_ : S₁ →ᴿ S₂ → S₂ →ᴿ S₃ → S₁ →ᴿ S₃
  []       ⨟ᴿ ξ₂ = []
  (x ∙ᴿ ξ) ⨟ᴿ ξ₂ = (x [ ξ₂ ]ᴿ) ∙ᴿ (ξ ⨟ᴿ ξ₂)

-- ─── the substitution world ─────────────────────────────────────────

opaque
  unfolding wk*ᴿ idᴿ wkᴿ _↑ᴿ_ _[_]ᴿ _⨟ᴿ_

  ⟨_⟩ : S₁ →ᴿ S₂ → S₁ →ˢ S₂
  ⟨ [] ⟩     = []
  ⟨ x ∙ᴿ ξ ⟩ = (`_ x) ∙ˢ ⟨ ξ ⟩

  -- post-composition of a substitution with a renaming: keeps ↑ˢ
  -- structural, and is erased by ⨟ˢᴿ-def before any rule sees it
  _⨟ˢᴿ_ : S₁ →ˢ S₂ → S₂ →ᴿ S₃ → S₁ →ˢ S₃
  []       ⨟ˢᴿ ξ = []
  (t ∙ˢ σ) ⨟ˢᴿ ξ = (t [ ξ ]ᴿ) ∙ˢ (σ ⨟ˢᴿ ξ)

  _↑ˢ_ : S₁ →ˢ S₂ → ∀ s → (s ∷ S₁) →ˢ (s ∷ S₂)
  σ ↑ˢ s = (`_ zero) ∙ˢ (σ ⨟ˢᴿ wkᴿ s)

-- The n-fold substitution lift, likewise between _↑ˢ_ and _[_]ˢ.

_↑ˢ*[_]_ : S₁ →ˢ S₂ → ∀ b n → (ext* b n S₁) →ˢ (ext* b n S₂)
σ ↑ˢ*[ b ] zero    = σ
σ ↑ˢ*[ b ] (suc n) = (σ ↑ˢ*[ b ] n) ↑ˢ b

opaque
  unfolding wk*ᴿ idᴿ wkᴿ _↑ᴿ_ _[_]ᴿ ⟨_⟩ _⨟ˢᴿ_ _↑ˢ_

  _[_]ˢ : S₁ ⊢[ m ] s → S₁ →ˢ S₂ → S₂ ⊢ s
  zero    [ t ∙ˢ σ ]ˢ = t
  (suc y) [ t ∙ˢ σ ]ˢ = y [ σ ]ˢ
  (`_ x) [ σ ]ˢ = x [ σ ]ˢ
  Top                         [ σ ]ˢ = Top
  (_⇒_ type0 type1)           [ σ ]ˢ = _⇒_ (type0 [ σ ]ˢ) (type1 [ σ ]ˢ)
  (∀[<:_]_ type0 type1)       [ σ ]ˢ = ∀[<:_]_ (type0 [ σ ]ˢ) (type1 [ σ ↑ˢ type ]ˢ)
  (RcdT rtype0)               [ σ ]ˢ = RcdT (rtype0 [ σ ]ˢ)
  nilT                        [ σ ]ˢ = nilT
  (consT label0 type0 rtype0) [ σ ]ˢ = consT label0 (type0 [ σ ]ˢ) (rtype0 [ σ ]ˢ)
  (λx[_]_ type0 expr0)        [ σ ]ˢ = λx[_]_ (type0 [ σ ]ˢ) (expr0 [ σ ↑ˢ expr ]ˢ)
  (Λα[<:_]_ type0 expr0)      [ σ ]ˢ = Λα[<:_]_ (type0 [ σ ]ˢ) (expr0 [ σ ↑ˢ type ]ˢ)
  (_·_ expr0 expr1)           [ σ ]ˢ = _·_ (expr0 [ σ ]ˢ) (expr1 [ σ ]ˢ)
  (_•_ expr0 type0)           [ σ ]ˢ = _•_ (expr0 [ σ ]ˢ) (type0 [ σ ]ˢ)
  (RcdE rexpr0)               [ σ ]ˢ = RcdE (rexpr0 [ σ ]ˢ)
  (_#_ expr0 label0)          [ σ ]ˢ = _#_ (expr0 [ σ ]ˢ) label0
  (letP pat0 expr0 expr1)     [ σ ]ˢ = letP (pat0 [ σ ]ˢ) (expr0 [ σ ]ˢ) (expr1 [ σ ↑ˢ*[ expr ] _ ]ˢ)
  nilE                        [ σ ]ˢ = nilE
  (consE label0 expr0 rexpr0) [ σ ]ˢ = consE label0 (expr0 [ σ ]ˢ) (rexpr0 [ σ ]ˢ)
  (pvar type0)                [ σ ]ˢ = pvar (type0 [ σ ]ˢ)
  (prcd rpat0)                [ σ ]ˢ = prcd (rpat0 [ σ ]ˢ)
  nilP                        [ σ ]ˢ = nilP
  (consP label0 pat0 rpat0)   [ σ ]ˢ = consP label0 (pat0 [ σ ]ˢ) (rpat0 [ σ ]ˢ)

  _⨟_ : S₁ →ˢ S₂ → S₂ →ˢ S₃ → S₁ →ˢ S₃
  []       ⨟ σ₂ = []
  (t ∙ˢ σ) ⨟ σ₂ = (t [ σ₂ ]ˢ) ∙ˢ (σ ⨟ σ₂)

idˢ : S →ˢ S
idˢ = ⟨ idᴿ ⟩

wkˢ : ∀ s′ → S →ˢ (s′ ∷ S)
wkˢ s′ = ⟨ wkᴿ s′ ⟩

-- ─── the two-world rewrite system ───────────────────────────────────

opaque
  unfolding wk*ᴿ idᴿ wkᴿ _↑ᴿ_ _[_]ᴿ _⨟ᴿ_

  -- ══ Iᴿ. applied rules, renaming world ═════════════════════════════
  def-∙ᴿ-zero : zero [ (x ∙ᴿ ξ) ]ᴿ ≡ x
  def-∙ᴿ-zero = refl

  def-∙ᴿ-suc : (suc {s′ = s′} x′) [ (x ∙ᴿ ξ) ]ᴿ ≡ x′ [ ξ ]ᴿ
  def-∙ᴿ-suc = refl

  lookup-wk*ᴿ : ∀ (x : S₁ ∋ s) (ξ : S₁ →ᴿ S₂) → x [ wk*ᴿ s′ ξ ]ᴿ ≡ suc (x [ ξ ]ᴿ)
  lookup-wk*ᴿ zero    (y ∙ᴿ ξ) = refl
  lookup-wk*ᴿ (suc x) (y ∙ᴿ ξ) = lookup-wk*ᴿ x ξ

  lookup-idᴿ : ∀ (x : S ∋ s) → x [ idᴿ ]ᴿ ≡ x
  lookup-idᴿ zero    = refl
  lookup-idᴿ (suc x) = trans (lookup-wk*ᴿ x idᴿ) (cong suc (lookup-idᴿ x))

  def-wkᴿ : x [ wkᴿ s′ ]ᴿ ≡ suc x
  def-wkᴿ {x = x} = trans (lookup-wk*ᴿ x idᴿ) (cong suc (lookup-idᴿ x))

  def-↑ᴿ-zero : zero [ (ξ ↑ᴿ s) ]ᴿ ≡ zero
  def-↑ᴿ-zero = refl

  def-↑ᴿ-suc : (suc x) [ (ξ ↑ᴿ s) ]ᴿ ≡ suc (x [ ξ ]ᴿ)
  def-↑ᴿ-suc {x = x} {ξ = ξ} = lookup-wk*ᴿ x ξ

  lift-idᴿ : (idᴿ {S} ↑ᴿ s) ≡ idᴿ
  lift-idᴿ = refl

  -- ══ IIᴿ. traversal rules, renaming world ═════════════════════════
  instᴿ-var : (`_ x) [ ξ ]ᴿ ≡ `_ (x [ ξ ]ᴿ)
  instᴿ-Top      : Top {S = S} [ ξ ]ᴿ                                                                                          ≡ Top
  instᴿ-_⇒_      : (_⇒_ type0 type1) [ ξ ]ᴿ                                                                                    ≡ _⇒_ (type0 [ ξ ]ᴿ) (type1 [ ξ ]ᴿ)
  instᴿ-∀[<:_]_  : (∀[<:_]_ type0 type1) [ ξ ]ᴿ                                                                                ≡ ∀[<:_]_ (type0 [ ξ ]ᴿ) (type1 [ ξ ↑ᴿ type ]ᴿ)
  instᴿ-RcdT     : (RcdT rtype0) [ ξ ]ᴿ                                                                                        ≡ RcdT (rtype0 [ ξ ]ᴿ)
  instᴿ-nilT     : nilT {S = S} [ ξ ]ᴿ                                                                                         ≡ nilT
  instᴿ-consT    : (consT label0 type0 rtype0) [ ξ ]ᴿ                                                                          ≡ consT label0 (type0 [ ξ ]ᴿ) (rtype0 [ ξ ]ᴿ)
  instᴿ-λx[_]_   : (λx[_]_ type0 expr0) [ ξ ]ᴿ                                                                                 ≡ λx[_]_ (type0 [ ξ ]ᴿ) (expr0 [ ξ ↑ᴿ expr ]ᴿ)
  instᴿ-Λα[<:_]_ : (Λα[<:_]_ type0 expr0) [ ξ ]ᴿ                                                                               ≡ Λα[<:_]_ (type0 [ ξ ]ᴿ) (expr0 [ ξ ↑ᴿ type ]ᴿ)
  instᴿ-_·_      : (_·_ expr0 expr1) [ ξ ]ᴿ                                                                                    ≡ _·_ (expr0 [ ξ ]ᴿ) (expr1 [ ξ ]ᴿ)
  instᴿ-_•_      : (_•_ expr0 type0) [ ξ ]ᴿ                                                                                    ≡ _•_ (expr0 [ ξ ]ᴿ) (type0 [ ξ ]ᴿ)
  instᴿ-RcdE     : (RcdE rexpr0) [ ξ ]ᴿ                                                                                        ≡ RcdE (rexpr0 [ ξ ]ᴿ)
  instᴿ-_#_      : (_#_ expr0 label0) [ ξ ]ᴿ                                                                                   ≡ _#_ (expr0 [ ξ ]ᴿ) label0
  instᴿ-letP     : ∀ {pat0 : S ⊢ pat 0 n} {expr0 : S ⊢ expr} {expr1 : (ext* expr n S) ⊢ expr} → (letP pat0 expr0 expr1) [ ξ ]ᴿ ≡ letP (pat0 [ ξ ]ᴿ) (expr0 [ ξ ]ᴿ) (expr1 [ ξ ↑ᴿ*[ expr ] n ]ᴿ)
  instᴿ-nilE     : nilE {S = S} [ ξ ]ᴿ                                                                                         ≡ nilE
  instᴿ-consE    : (consE label0 expr0 rexpr0) [ ξ ]ᴿ                                                                          ≡ consE label0 (expr0 [ ξ ]ᴿ) (rexpr0 [ ξ ]ᴿ)
  instᴿ-pvar     : ∀ {type0 : S ⊢ type} → (pvar {n = n} type0) [ ξ ]ᴿ                                                          ≡ pvar (type0 [ ξ ]ᴿ)
  instᴿ-prcd     : ∀ {rpat0 : S ⊢ rpat n₁ n₂} → (prcd rpat0) [ ξ ]ᴿ                                                            ≡ prcd (rpat0 [ ξ ]ᴿ)
  instᴿ-nilP     : nilP {S = S} {n = n} [ ξ ]ᴿ                                                                                 ≡ nilP
  instᴿ-consP    : ∀ {pat0 : S ⊢ pat n₁ n₂} {rpat0 : S ⊢ rpat n₂ n₃} → (consP label0 pat0 rpat0) [ ξ ]ᴿ                        ≡ consP label0 (pat0 [ ξ ]ᴿ) (rpat0 [ ξ ]ᴿ)
  instᴿ-var = refl
  instᴿ-Top      = refl
  instᴿ-_⇒_      = refl
  instᴿ-∀[<:_]_  = refl
  instᴿ-RcdT     = refl
  instᴿ-nilT     = refl
  instᴿ-consT    = refl
  instᴿ-λx[_]_   = refl
  instᴿ-Λα[<:_]_ = refl
  instᴿ-_·_      = refl
  instᴿ-_•_      = refl
  instᴿ-RcdE     = refl
  instᴿ-_#_      = refl
  instᴿ-letP     = refl
  instᴿ-nilE     = refl
  instᴿ-consE    = refl
  instᴿ-pvar     = refl
  instᴿ-prcd     = refl
  instᴿ-nilP     = refl
  instᴿ-consP    = refl

  -- ══ IIIᴿ. map algebra, renaming world ════════════════════════════
  distᴿ : (x ∙ᴿ ξ₁) ⨟ᴿ ξ₂ ≡ (x [ ξ₂ ]ᴿ) ∙ᴿ (ξ₁ ⨟ᴿ ξ₂)
  distᴿ = refl

  compositionalityᴿᴿ-var : ∀ (x : S₁ ∋ s) {ξ₁ : S₁ →ᴿ S₂} {ξ₂ : S₂ →ᴿ S₃} →
    x [ (ξ₁ ⨟ᴿ ξ₂) ]ᴿ ≡ (x [ ξ₁ ]ᴿ) [ ξ₂ ]ᴿ
  compositionalityᴿᴿ-var zero    {ξ₁ = y ∙ᴿ ξ₁} = refl
  compositionalityᴿᴿ-var (suc x) {ξ₁ = y ∙ᴿ ξ₁} = compositionalityᴿᴿ-var x

  wk*ᴿ-⨟ᴿ : ∀ (ξ₁ : S₁ →ᴿ S₂) (x : S₃ ∋ s′) (ξ₂ : S₂ →ᴿ S₃) →
    wk*ᴿ s′ ξ₁ ⨟ᴿ (x ∙ᴿ ξ₂) ≡ ξ₁ ⨟ᴿ ξ₂
  wk*ᴿ-⨟ᴿ []        x ξ₂ = refl
  wk*ᴿ-⨟ᴿ (y ∙ᴿ ξ₁) x ξ₂ = cong (_ ∙ᴿ_) (wk*ᴿ-⨟ᴿ ξ₁ x ξ₂)

  comp-idₗᴿ : idᴿ ⨟ᴿ ξ ≡ ξ
  comp-idₗᴿ {ξ = []}     = refl
  comp-idₗᴿ {ξ = x ∙ᴿ ξ} = cong (x ∙ᴿ_) (trans (wk*ᴿ-⨟ᴿ idᴿ x ξ) comp-idₗᴿ)

  comp-idᵣᴿ : ξ ⨟ᴿ idᴿ ≡ ξ
  comp-idᵣᴿ {ξ = []}     = refl
  comp-idᵣᴿ {ξ = x ∙ᴿ ξ} = cong2 _∙ᴿ_ (lookup-idᴿ x) comp-idᵣᴿ

  interactᴿ : wkᴿ s ⨟ᴿ (x ∙ᴿ ξ) ≡ ξ
  interactᴿ {x = x} {ξ = ξ} = trans (wk*ᴿ-⨟ᴿ idᴿ x ξ) comp-idₗᴿ

  lift-consᴿ : (ξ ↑ᴿ s) ⨟ᴿ (x ∙ᴿ ξ′) ≡ x ∙ᴿ (ξ ⨟ᴿ ξ′)
  lift-consᴿ {ξ = ξ} {x = x} {ξ′ = ξ′} = cong (x ∙ᴿ_) (wk*ᴿ-⨟ᴿ ξ x ξ′)

  assocᴿ : (ξ₁ ⨟ᴿ ξ₂) ⨟ᴿ ξ₃ ≡ ξ₁ ⨟ᴿ (ξ₂ ⨟ᴿ ξ₃)
  assocᴿ {ξ₁ = []}      = refl
  assocᴿ {ξ₁ = x ∙ᴿ ξ₁} = cong2 _∙ᴿ_ (sym (compositionalityᴿᴿ-var x)) assocᴿ

  wk*ᴿ-comp : ∀ (ξ₁ : S₁ →ᴿ S₂) (ξ₂ : S₂ →ᴿ S₃) →
    wk*ᴿ s ξ₁ ⨟ᴿ (ξ₂ ↑ᴿ s) ≡ wk*ᴿ s (ξ₁ ⨟ᴿ ξ₂)
  wk*ᴿ-comp []        ξ₂ = refl
  wk*ᴿ-comp (x ∙ᴿ ξ₁) ξ₂ = cong2 _∙ᴿ_ (lookup-wk*ᴿ x ξ₂) (wk*ᴿ-comp ξ₁ ξ₂)

  ⨟ᴿ-wk*ᴿ : ∀ (ξ₁ : S₁ →ᴿ S₂) (ξ₂ : S₂ →ᴿ S₃) →
    ξ₁ ⨟ᴿ wk*ᴿ s ξ₂ ≡ wk*ᴿ s (ξ₁ ⨟ᴿ ξ₂)
  ⨟ᴿ-wk*ᴿ []        ξ₂ = refl
  ⨟ᴿ-wk*ᴿ (x ∙ᴿ ξ₁) ξ₂ = cong2 _∙ᴿ_ (lookup-wk*ᴿ x ξ₂) (⨟ᴿ-wk*ᴿ ξ₁ ξ₂)

  lift-dist-compᴿᴿ : ((ξ₁ ↑ᴿ s) ⨟ᴿ (ξ₂ ↑ᴿ s)) ≡ ((ξ₁ ⨟ᴿ ξ₂) ↑ᴿ s)
  lift-dist-compᴿᴿ {ξ₁ = ξ₁} {ξ₂ = ξ₂} = cong (zero ∙ᴿ_) (wk*ᴿ-comp ξ₁ ξ₂)

  lift-wkᴿ : wkᴿ s ⨟ᴿ (ξ ↑ᴿ s) ≡ ξ ⨟ᴿ wkᴿ s
  lift-wkᴿ {ξ = ξ} = trans (wk*ᴿ-comp idᴿ ξ)
    (trans (cong (wk*ᴿ _) comp-idₗᴿ)
    (sym (trans (⨟ᴿ-wk*ᴿ ξ idᴿ) (cong (wk*ᴿ _) comp-idᵣᴿ))))

  -- ══ Vᴿ. monad laws, renaming world ═══════════════════════════════
  right-idᴿ : ∀ (x/t : S ⊢[ m ] s) → x/t [ idᴿ ]ᴿ ≡ x/t
  right-idᴿ zero    = refl
  right-idᴿ (suc x) = lookup-idᴿ (suc x)
  right-idᴿ (`_ x)   = cong `_ (lookup-idᴿ x)
  right-idᴿ Top                             = refl
  right-idᴿ (_⇒_ type0 type1)               = cong2 _⇒_ (right-idᴿ type0) (right-idᴿ type1)
  right-idᴿ (∀[<:_]_ type0 type1)           = cong2 ∀[<:_]_ (right-idᴿ type0) (trans (cong (type1 [_]ᴿ) lift-idᴿ) (right-idᴿ type1))
  right-idᴿ (RcdT rtype0)                   = cong1 RcdT (right-idᴿ rtype0)
  right-idᴿ nilT                            = refl
  right-idᴿ (consT label0 type0 rtype0)     = cong3 consT refl (right-idᴿ type0) (right-idᴿ rtype0)
  right-idᴿ (λx[_]_ type0 expr0)            = cong2 λx[_]_ (right-idᴿ type0) (trans (cong (expr0 [_]ᴿ) lift-idᴿ) (right-idᴿ expr0))
  right-idᴿ (Λα[<:_]_ type0 expr0)          = cong2 Λα[<:_]_ (right-idᴿ type0) (trans (cong (expr0 [_]ᴿ) lift-idᴿ) (right-idᴿ expr0))
  right-idᴿ (_·_ expr0 expr1)               = cong2 _·_ (right-idᴿ expr0) (right-idᴿ expr1)
  right-idᴿ (_•_ expr0 type0)               = cong2 _•_ (right-idᴿ expr0) (right-idᴿ type0)
  right-idᴿ (RcdE rexpr0)                   = cong1 RcdE (right-idᴿ rexpr0)
  right-idᴿ (_#_ expr0 label0)              = cong2 _#_ (right-idᴿ expr0) refl
  right-idᴿ (letP {n = n} pat0 expr0 expr1) = cong-letP (right-idᴿ pat0) (right-idᴿ expr0) (trans (cong (expr1 [_]ᴿ) (lift*-idᴿ expr n)) (right-idᴿ expr1))
  right-idᴿ nilE                            = refl
  right-idᴿ (consE label0 expr0 rexpr0)     = cong3 consE refl (right-idᴿ expr0) (right-idᴿ rexpr0)
  right-idᴿ (pvar type0)                    = cong-pvar (right-idᴿ type0)
  right-idᴿ (prcd rpat0)                    = cong-prcd (right-idᴿ rpat0)
  right-idᴿ nilP                            = refl
  right-idᴿ (consP label0 pat0 rpat0)       = cong-consP (right-idᴿ pat0) (right-idᴿ rpat0)

  compositionalityᴿᴿ : ∀ (x/t : S₁ ⊢[ m ] s) {ξ₁ : S₁ →ᴿ S₂} {ξ₂ : S₂ →ᴿ S₃} →
    (x/t [ ξ₁ ]ᴿ) [ ξ₂ ]ᴿ ≡ x/t [ (ξ₁ ⨟ᴿ ξ₂) ]ᴿ
  compositionalityᴿᴿ zero    {ξ₁ = y ∙ᴿ ξ₁} = refl
  compositionalityᴿᴿ (suc x) {ξ₁ = y ∙ᴿ ξ₁} = compositionalityᴿᴿ x
  compositionalityᴿᴿ (`_ x) = cong `_ (compositionalityᴿᴿ x)
  compositionalityᴿᴿ Top                             = refl
  compositionalityᴿᴿ (_⇒_ type0 type1)               = cong2 _⇒_ (compositionalityᴿᴿ type0) (compositionalityᴿᴿ type1)
  compositionalityᴿᴿ (∀[<:_]_ type0 type1)           = cong2 ∀[<:_]_ (compositionalityᴿᴿ type0) (trans (compositionalityᴿᴿ type1) (cong (type1 [_]ᴿ) lift-dist-compᴿᴿ))
  compositionalityᴿᴿ (RcdT rtype0)                   = cong1 RcdT (compositionalityᴿᴿ rtype0)
  compositionalityᴿᴿ nilT                            = refl
  compositionalityᴿᴿ (consT label0 type0 rtype0)     = cong3 consT refl (compositionalityᴿᴿ type0) (compositionalityᴿᴿ rtype0)
  compositionalityᴿᴿ (λx[_]_ type0 expr0)            = cong2 λx[_]_ (compositionalityᴿᴿ type0) (trans (compositionalityᴿᴿ expr0) (cong (expr0 [_]ᴿ) lift-dist-compᴿᴿ))
  compositionalityᴿᴿ (Λα[<:_]_ type0 expr0)          = cong2 Λα[<:_]_ (compositionalityᴿᴿ type0) (trans (compositionalityᴿᴿ expr0) (cong (expr0 [_]ᴿ) lift-dist-compᴿᴿ))
  compositionalityᴿᴿ (_·_ expr0 expr1)               = cong2 _·_ (compositionalityᴿᴿ expr0) (compositionalityᴿᴿ expr1)
  compositionalityᴿᴿ (_•_ expr0 type0)               = cong2 _•_ (compositionalityᴿᴿ expr0) (compositionalityᴿᴿ type0)
  compositionalityᴿᴿ (RcdE rexpr0)                   = cong1 RcdE (compositionalityᴿᴿ rexpr0)
  compositionalityᴿᴿ (_#_ expr0 label0)              = cong2 _#_ (compositionalityᴿᴿ expr0) refl
  compositionalityᴿᴿ (letP {n = n} pat0 expr0 expr1) = cong-letP (compositionalityᴿᴿ pat0) (compositionalityᴿᴿ expr0) (trans (compositionalityᴿᴿ expr1) (cong (expr1 [_]ᴿ) (lift*-dist-compᴿᴿ expr n)))
  compositionalityᴿᴿ nilE                            = refl
  compositionalityᴿᴿ (consE label0 expr0 rexpr0)     = cong3 consE refl (compositionalityᴿᴿ expr0) (compositionalityᴿᴿ rexpr0)
  compositionalityᴿᴿ (pvar type0)                    = cong-pvar (compositionalityᴿᴿ type0)
  compositionalityᴿᴿ (prcd rpat0)                    = cong-prcd (compositionalityᴿᴿ rpat0)
  compositionalityᴿᴿ nilP                            = refl
  compositionalityᴿᴿ (consP label0 pat0 rpat0)       = cong-consP (compositionalityᴿᴿ pat0) (compositionalityᴿᴿ rpat0)

-- ─── the substitution world ─────────────────────────────────────────

opaque
  unfolding wk*ᴿ idᴿ wkᴿ _↑ᴿ_ _[_]ᴿ _⨟ᴿ_ ⟨_⟩ _⨟ˢᴿ_ _↑ˢ_ _[_]ˢ _⨟_

  ⟨⟩-⨟ˢᴿ-wk : ∀ (ξ : S₁ →ᴿ S₂) → ⟨ ξ ⟩ ⨟ˢᴿ wkᴿ s ≡ ⟨ wk*ᴿ s ξ ⟩
  ⟨⟩-⨟ˢᴿ-wk []       = refl
  ⟨⟩-⨟ˢᴿ-wk (x ∙ᴿ ξ) = cong2 _∙ˢ_ (cong `_ def-wkᴿ) (⟨⟩-⨟ˢᴿ-wk ξ)

  ⟨⟩-lift : (⟨ ξ ⟩ ↑ˢ s) ≡ ⟨ ξ ↑ᴿ s ⟩
  ⟨⟩-lift {ξ = ξ} = cong ((`_ zero) ∙ˢ_) (⟨⟩-⨟ˢᴿ-wk ξ)

  coincidence-var : ∀ (x : S₁ ∋ s) (ξ : S₁ →ᴿ S₂) → x [ ⟨ ξ ⟩ ]ˢ ≡ `_ (x [ ξ ]ᴿ)
  coincidence-var zero    (y ∙ᴿ ξ) = refl
  coincidence-var (suc x) (y ∙ᴿ ξ) = coincidence-var x ξ

  coincidence : ∀ (t : S₁ ⊢ s) (ξ : S₁ →ᴿ S₂) → t [ ⟨ ξ ⟩ ]ˢ ≡ t [ ξ ]ᴿ
  coincidence (`_ x) ξ = coincidence-var x ξ
  coincidence Top ξ                             = refl
  coincidence (_⇒_ type0 type1) ξ               = cong2 _⇒_ (coincidence type0 ξ) (coincidence type1 ξ)
  coincidence (∀[<:_]_ type0 type1) ξ           = cong2 ∀[<:_]_ (coincidence type0 ξ) (trans (cong (type1 [_]ˢ) (⟨⟩-lift {ξ = ξ})) (coincidence type1 (ξ ↑ᴿ type)))
  coincidence (RcdT rtype0) ξ                   = cong1 RcdT (coincidence rtype0 ξ)
  coincidence nilT ξ                            = refl
  coincidence (consT label0 type0 rtype0) ξ     = cong3 consT refl (coincidence type0 ξ) (coincidence rtype0 ξ)
  coincidence (λx[_]_ type0 expr0) ξ            = cong2 λx[_]_ (coincidence type0 ξ) (trans (cong (expr0 [_]ˢ) (⟨⟩-lift {ξ = ξ})) (coincidence expr0 (ξ ↑ᴿ expr)))
  coincidence (Λα[<:_]_ type0 expr0) ξ          = cong2 Λα[<:_]_ (coincidence type0 ξ) (trans (cong (expr0 [_]ˢ) (⟨⟩-lift {ξ = ξ})) (coincidence expr0 (ξ ↑ᴿ type)))
  coincidence (_·_ expr0 expr1) ξ               = cong2 _·_ (coincidence expr0 ξ) (coincidence expr1 ξ)
  coincidence (_•_ expr0 type0) ξ               = cong2 _•_ (coincidence expr0 ξ) (coincidence type0 ξ)
  coincidence (RcdE rexpr0) ξ                   = cong1 RcdE (coincidence rexpr0 ξ)
  coincidence (_#_ expr0 label0) ξ              = cong2 _#_ (coincidence expr0 ξ) refl
  coincidence (letP {n = n} pat0 expr0 expr1) ξ = cong-letP (coincidence pat0 ξ) (coincidence expr0 ξ) (trans (cong (expr1 [_]ˢ) (⟨⟩-lift* {ξ = ξ} expr n)) (coincidence expr1 (ξ ↑ᴿ*[ expr ] n)))
  coincidence nilE ξ                            = refl
  coincidence (consE label0 expr0 rexpr0) ξ     = cong3 consE refl (coincidence expr0 ξ) (coincidence rexpr0 ξ)
  coincidence (pvar type0) ξ                    = cong-pvar (coincidence type0 ξ)
  coincidence (prcd rpat0) ξ                    = cong-prcd (coincidence rpat0 ξ)
  coincidence nilP ξ                            = refl
  coincidence (consP label0 pat0 rpat0) ξ       = cong-consP (coincidence pat0 ξ) (coincidence rpat0 ξ)

  ⨟ˢᴿ-def : ∀ (σ : S₁ →ˢ S₂) (ξ : S₂ →ᴿ S₃) → σ ⨟ˢᴿ ξ ≡ σ ⨟ ⟨ ξ ⟩
  ⨟ˢᴿ-def []       ξ = refl
  ⨟ˢᴿ-def (t ∙ˢ σ) ξ = cong2 _∙ˢ_ (sym (coincidence t ξ)) (⨟ˢᴿ-def σ ξ)

  -- ══ Iˢ. applied rules, substitution world ════════════════════════
  def-∙ˢ-zero : zero [ (t ∙ˢ σ) ]ˢ ≡ t
  def-∙ˢ-zero = refl

  def-∙ˢ-suc : (suc {s′ = s′} x) [ (t ∙ˢ σ) ]ˢ ≡ x [ σ ]ˢ
  def-∙ˢ-suc = refl

  def-↑ˢ-zero : zero [ (σ ↑ˢ s) ]ˢ ≡ `_ zero
  def-↑ˢ-zero = refl

  def-↑ˢ-suc : (suc x) [ (σ ↑ˢ s) ]ˢ ≡ x [ (σ ⨟ ⟨ wkᴿ s ⟩) ]ˢ
  def-↑ˢ-suc {x = x} {σ = σ} {s = s} = cong (x [_]ˢ) (⨟ˢᴿ-def σ (wkᴿ s))

  -- ══ lookup through the two hybrid compositions ═══════════════════
  lookup-⨟ˢᴿ : ∀ (x : S₁ ∋ s) (σ : S₁ →ˢ S₂) (ξ : S₂ →ᴿ S₃) →
    x [ σ ⨟ˢᴿ ξ ]ˢ ≡ (x [ σ ]ˢ) [ ξ ]ᴿ
  lookup-⨟ˢᴿ zero    (t ∙ˢ σ) ξ = refl
  lookup-⨟ˢᴿ (suc x) (t ∙ˢ σ) ξ = lookup-⨟ˢᴿ x σ ξ

  -- ══ IIIˢ/IVˢ. map algebra and lifting, substitution world ════════
  dist : (t ∙ˢ σ₁) ⨟ σ₂ ≡ (t [ σ₂ ]ˢ) ∙ˢ (σ₁ ⨟ σ₂)
  dist = refl

  ⟨wk*⟩-cons : ∀ (ξ : S₁ →ᴿ S₂) (t : S₃ ⊢ s′) (σ : S₂ →ˢ S₃) →
    ⟨ wk*ᴿ s′ ξ ⟩ ⨟ (t ∙ˢ σ) ≡ ⟨ ξ ⟩ ⨟ σ
  ⟨wk*⟩-cons []       t σ = refl
  ⟨wk*⟩-cons (x ∙ᴿ ξ) t σ = cong (_ ∙ˢ_) (⟨wk*⟩-cons ξ t σ)

  comp-idₗ : ⟨ idᴿ {S₁} ⟩ ⨟ σ ≡ σ
  comp-idₗ {σ = []}     = refl
  comp-idₗ {σ = t ∙ˢ σ} = cong (t ∙ˢ_) (trans (⟨wk*⟩-cons idᴿ t σ) comp-idₗ)

  interact : ⟨ wkᴿ s ⟩ ⨟ (t ∙ˢ σ) ≡ σ
  interact {t = t} {σ = σ} = trans (⟨wk*⟩-cons idᴿ t σ) comp-idₗ

  ⟨wk*⟩-lift : ∀ (ξ : S₁ →ᴿ S₂) (σ : S₂ →ˢ S₃) →
    ⟨ wk*ᴿ s ξ ⟩ ⨟ (σ ↑ˢ s) ≡ (⟨ ξ ⟩ ⨟ σ) ⨟ˢᴿ wkᴿ s
  ⟨wk*⟩-lift []       σ = refl
  ⟨wk*⟩-lift (x ∙ᴿ ξ) σ = cong2 _∙ˢ_ (lookup-⨟ˢᴿ x σ (wkᴿ _)) (⟨wk*⟩-lift ξ σ)

  lift-dist-compᴿˢ : ⟨ ξ ↑ᴿ s ⟩ ⨟ (σ ↑ˢ s) ≡ ((⟨ ξ ⟩ ⨟ σ) ↑ˢ s)
  lift-dist-compᴿˢ {ξ = ξ} {σ = σ} = cong ((`_ zero) ∙ˢ_) (⟨wk*⟩-lift ξ σ)

  -- ══ the mixed compositionality laws, stratified ══════════════════
  compositionalityᴿˢ : ∀ (x/t : S₁ ⊢[ m ] s) {ξ : S₁ →ᴿ S₂} {σ : S₂ →ˢ S₃} →
    (x/t [ ξ ]ᴿ) [ σ ]ˢ ≡ x/t [ (⟨ ξ ⟩ ⨟ σ) ]ˢ
  compositionalityᴿˢ zero    {ξ = y ∙ᴿ ξ} = refl
  compositionalityᴿˢ (suc x) {ξ = y ∙ᴿ ξ} = compositionalityᴿˢ x
  compositionalityᴿˢ (`_ x) = compositionalityᴿˢ x
  compositionalityᴿˢ Top                             = refl
  compositionalityᴿˢ (_⇒_ type0 type1)               = cong2 _⇒_ (compositionalityᴿˢ type0) (compositionalityᴿˢ type1)
  compositionalityᴿˢ (∀[<:_]_ type0 type1)           = cong2 ∀[<:_]_ (compositionalityᴿˢ type0) (trans (compositionalityᴿˢ type1) (cong (type1 [_]ˢ) lift-dist-compᴿˢ))
  compositionalityᴿˢ (RcdT rtype0)                   = cong1 RcdT (compositionalityᴿˢ rtype0)
  compositionalityᴿˢ nilT                            = refl
  compositionalityᴿˢ (consT label0 type0 rtype0)     = cong3 consT refl (compositionalityᴿˢ type0) (compositionalityᴿˢ rtype0)
  compositionalityᴿˢ (λx[_]_ type0 expr0)            = cong2 λx[_]_ (compositionalityᴿˢ type0) (trans (compositionalityᴿˢ expr0) (cong (expr0 [_]ˢ) lift-dist-compᴿˢ))
  compositionalityᴿˢ (Λα[<:_]_ type0 expr0)          = cong2 Λα[<:_]_ (compositionalityᴿˢ type0) (trans (compositionalityᴿˢ expr0) (cong (expr0 [_]ˢ) lift-dist-compᴿˢ))
  compositionalityᴿˢ (_·_ expr0 expr1)               = cong2 _·_ (compositionalityᴿˢ expr0) (compositionalityᴿˢ expr1)
  compositionalityᴿˢ (_•_ expr0 type0)               = cong2 _•_ (compositionalityᴿˢ expr0) (compositionalityᴿˢ type0)
  compositionalityᴿˢ (RcdE rexpr0)                   = cong1 RcdE (compositionalityᴿˢ rexpr0)
  compositionalityᴿˢ (_#_ expr0 label0)              = cong2 _#_ (compositionalityᴿˢ expr0) refl
  compositionalityᴿˢ (letP {n = n} pat0 expr0 expr1) = cong-letP (compositionalityᴿˢ pat0) (compositionalityᴿˢ expr0) (trans (compositionalityᴿˢ expr1) (cong (expr1 [_]ˢ) (lift*-dist-compᴿˢ expr n)))
  compositionalityᴿˢ nilE                            = refl
  compositionalityᴿˢ (consE label0 expr0 rexpr0)     = cong3 consE refl (compositionalityᴿˢ expr0) (compositionalityᴿˢ rexpr0)
  compositionalityᴿˢ (pvar type0)                    = cong-pvar (compositionalityᴿˢ type0)
  compositionalityᴿˢ (prcd rpat0)                    = cong-prcd (compositionalityᴿˢ rpat0)
  compositionalityᴿˢ nilP                            = refl
  compositionalityᴿˢ (consP label0 pat0 rpat0)       = cong-consP (compositionalityᴿˢ pat0) (compositionalityᴿˢ rpat0)

  ⨟ˢᴿ-lift : ∀ (σ : S₁ →ˢ S₂) (ξ : S₂ →ᴿ S₃) →
    (σ ⨟ˢᴿ wkᴿ s) ⨟ˢᴿ (ξ ↑ᴿ s) ≡ (σ ⨟ˢᴿ ξ) ⨟ˢᴿ wkᴿ s
  ⨟ˢᴿ-lift []       ξ = refl
  ⨟ˢᴿ-lift (t ∙ˢ σ) ξ = cong2 _∙ˢ_
    (trans (compositionalityᴿᴿ t) (trans (cong (t [_]ᴿ) lift-wkᴿ) (sym (compositionalityᴿᴿ t))))
    (⨟ˢᴿ-lift σ ξ)

  lift-⨟ˢᴿ : ∀ {σ : S₁ →ˢ S₂} {ξ : S₂ →ᴿ S₃} →
    (σ ↑ˢ s) ⨟ˢᴿ (ξ ↑ᴿ s) ≡ ((σ ⨟ˢᴿ ξ) ↑ˢ s)
  lift-⨟ˢᴿ {σ = σ} {ξ = ξ} = cong ((`_ zero) ∙ˢ_) (⨟ˢᴿ-lift σ ξ)

  compositionalityˢᴿ′ : ∀ (x/t : S₁ ⊢[ m ] s) {σ : S₁ →ˢ S₂} {ξ : S₂ →ᴿ S₃} →
    (x/t [ σ ]ˢ) [ ξ ]ᴿ ≡ x/t [ (σ ⨟ˢᴿ ξ) ]ˢ
  compositionalityˢᴿ′ zero    {σ = t ∙ˢ σ} = refl
  compositionalityˢᴿ′ (suc x) {σ = t ∙ˢ σ} = compositionalityˢᴿ′ x
  compositionalityˢᴿ′ (`_ x) = compositionalityˢᴿ′ x
  compositionalityˢᴿ′ Top                             = refl
  compositionalityˢᴿ′ (_⇒_ type0 type1)               = cong2 _⇒_ (compositionalityˢᴿ′ type0) (compositionalityˢᴿ′ type1)
  compositionalityˢᴿ′ (∀[<:_]_ type0 type1)           = cong2 ∀[<:_]_ (compositionalityˢᴿ′ type0) (trans (compositionalityˢᴿ′ type1) (cong (type1 [_]ˢ) lift-⨟ˢᴿ))
  compositionalityˢᴿ′ (RcdT rtype0)                   = cong1 RcdT (compositionalityˢᴿ′ rtype0)
  compositionalityˢᴿ′ nilT                            = refl
  compositionalityˢᴿ′ (consT label0 type0 rtype0)     = cong3 consT refl (compositionalityˢᴿ′ type0) (compositionalityˢᴿ′ rtype0)
  compositionalityˢᴿ′ (λx[_]_ type0 expr0)            = cong2 λx[_]_ (compositionalityˢᴿ′ type0) (trans (compositionalityˢᴿ′ expr0) (cong (expr0 [_]ˢ) lift-⨟ˢᴿ))
  compositionalityˢᴿ′ (Λα[<:_]_ type0 expr0)          = cong2 Λα[<:_]_ (compositionalityˢᴿ′ type0) (trans (compositionalityˢᴿ′ expr0) (cong (expr0 [_]ˢ) lift-⨟ˢᴿ))
  compositionalityˢᴿ′ (_·_ expr0 expr1)               = cong2 _·_ (compositionalityˢᴿ′ expr0) (compositionalityˢᴿ′ expr1)
  compositionalityˢᴿ′ (_•_ expr0 type0)               = cong2 _•_ (compositionalityˢᴿ′ expr0) (compositionalityˢᴿ′ type0)
  compositionalityˢᴿ′ (RcdE rexpr0)                   = cong1 RcdE (compositionalityˢᴿ′ rexpr0)
  compositionalityˢᴿ′ (_#_ expr0 label0)              = cong2 _#_ (compositionalityˢᴿ′ expr0) refl
  compositionalityˢᴿ′ (letP {n = n} pat0 expr0 expr1) = cong-letP (compositionalityˢᴿ′ pat0) (compositionalityˢᴿ′ expr0) (trans (compositionalityˢᴿ′ expr1) (cong (expr1 [_]ˢ) (lift*-⨟ˢᴿ expr n)))
  compositionalityˢᴿ′ nilE                            = refl
  compositionalityˢᴿ′ (consE label0 expr0 rexpr0)     = cong3 consE refl (compositionalityˢᴿ′ expr0) (compositionalityˢᴿ′ rexpr0)
  compositionalityˢᴿ′ (pvar type0)                    = cong-pvar (compositionalityˢᴿ′ type0)
  compositionalityˢᴿ′ (prcd rpat0)                    = cong-prcd (compositionalityˢᴿ′ rpat0)
  compositionalityˢᴿ′ nilP                            = refl
  compositionalityˢᴿ′ (consP label0 pat0 rpat0)       = cong-consP (compositionalityˢᴿ′ pat0) (compositionalityˢᴿ′ rpat0)

  compositionalityˢᴿ : ∀ (x/t : S₁ ⊢[ m ] s) {σ₁ : S₁ →ˢ S₂} {ξ₂ : S₂ →ᴿ S₃} →
    (x/t [ σ₁ ]ˢ) [ ξ₂ ]ᴿ ≡ x/t [ (σ₁ ⨟ ⟨ ξ₂ ⟩) ]ˢ
  compositionalityˢᴿ x/t {σ₁ = σ} {ξ₂ = ξ} =
    trans (compositionalityˢᴿ′ x/t) (cong (x/t [_]ˢ) (⨟ˢᴿ-def σ ξ))

  lift-wk : ⟨ wkᴿ s ⟩ ⨟ (σ ↑ˢ s) ≡ σ ⨟ ⟨ wkᴿ s ⟩
  lift-wk {s = s} {σ = σ} = trans (⟨wk*⟩-lift idᴿ σ)
    (trans (cong (_⨟ˢᴿ wkᴿ s) comp-idₗ) (⨟ˢᴿ-def σ (wkᴿ s)))

  ⨟ˢᴿwk-lift : ∀ (σ₁ : S₁ →ˢ S₂) (σ₂ : S₂ →ˢ S₃) →
    (σ₁ ⨟ˢᴿ wkᴿ s) ⨟ (σ₂ ↑ˢ s) ≡ (σ₁ ⨟ σ₂) ⨟ˢᴿ wkᴿ s
  ⨟ˢᴿwk-lift []       σ₂ = refl
  ⨟ˢᴿwk-lift {s = s} (t ∙ˢ σ₁) σ₂ = cong2 _∙ˢ_
    (trans (compositionalityᴿˢ t)
      (trans (cong (t [_]ˢ) (trans lift-wk (sym (⨟ˢᴿ-def σ₂ (wkᴿ s)))))
             (sym (compositionalityˢᴿ′ t))))
    (⨟ˢᴿwk-lift σ₁ σ₂)

  lift-dist-compˢˢ : ((σ₁ ↑ˢ s) ⨟ (σ₂ ↑ˢ s)) ≡ ((σ₁ ⨟ σ₂) ↑ˢ s)
  lift-dist-compˢˢ {σ₁ = σ₁} {σ₂ = σ₂} = cong ((`_ zero) ∙ˢ_) (⨟ˢᴿwk-lift σ₁ σ₂)

  -- ══ Vˢ. monad laws, substitution world ═══════════════════════════
  compositionalityˢˢ : ∀ (x/t : S₁ ⊢[ m ] s) {σ₁ : S₁ →ˢ S₂} {σ₂ : S₂ →ˢ S₃} →
    (x/t [ σ₁ ]ˢ) [ σ₂ ]ˢ ≡ x/t [ (σ₁ ⨟ σ₂) ]ˢ
  compositionalityˢˢ zero    {σ₁ = t ∙ˢ σ₁} = refl
  compositionalityˢˢ (suc x) {σ₁ = t ∙ˢ σ₁} = compositionalityˢˢ x
  compositionalityˢˢ (`_ x) = compositionalityˢˢ x
  compositionalityˢˢ Top                             = refl
  compositionalityˢˢ (_⇒_ type0 type1)               = cong2 _⇒_ (compositionalityˢˢ type0) (compositionalityˢˢ type1)
  compositionalityˢˢ (∀[<:_]_ type0 type1)           = cong2 ∀[<:_]_ (compositionalityˢˢ type0) (trans (compositionalityˢˢ type1) (cong (type1 [_]ˢ) lift-dist-compˢˢ))
  compositionalityˢˢ (RcdT rtype0)                   = cong1 RcdT (compositionalityˢˢ rtype0)
  compositionalityˢˢ nilT                            = refl
  compositionalityˢˢ (consT label0 type0 rtype0)     = cong3 consT refl (compositionalityˢˢ type0) (compositionalityˢˢ rtype0)
  compositionalityˢˢ (λx[_]_ type0 expr0)            = cong2 λx[_]_ (compositionalityˢˢ type0) (trans (compositionalityˢˢ expr0) (cong (expr0 [_]ˢ) lift-dist-compˢˢ))
  compositionalityˢˢ (Λα[<:_]_ type0 expr0)          = cong2 Λα[<:_]_ (compositionalityˢˢ type0) (trans (compositionalityˢˢ expr0) (cong (expr0 [_]ˢ) lift-dist-compˢˢ))
  compositionalityˢˢ (_·_ expr0 expr1)               = cong2 _·_ (compositionalityˢˢ expr0) (compositionalityˢˢ expr1)
  compositionalityˢˢ (_•_ expr0 type0)               = cong2 _•_ (compositionalityˢˢ expr0) (compositionalityˢˢ type0)
  compositionalityˢˢ (RcdE rexpr0)                   = cong1 RcdE (compositionalityˢˢ rexpr0)
  compositionalityˢˢ (_#_ expr0 label0)              = cong2 _#_ (compositionalityˢˢ expr0) refl
  compositionalityˢˢ (letP {n = n} pat0 expr0 expr1) = cong-letP (compositionalityˢˢ pat0) (compositionalityˢˢ expr0) (trans (compositionalityˢˢ expr1) (cong (expr1 [_]ˢ) (lift*-dist-compˢˢ expr n)))
  compositionalityˢˢ nilE                            = refl
  compositionalityˢˢ (consE label0 expr0 rexpr0)     = cong3 consE refl (compositionalityˢˢ expr0) (compositionalityˢˢ rexpr0)
  compositionalityˢˢ (pvar type0)                    = cong-pvar (compositionalityˢˢ type0)
  compositionalityˢˢ (prcd rpat0)                    = cong-prcd (compositionalityˢˢ rpat0)
  compositionalityˢˢ nilP                            = refl
  compositionalityˢˢ (consP label0 pat0 rpat0)       = cong-consP (compositionalityˢˢ pat0) (compositionalityˢˢ rpat0)

  assoc : (σ₁ ⨟ σ₂) ⨟ σ₃ ≡ σ₁ ⨟ (σ₂ ⨟ σ₃)
  assoc {σ₁ = []}      = refl
  assoc {σ₁ = t ∙ˢ σ₁} = cong2 _∙ˢ_ (compositionalityˢˢ t) assoc

  comp-idᵣ : σ ⨟ ⟨ idᴿ ⟩ ≡ σ
  comp-idᵣ {σ = []}     = refl
  comp-idᵣ {σ = t ∙ˢ σ} = cong2 _∙ˢ_ (trans (coincidence t idᴿ) (right-idᴿ t)) comp-idᵣ

  ⨟ˢᴿwk-cons : ∀ (σ : S₁ →ˢ S₂) (t : S₃ ⊢ s) (τ : S₂ →ˢ S₃) →
    (σ ⨟ˢᴿ wkᴿ s) ⨟ (t ∙ˢ τ) ≡ σ ⨟ τ
  ⨟ˢᴿwk-cons []       t τ = refl
  ⨟ˢᴿwk-cons (u ∙ˢ σ) t τ =
    cong2 _∙ˢ_ (trans (compositionalityᴿˢ u) (cong (u [_]ˢ) interact)) (⨟ˢᴿwk-cons σ t τ)

  lift-cons : (σ ↑ˢ s) ⨟ (t ∙ˢ τ) ≡ t ∙ˢ (σ ⨟ τ)
  lift-cons {σ = σ} {t = t} {τ = τ} = cong (t ∙ˢ_) (⨟ˢᴿwk-cons σ t τ)

  -- ══ the collapse family: ⟨_⟩ is pushed back into the ᴿ world ═════
  ⟨⟩-comp : ⟨ ξ₁ ⟩ ⨟ ⟨ ξ₂ ⟩ ≡ ⟨ ξ₁ ⨟ᴿ ξ₂ ⟩
  ⟨⟩-comp {ξ₁ = []}      = refl
  ⟨⟩-comp {ξ₁ = x ∙ᴿ ξ₁} {ξ₂ = ξ₂} = cong2 _∙ˢ_ (coincidence-var x ξ₂) ⟨⟩-comp

  ⟨⟩-split-⨟ : ⟨ ξ₁ ⨟ᴿ ξ₂ ⟩ ⨟ σ ≡ ⟨ ξ₁ ⟩ ⨟ (⟨ ξ₂ ⟩ ⨟ σ)
  ⟨⟩-split-⨟ {ξ₁ = []}      = refl
  ⟨⟩-split-⨟ {ξ₁ = x ∙ᴿ ξ₁} = cong2 _∙ˢ_ (compositionalityᴿˢ x) ⟨⟩-split-⨟

  ⟨⟩-lift-cons : ⟨ ξ ↑ᴿ s ⟩ ⨟ (t ∙ˢ σ) ≡ t ∙ˢ (⟨ ξ ⟩ ⨟ σ)
  ⟨⟩-lift-cons {ξ = ξ} {t = t} {σ = σ} = cong (t ∙ˢ_) (⟨wk*⟩-cons ξ t σ)

  lift-id : (⟨ idᴿ {S} ⟩ ↑ˢ s) ≡ ⟨ idᴿ ⟩
  lift-id = ⟨⟩-lift


opaque
  unfolding wk*ᴿ idᴿ wkᴿ _↑ᴿ_ _[_]ᴿ _⨟ᴿ_ ⟨_⟩ _⨟ˢᴿ_ _↑ˢ_ _[_]ˢ _⨟_

  -- ══ IIˢ. traversal rules, substitution world ═════════════════════
  inst-var : (`_ x) [ σ ]ˢ ≡ x [ σ ]ˢ
  inst-Top      : Top {S = S} [ σ ]ˢ                                                                                          ≡ Top
  inst-_⇒_      : (_⇒_ type0 type1) [ σ ]ˢ                                                                                    ≡ _⇒_ (type0 [ σ ]ˢ) (type1 [ σ ]ˢ)
  inst-∀[<:_]_  : (∀[<:_]_ type0 type1) [ σ ]ˢ                                                                                ≡ ∀[<:_]_ (type0 [ σ ]ˢ) (type1 [ σ ↑ˢ type ]ˢ)
  inst-RcdT     : (RcdT rtype0) [ σ ]ˢ                                                                                        ≡ RcdT (rtype0 [ σ ]ˢ)
  inst-nilT     : nilT {S = S} [ σ ]ˢ                                                                                         ≡ nilT
  inst-consT    : (consT label0 type0 rtype0) [ σ ]ˢ                                                                          ≡ consT label0 (type0 [ σ ]ˢ) (rtype0 [ σ ]ˢ)
  inst-λx[_]_   : (λx[_]_ type0 expr0) [ σ ]ˢ                                                                                 ≡ λx[_]_ (type0 [ σ ]ˢ) (expr0 [ σ ↑ˢ expr ]ˢ)
  inst-Λα[<:_]_ : (Λα[<:_]_ type0 expr0) [ σ ]ˢ                                                                               ≡ Λα[<:_]_ (type0 [ σ ]ˢ) (expr0 [ σ ↑ˢ type ]ˢ)
  inst-_·_      : (_·_ expr0 expr1) [ σ ]ˢ                                                                                    ≡ _·_ (expr0 [ σ ]ˢ) (expr1 [ σ ]ˢ)
  inst-_•_      : (_•_ expr0 type0) [ σ ]ˢ                                                                                    ≡ _•_ (expr0 [ σ ]ˢ) (type0 [ σ ]ˢ)
  inst-RcdE     : (RcdE rexpr0) [ σ ]ˢ                                                                                        ≡ RcdE (rexpr0 [ σ ]ˢ)
  inst-_#_      : (_#_ expr0 label0) [ σ ]ˢ                                                                                   ≡ _#_ (expr0 [ σ ]ˢ) label0
  inst-letP     : ∀ {pat0 : S ⊢ pat 0 n} {expr0 : S ⊢ expr} {expr1 : (ext* expr n S) ⊢ expr} → (letP pat0 expr0 expr1) [ σ ]ˢ ≡ letP (pat0 [ σ ]ˢ) (expr0 [ σ ]ˢ) (expr1 [ σ ↑ˢ*[ expr ] n ]ˢ)
  inst-nilE     : nilE {S = S} [ σ ]ˢ                                                                                         ≡ nilE
  inst-consE    : (consE label0 expr0 rexpr0) [ σ ]ˢ                                                                          ≡ consE label0 (expr0 [ σ ]ˢ) (rexpr0 [ σ ]ˢ)
  inst-pvar     : ∀ {type0 : S ⊢ type} → (pvar {n = n} type0) [ σ ]ˢ                                                          ≡ pvar (type0 [ σ ]ˢ)
  inst-prcd     : ∀ {rpat0 : S ⊢ rpat n₁ n₂} → (prcd rpat0) [ σ ]ˢ                                                            ≡ prcd (rpat0 [ σ ]ˢ)
  inst-nilP     : nilP {S = S} {n = n} [ σ ]ˢ                                                                                 ≡ nilP
  inst-consP    : ∀ {pat0 : S ⊢ pat n₁ n₂} {rpat0 : S ⊢ rpat n₂ n₃} → (consP label0 pat0 rpat0) [ σ ]ˢ                        ≡ consP label0 (pat0 [ σ ]ˢ) (rpat0 [ σ ]ˢ)
  inst-var = refl
  inst-Top      = refl
  inst-_⇒_      = refl
  inst-∀[<:_]_  = refl
  inst-RcdT     = refl
  inst-nilT     = refl
  inst-consT    = refl
  inst-λx[_]_   = refl
  inst-Λα[<:_]_ = refl
  inst-_·_      = refl
  inst-_•_      = refl
  inst-RcdE     = refl
  inst-_#_      = refl
  inst-letP     = refl
  inst-nilE     = refl
  inst-consE    = refl
  inst-pvar     = refl
  inst-prcd     = refl
  inst-nilP     = refl
  inst-consP    = refl

  -- ITERATED lifting.  Unlike records, patterns FORCE these to be
  -- REWRITE RULES: without lift*-idᴿ the pair (right-idᴿ, instᴿ-let) is
  -- not joinable, because `e₂ [ idᴿ ↑ᴿ*[ b ] n ]ᴿ` is stuck for abstract n.
  lift*-idᴿ         : ∀ b n → (idᴿ {S} ↑ᴿ*[ b ] n) ≡ idᴿ
  lift*-dist-compᴿᴿ : ∀ b n → ((ξ₁ ↑ᴿ*[ b ] n) ⨟ᴿ (ξ₂ ↑ᴿ*[ b ] n)) ≡ ((ξ₁ ⨟ᴿ ξ₂) ↑ᴿ*[ b ] n)
  lift*-dist-compᴿˢ : ∀ b n {ξ : S₁ →ᴿ S₂} {σ : S₂ →ˢ S₃} →
    (⟨ ξ ↑ᴿ*[ b ] n ⟩ ⨟ (σ ↑ˢ*[ b ] n)) ≡ ((⟨ ξ ⟩ ⨟ σ) ↑ˢ*[ b ] n)
  lift*-dist-compˢᴿ : ∀ b n {σ : S₁ →ˢ S₂} {ξ : S₂ →ᴿ S₃} →
    ((σ ↑ˢ*[ b ] n) ⨟ ⟨ ξ ↑ᴿ*[ b ] n ⟩) ≡ ((σ ⨟ ⟨ ξ ⟩) ↑ˢ*[ b ] n)
  lift*-dist-compˢˢ : ∀ b n → ((σ₁ ↑ˢ*[ b ] n) ⨟ (σ₂ ↑ˢ*[ b ] n)) ≡ ((σ₁ ⨟ σ₂) ↑ˢ*[ b ] n)
  ⟨⟩-lift*          : ∀ b n → (⟨ ξ ⟩ ↑ˢ*[ b ] n) ≡ ⟨ ξ ↑ᴿ*[ b ] n ⟩

  -- THE ITERATED COMPLETION COMPANIONS.  One for each `-var` / `-⨟ᴿ` /
  -- `-⨟` companion of the single-lifting layer; each closes exactly the
  -- pair that its single-lifting counterpart closes, one level up.
  lift*-dist-compᴿᴿ-var : ∀ {S₁ S₂ S₃} (b : Sort) (n : ℕ) {s} {x : (ext* b n S₁) ∋ s}
    {ξ₁ : S₁ →ᴿ S₂} {ξ₂ : S₂ →ᴿ S₃} →
    (x [ (ξ₁ ↑ᴿ*[ b ] n) ]ᴿ) [ (ξ₂ ↑ᴿ*[ b ] n) ]ᴿ ≡ x [ ((ξ₁ ⨟ᴿ ξ₂) ↑ᴿ*[ b ] n) ]ᴿ
  lift*-dist-compᴿᴿ-⨟ᴿ : ∀ {S₁ S₂ S₃ S₄} (b : Sort) (n : ℕ) {ξ₁ : S₁ →ᴿ S₂} {ξ₂ : S₂ →ᴿ S₃}
    {ξ′ : (ext* b n S₃) →ᴿ S₄} →
    (ξ₁ ↑ᴿ*[ b ] n) ⨟ᴿ ((ξ₂ ↑ᴿ*[ b ] n) ⨟ᴿ ξ′) ≡ ((ξ₁ ⨟ᴿ ξ₂) ↑ᴿ*[ b ] n) ⨟ᴿ ξ′
  lift*-dist-compˢˢ-⨟ : ∀ {S₁ S₂ S₃} (b : Sort) (n : ℕ) {S₄} {σ₁ : S₁ →ˢ S₂} {σ₂ : S₂ →ˢ S₃}
    {τ : (ext* b n S₃) →ˢ S₄} →
    (σ₁ ↑ˢ*[ b ] n) ⨟ ((σ₂ ↑ˢ*[ b ] n) ⨟ τ) ≡ ((σ₁ ⨟ σ₂) ↑ˢ*[ b ] n) ⨟ τ
  lift*-dist-compᴿˢ-⨟ : ∀ {S₁ S₂ S₃} (b : Sort) (n : ℕ) {S₄} {ξ : S₁ →ᴿ S₂} {σ : S₂ →ˢ S₃}
    {τ : (ext* b n S₃) →ˢ S₄} →
    ⟨ ξ ↑ᴿ*[ b ] n ⟩ ⨟ ((σ ↑ˢ*[ b ] n) ⨟ τ) ≡ ((⟨ ξ ⟩ ⨟ σ) ↑ˢ*[ b ] n) ⨟ τ
  lift*-dist-compˢᴿ-⨟ : ∀ {S₁ S₂ S₃} (b : Sort) (n : ℕ) {S₄} {σ : S₁ →ˢ S₂} {ξ : S₂ →ᴿ S₃}
    {τ : (ext* b n S₃) →ˢ S₄} →
    (σ ↑ˢ*[ b ] n) ⨟ (⟨ ξ ↑ᴿ*[ b ] n ⟩ ⨟ τ) ≡ ((σ ⨟ ⟨ ξ ⟩) ↑ˢ*[ b ] n) ⨟ τ
  lift*-dist-compᴿˢ-var : ∀ {S₁ S₂ S₃} (b : Sort) (n : ℕ) {s} {x : (ext* b n S₁) ∋ s}
    {ξ : S₁ →ᴿ S₂} {σ : S₂ →ˢ S₃} →
    (x [ (ξ ↑ᴿ*[ b ] n) ]ᴿ) [ (σ ↑ˢ*[ b ] n) ]ˢ ≡ x [ ((⟨ ξ ⟩ ⨟ σ) ↑ˢ*[ b ] n) ]ˢ
  ⟨⟩-comp-⨟-lift*-dist-compᴿᴿ : ∀ {S₁ S₂ S₃} (b : Sort) (n : ℕ) {S₄} {ξ₁ : S₁ →ᴿ S₂} {ξ₂ : S₂ →ᴿ S₃}
    {τ : (ext* b n S₃) →ˢ S₄} →
    ⟨ ξ₁ ↑ᴿ*[ b ] n ⟩ ⨟ (⟨ ξ₂ ↑ᴿ*[ b ] n ⟩ ⨟ τ) ≡ ⟨ (ξ₁ ⨟ᴿ ξ₂) ↑ᴿ*[ b ] n ⟩ ⨟ τ
  lift*-dist-compᴿˢ-⨟-var : ∀ {S₁ S₂ S₃} (b : Sort) (n : ℕ) {S₄} {s} {x : (ext* b n S₁) ∋ s}
    {ξ : S₁ →ᴿ S₂} {σ : S₂ →ˢ S₃} {τ : (ext* b n S₃) →ˢ S₄} →
    (x [ (ξ ↑ᴿ*[ b ] n) ]ᴿ) [ ((σ ↑ˢ*[ b ] n) ⨟ τ) ]ˢ ≡ x [ (((⟨ ξ ⟩ ⨟ σ) ↑ˢ*[ b ] n) ⨟ τ) ]ˢ
  ⟨⟩-split*-tail : ∀ {S₁ S₂ S₃} (b : Sort) (n : ℕ) {S₄} {σ : S₁ →ˢ S₂} {ξ : S₂ →ᴿ S₃}
    {ξ′ : (ext* b n S₃) →ᴿ S₄} →
    (σ ↑ˢ*[ b ] n) ⨟ ⟨ (ξ ↑ᴿ*[ b ] n) ⨟ᴿ ξ′ ⟩ ≡ ((σ ⨟ ⟨ ξ ⟩) ↑ˢ*[ b ] n) ⨟ ⟨ ξ′ ⟩

  lift*-idᴿ b zero    = refl
  lift*-idᴿ b (suc n) = trans (cong (_↑ᴿ b) (lift*-idᴿ b n)) lift-idᴿ
  lift*-dist-compᴿᴿ b zero = refl
  lift*-dist-compᴿᴿ {ξ₁ = ξ₁} {ξ₂ = ξ₂} b (suc n) =
    trans (lift-dist-compᴿᴿ {ξ₁ = ξ₁ ↑ᴿ*[ b ] n} {s = b} {ξ₂ = ξ₂ ↑ᴿ*[ b ] n})
          (cong (_↑ᴿ b) (lift*-dist-compᴿᴿ b n))
  lift*-dist-compᴿˢ b zero = refl
  lift*-dist-compᴿˢ b (suc n) {ξ = ξ} {σ = σ} =
    trans (lift-dist-compᴿˢ {ξ = ξ ↑ᴿ*[ b ] n} {s = b} {σ = σ ↑ˢ*[ b ] n})
          (cong (_↑ˢ b) (lift*-dist-compᴿˢ b n))
  -- lift-dist-compˢᴿ is subsumed here, so the step is refl
  lift*-dist-compˢᴿ b zero = refl
  lift*-dist-compˢᴿ b (suc n) = cong (_↑ˢ b) (lift*-dist-compˢᴿ b n)
  lift*-dist-compˢˢ b zero = refl
  lift*-dist-compˢˢ {σ₁ = σ₁} {σ₂ = σ₂} b (suc n) =
    trans (lift-dist-compˢˢ {σ₁ = σ₁ ↑ˢ*[ b ] n} {s = b} {σ₂ = σ₂ ↑ˢ*[ b ] n})
          (cong (_↑ˢ b) (lift*-dist-compˢˢ b n))
  ⟨⟩-lift* b zero    = refl
  ⟨⟩-lift* {ξ = ξ} b (suc n) =
    trans (cong (_↑ˢ b) (⟨⟩-lift* b n)) (⟨⟩-lift {ξ = ξ ↑ᴿ*[ b ] n} {s = b})

  -- the companions.  Each `suc` case loses its single-lifting step.
  lift*-dist-compᴿᴿ-var b zero = refl
  lift*-dist-compᴿᴿ-var b (suc n) {x = x} =
    cong (λ z → x [ (z ↑ᴿ b) ]ᴿ) (lift*-dist-compᴿᴿ b n)
  lift*-dist-compᴿᴿ-⨟ᴿ b zero {ξ₁ = ξ₁} {ξ₂ = ξ₂} {ξ′ = ξ′} =
    sym (assocᴿ {ξ₁ = ξ₁} {ξ₂ = ξ₂} {ξ₃ = ξ′})
  lift*-dist-compᴿᴿ-⨟ᴿ b (suc n) {ξ′ = ξ′} =
    cong (λ z → (z ↑ᴿ b) ⨟ᴿ ξ′) (lift*-dist-compᴿᴿ b n)
  lift*-dist-compˢˢ-⨟ b zero {σ₁ = σ₁} {σ₂ = σ₂} {τ = τ} =
    sym (assoc {σ₁ = σ₁} {σ₂ = σ₂} {σ₃ = τ})
  lift*-dist-compˢˢ-⨟ b (suc n) {τ = τ} =
    cong (λ z → (z ↑ˢ b) ⨟ τ) (lift*-dist-compˢˢ b n)
  lift*-dist-compᴿˢ-⨟ b zero {ξ = ξ} {σ = σ} {τ = τ} =
    sym (assoc {σ₁ = ⟨ ξ ⟩} {σ₂ = σ} {σ₃ = τ})
  lift*-dist-compᴿˢ-⨟ b (suc n) {τ = τ} =
    cong (λ z → (z ↑ˢ b) ⨟ τ) (lift*-dist-compᴿˢ b n)
  lift*-dist-compˢᴿ-⨟ b zero {σ = σ} {ξ = ξ} {τ = τ} =
    sym (assoc {σ₁ = σ} {σ₂ = ⟨ ξ ⟩} {σ₃ = τ})
  lift*-dist-compˢᴿ-⨟ b (suc n) {τ = τ} =
    cong (λ z → (z ↑ˢ b) ⨟ τ) (lift*-dist-compˢᴿ b n)
  lift*-dist-compᴿˢ-var b zero = refl
  lift*-dist-compᴿˢ-var b (suc n) {x = x} =
    cong (λ z → x [ (z ↑ˢ b) ]ˢ) (lift*-dist-compᴿˢ b n)
  ⟨⟩-comp-⨟-lift*-dist-compᴿᴿ b zero {ξ₁ = ξ₁} {ξ₂ = ξ₂} {τ = τ} =
    sym (⟨⟩-split-⨟ {ξ₁ = ξ₁} {ξ₂ = ξ₂} {σ = τ})
  ⟨⟩-comp-⨟-lift*-dist-compᴿᴿ b (suc n) {τ = τ} =
    cong (λ z → ⟨ z ↑ᴿ b ⟩ ⨟ τ) (lift*-dist-compᴿᴿ b n)
  lift*-dist-compᴿˢ-⨟-var b zero {x = x} {ξ = ξ} {σ = σ} {τ = τ} =
    cong (x [_]ˢ) (sym (assoc {σ₁ = ⟨ ξ ⟩} {σ₂ = σ} {σ₃ = τ}))
  lift*-dist-compᴿˢ-⨟-var b (suc n) {x = x} {τ = τ} =
    cong (λ z → x [ ((z ↑ˢ b) ⨟ τ) ]ˢ) (lift*-dist-compᴿˢ b n)
  ⟨⟩-split*-tail b zero {σ = σ} {ξ = ξ} {ξ′ = ξ′} =
    sym (trans (assoc {σ₁ = σ} {σ₂ = ⟨ ξ ⟩} {σ₃ = ⟨ ξ′ ⟩})
               (cong (σ ⨟_) (⟨⟩-comp {ξ₁ = ξ} {ξ₂ = ξ′})))
  ⟨⟩-split*-tail b (suc n) {ξ′ = ξ′} =
    cong (λ z → (z ↑ˢ b) ⨟ ⟨ ξ′ ⟩) (lift*-dist-compˢᴿ b n)

-- ═══ THE COMPLETED TWO-WORLD SYSTEM ════════════════════════════════
--
-- The vector model needs NO completion families.  The `-⨟` continuation
-- companions, the mode-V `-var` companions and the coercion family that
-- the function model registers are all subsumed here, because a vector
-- composition reduces structurally where a function composition is
-- stuck.  closure-vec.agda states every one of those absences and
-- checks it by `refl`.

-- 88 rules -- 33 signature-independent, 15 for the
-- iterated (variable-arity) lifting, 40 traversal rules (one instᴿ-*
-- and one inst-* per constructor, plus the variable case).

{-# REWRITE
  def-wkᴿ def-∙ᴿ-zero def-∙ᴿ-suc def-↑ᴿ-zero def-↑ᴿ-suc
  instᴿ-var instᴿ-Top instᴿ-_⇒_ instᴿ-∀[<:_]_ instᴿ-RcdT instᴿ-nilT
  instᴿ-consT instᴿ-λx[_]_ instᴿ-Λα[<:_]_ instᴿ-_·_ instᴿ-_•_ instᴿ-RcdE
  instᴿ-_#_ instᴿ-letP instᴿ-nilE instᴿ-consE instᴿ-pvar instᴿ-prcd
  instᴿ-nilP instᴿ-consP
  assocᴿ comp-idₗᴿ comp-idᵣᴿ interactᴿ
  lift-idᴿ lift-dist-compᴿᴿ lift-wkᴿ
  right-idᴿ compositionalityᴿᴿ-var compositionalityᴿᴿ
  coincidence-var def-∙ˢ-zero def-∙ˢ-suc def-↑ˢ-zero def-↑ˢ-suc
  inst-var inst-Top inst-_⇒_ inst-∀[<:_]_ inst-RcdT inst-nilT inst-consT
  inst-λx[_]_ inst-Λα[<:_]_ inst-_·_ inst-_•_ inst-RcdE inst-_#_ inst-letP
  inst-nilE inst-consE inst-pvar inst-prcd inst-nilP inst-consP
  assoc dist interact comp-idₗ comp-idᵣ
  lift-wk lift-cons lift-dist-compˢˢ
  compositionalityˢˢ compositionalityᴿˢ compositionalityˢᴿ lift-dist-compᴿˢ
  coincidence ⟨⟩-comp ⟨⟩-split-⨟ ⟨⟩-lift ⟨⟩-lift-cons
  lift*-idᴿ lift*-dist-compᴿᴿ lift*-dist-compᴿˢ lift*-dist-compˢᴿ
  lift*-dist-compˢˢ ⟨⟩-lift* lift*-dist-compᴿᴿ-var lift*-dist-compᴿᴿ-⨟ᴿ
  lift*-dist-compˢˢ-⨟ lift*-dist-compᴿˢ-⨟ lift*-dist-compˢᴿ-⨟
  lift*-dist-compᴿˢ-var ⟨⟩-comp-⨟-lift*-dist-compᴿᴿ lift*-dist-compᴿˢ-⨟-var
  ⟨⟩-split*-tail
#-}

-- ─── the derived operations ─────────────────────────────────────────
-- Neither is primitive and neither has rules of its own: weakening is a
-- renaming, single substitution is a cons onto the identity.  The
-- rewrite system computes through both without knowing they exist.

weaken : S ⊢ s → (s′ ∷ S) ⊢ s
weaken t = t [ wkᴿ _ ]ᴿ

_[_]₀ : (s′ ∷ S) ⊢ s → S ⊢ s′ → S ⊢ s
t [ t′ ]₀ = t [ (t′ ∙ˢ idˢ) ]ˢ
