{-# OPTIONS --rewriting --local-confluence-check #-}

-- Generated by gen/agdasubst.py --model=vectors.  DO NOT EDIT.
--
-- The multi-sorted, mode-merged σ-calculus with FIRST-CLASS RENAMINGS,
-- installed as a locally confluent Agda REWRITE system.  Maps are
-- inductive VECTORS, so equality of maps is equality of data and the
-- module assumes NOTHING: no function extensionality, no postulates.

module Languages.STLC where

open import Relation.Binary.PropositionalEquality
  using (_≡_; refl; sym; cong; trans; module ≡-Reasoning)
open ≡-Reasoning
open import Agda.Builtin.Equality.Rewrite
open import Data.List using (List; []; _∷_)
open import Data.Nat using (ℕ; zero; suc)

cong1 : ∀ {A1 A2 : Set} (f : A1 → A2) {a1 a2} →
  a1 ≡ a2 → f a1 ≡ f a2
cong1 f refl = refl

cong2 : ∀ {A1 A2 A3 : Set} (f : A1 → A2 → A3) {a1 a2 a3 a4} →
  a1 ≡ a2 → a3 ≡ a4 → f a1 a3 ≡ f a2 a4
cong2 f refl refl = refl

infixl 7 _·_

-- ─── syntax ─────────────────────────────────────────────────────────

data Sort : Set where
  expr : Sort
Scope = List Sort

variable
  s s₁ s₂ s′ : Sort
  S S₁ S₂ S₃ : Scope


-- ─── iterated lifting: a binder of VARIABLE ARITY ───────────────────
--
-- `ext* b n S` extends a scope by n copies of ONE sort.  DERIVED and
-- TRANSPARENT: it computes on n, so the rewrite system needs rules only
-- for the case where n is abstract.
--
-- Generalized from gen/Reference/FsubPatterns.agda, which fixes b := expr.

ext* : Sort → ℕ → Scope → Scope
ext* b zero    S = S
ext* b (suc n) S = b ∷ ext* b n S

data Mode : Set where V T : Mode

variable
  m : Mode

data _⊢[_]_ : Scope → Mode → Sort → Set

_⊢_ = _⊢[ T ]_
_∋_ = _⊢[ V ]_

data _⊢[_]_ where
  zero : (s ∷ S) ∋ s
  suc  : S ∋ s → (s′ ∷ S) ∋ s
  `_   : S ∋ s → S ⊢ s
  λx_  : (expr ∷ S) ⊢ expr → S ⊢ expr
  _·_  : S ⊢ expr → S ⊢ expr → S ⊢ expr

variable
  t t₁ t₂ t′ : S ⊢ s
  x x′       : S ∋ s
  x/t x/t′   : S ⊢[ m ] s

variable
  expr0 expr1 : S ⊢ expr

-- ─── maps as vectors ────────────────────────────────────────────────

infixr 5 _∙ᴿ_ _∙ˢ_

data _→ᴿ_ : Scope → Scope → Set where
  []   : [] →ᴿ S
  _∙ᴿ_ : S₂ ∋ s → S₁ →ᴿ S₂ → (s ∷ S₁) →ᴿ S₂

data _→ˢ_ : Scope → Scope → Set where
  []   : [] →ˢ S
  _∙ˢ_ : S₂ ⊢ s → S₁ →ˢ S₂ → (s ∷ S₁) →ˢ S₂

variable
  ξ ξ′ ξ₁ ξ₂ ξ₃ : S₁ →ᴿ S₂
  σ σ′ σ₁ σ₂ σ₃ τ ρ : S₁ →ˢ S₂

-- ─── the renaming world ─────────────────────────────────────────────

opaque
  -- post-composition with weakening: the primitive recursion that lets
  -- lifting and the identity be defined without a composition cycle
  wk*ᴿ : ∀ s′ → S₁ →ᴿ S₂ → S₁ →ᴿ (s′ ∷ S₂)
  wk*ᴿ s′ []       = []
  wk*ᴿ s′ (x ∙ᴿ ξ) = suc x ∙ᴿ wk*ᴿ s′ ξ

  idᴿ : S →ᴿ S
  idᴿ {[]}    = []
  idᴿ {s ∷ S} = zero ∙ᴿ wk*ᴿ s idᴿ

  wkᴿ : ∀ s′ → S →ᴿ (s′ ∷ S)
  wkᴿ s′ = wk*ᴿ s′ idᴿ

  _↑ᴿ_ : S₁ →ᴿ S₂ → ∀ s → (s ∷ S₁) →ᴿ (s ∷ S₂)
  ξ ↑ᴿ s = zero ∙ᴿ wk*ᴿ s ξ

-- The n-fold renaming lift.  Derived and transparent, and defined
-- BETWEEN the _↑ᴿ_ block and the _[_]ᴿ block, because the traversal of a
-- variable-arity binder uses it.

_↑ᴿ*[_]_ : S₁ →ᴿ S₂ → ∀ b n → (ext* b n S₁) →ᴿ (ext* b n S₂)
ξ ↑ᴿ*[ b ] zero    = ξ
ξ ↑ᴿ*[ b ] (suc n) = (ξ ↑ᴿ*[ b ] n) ↑ᴿ b

opaque
  unfolding wk*ᴿ idᴿ wkᴿ _↑ᴿ_

  _[_]ᴿ : S₁ ⊢[ m ] s → S₁ →ᴿ S₂ → S₂ ⊢[ m ] s
  zero    [ x ∙ᴿ ξ ]ᴿ = x
  (suc y) [ x ∙ᴿ ξ ]ᴿ = y [ ξ ]ᴿ
  (`_ x) [ ξ ]ᴿ = `_ (x [ ξ ]ᴿ)
  (λx_ expr0)       [ ξ ]ᴿ = λx_ (expr0 [ ξ ↑ᴿ expr ]ᴿ)
  (_·_ expr0 expr1) [ ξ ]ᴿ = _·_ (expr0 [ ξ ]ᴿ) (expr1 [ ξ ]ᴿ)

  _⨟ᴿ_ : S₁ →ᴿ S₂ → S₂ →ᴿ S₃ → S₁ →ᴿ S₃
  []       ⨟ᴿ ξ₂ = []
  (x ∙ᴿ ξ) ⨟ᴿ ξ₂ = (x [ ξ₂ ]ᴿ) ∙ᴿ (ξ ⨟ᴿ ξ₂)

-- ─── the substitution world ─────────────────────────────────────────

opaque
  unfolding wk*ᴿ idᴿ wkᴿ _↑ᴿ_ _[_]ᴿ _⨟ᴿ_

  ⟨_⟩ : S₁ →ᴿ S₂ → S₁ →ˢ S₂
  ⟨ [] ⟩     = []
  ⟨ x ∙ᴿ ξ ⟩ = (`_ x) ∙ˢ ⟨ ξ ⟩

  -- post-composition of a substitution with a renaming: keeps ↑ˢ
  -- structural, and is erased by ⨟ˢᴿ-def before any rule sees it
  _⨟ˢᴿ_ : S₁ →ˢ S₂ → S₂ →ᴿ S₃ → S₁ →ˢ S₃
  []       ⨟ˢᴿ ξ = []
  (t ∙ˢ σ) ⨟ˢᴿ ξ = (t [ ξ ]ᴿ) ∙ˢ (σ ⨟ˢᴿ ξ)

  _↑ˢ_ : S₁ →ˢ S₂ → ∀ s → (s ∷ S₁) →ˢ (s ∷ S₂)
  σ ↑ˢ s = (`_ zero) ∙ˢ (σ ⨟ˢᴿ wkᴿ s)

-- The n-fold substitution lift, likewise between _↑ˢ_ and _[_]ˢ.

_↑ˢ*[_]_ : S₁ →ˢ S₂ → ∀ b n → (ext* b n S₁) →ˢ (ext* b n S₂)
σ ↑ˢ*[ b ] zero    = σ
σ ↑ˢ*[ b ] (suc n) = (σ ↑ˢ*[ b ] n) ↑ˢ b

opaque
  unfolding wk*ᴿ idᴿ wkᴿ _↑ᴿ_ _[_]ᴿ ⟨_⟩ _⨟ˢᴿ_ _↑ˢ_

  _[_]ˢ : S₁ ⊢[ m ] s → S₁ →ˢ S₂ → S₂ ⊢ s
  zero    [ t ∙ˢ σ ]ˢ = t
  (suc y) [ t ∙ˢ σ ]ˢ = y [ σ ]ˢ
  (`_ x) [ σ ]ˢ = x [ σ ]ˢ
  (λx_ expr0)       [ σ ]ˢ = λx_ (expr0 [ σ ↑ˢ expr ]ˢ)
  (_·_ expr0 expr1) [ σ ]ˢ = _·_ (expr0 [ σ ]ˢ) (expr1 [ σ ]ˢ)

  _⨟_ : S₁ →ˢ S₂ → S₂ →ˢ S₃ → S₁ →ˢ S₃
  []       ⨟ σ₂ = []
  (t ∙ˢ σ) ⨟ σ₂ = (t [ σ₂ ]ˢ) ∙ˢ (σ ⨟ σ₂)

idˢ : S →ˢ S
idˢ = ⟨ idᴿ ⟩

wkˢ : ∀ s′ → S →ˢ (s′ ∷ S)
wkˢ s′ = ⟨ wkᴿ s′ ⟩

-- ─── the two-world rewrite system ───────────────────────────────────

opaque
  unfolding wk*ᴿ idᴿ wkᴿ _↑ᴿ_ _[_]ᴿ _⨟ᴿ_

  -- ══ Iᴿ. applied rules, renaming world ═════════════════════════════
  def-∙ᴿ-zero : zero [ (x ∙ᴿ ξ) ]ᴿ ≡ x
  def-∙ᴿ-zero = refl

  def-∙ᴿ-suc : (suc {s′ = s′} x′) [ (x ∙ᴿ ξ) ]ᴿ ≡ x′ [ ξ ]ᴿ
  def-∙ᴿ-suc = refl

  lookup-wk*ᴿ : ∀ (x : S₁ ∋ s) (ξ : S₁ →ᴿ S₂) → x [ wk*ᴿ s′ ξ ]ᴿ ≡ suc (x [ ξ ]ᴿ)
  lookup-wk*ᴿ zero    (y ∙ᴿ ξ) = refl
  lookup-wk*ᴿ (suc x) (y ∙ᴿ ξ) = lookup-wk*ᴿ x ξ

  lookup-idᴿ : ∀ (x : S ∋ s) → x [ idᴿ ]ᴿ ≡ x
  lookup-idᴿ zero    = refl
  lookup-idᴿ (suc x) = trans (lookup-wk*ᴿ x idᴿ) (cong suc (lookup-idᴿ x))

  def-wkᴿ : x [ wkᴿ s′ ]ᴿ ≡ suc x
  def-wkᴿ {x = x} = trans (lookup-wk*ᴿ x idᴿ) (cong suc (lookup-idᴿ x))

  def-↑ᴿ-zero : zero [ (ξ ↑ᴿ s) ]ᴿ ≡ zero
  def-↑ᴿ-zero = refl

  def-↑ᴿ-suc : (suc x) [ (ξ ↑ᴿ s) ]ᴿ ≡ suc (x [ ξ ]ᴿ)
  def-↑ᴿ-suc {x = x} {ξ = ξ} = lookup-wk*ᴿ x ξ

  lift-idᴿ : (idᴿ {S} ↑ᴿ s) ≡ idᴿ
  lift-idᴿ = refl

  -- ══ IIᴿ. traversal rules, renaming world ═════════════════════════
  instᴿ-var : (`_ x) [ ξ ]ᴿ ≡ `_ (x [ ξ ]ᴿ)
  instᴿ-λx_ : (λx_ expr0) [ ξ ]ᴿ       ≡ λx_ (expr0 [ ξ ↑ᴿ expr ]ᴿ)
  instᴿ-_·_ : (_·_ expr0 expr1) [ ξ ]ᴿ ≡ _·_ (expr0 [ ξ ]ᴿ) (expr1 [ ξ ]ᴿ)
  instᴿ-var = refl
  instᴿ-λx_ = refl
  instᴿ-_·_ = refl

  -- ══ IIIᴿ. map algebra, renaming world ════════════════════════════
  distᴿ : (x ∙ᴿ ξ₁) ⨟ᴿ ξ₂ ≡ (x [ ξ₂ ]ᴿ) ∙ᴿ (ξ₁ ⨟ᴿ ξ₂)
  distᴿ = refl

  compositionalityᴿᴿ-var : ∀ (x : S₁ ∋ s) {ξ₁ : S₁ →ᴿ S₂} {ξ₂ : S₂ →ᴿ S₃} →
    x [ (ξ₁ ⨟ᴿ ξ₂) ]ᴿ ≡ (x [ ξ₁ ]ᴿ) [ ξ₂ ]ᴿ
  compositionalityᴿᴿ-var zero    {ξ₁ = y ∙ᴿ ξ₁} = refl
  compositionalityᴿᴿ-var (suc x) {ξ₁ = y ∙ᴿ ξ₁} = compositionalityᴿᴿ-var x

  wk*ᴿ-⨟ᴿ : ∀ (ξ₁ : S₁ →ᴿ S₂) (x : S₃ ∋ s′) (ξ₂ : S₂ →ᴿ S₃) →
    wk*ᴿ s′ ξ₁ ⨟ᴿ (x ∙ᴿ ξ₂) ≡ ξ₁ ⨟ᴿ ξ₂
  wk*ᴿ-⨟ᴿ []        x ξ₂ = refl
  wk*ᴿ-⨟ᴿ (y ∙ᴿ ξ₁) x ξ₂ = cong (_ ∙ᴿ_) (wk*ᴿ-⨟ᴿ ξ₁ x ξ₂)

  comp-idₗᴿ : idᴿ ⨟ᴿ ξ ≡ ξ
  comp-idₗᴿ {ξ = []}     = refl
  comp-idₗᴿ {ξ = x ∙ᴿ ξ} = cong (x ∙ᴿ_) (trans (wk*ᴿ-⨟ᴿ idᴿ x ξ) comp-idₗᴿ)

  comp-idᵣᴿ : ξ ⨟ᴿ idᴿ ≡ ξ
  comp-idᵣᴿ {ξ = []}     = refl
  comp-idᵣᴿ {ξ = x ∙ᴿ ξ} = cong2 _∙ᴿ_ (lookup-idᴿ x) comp-idᵣᴿ

  interactᴿ : wkᴿ s ⨟ᴿ (x ∙ᴿ ξ) ≡ ξ
  interactᴿ {x = x} {ξ = ξ} = trans (wk*ᴿ-⨟ᴿ idᴿ x ξ) comp-idₗᴿ

  lift-consᴿ : (ξ ↑ᴿ s) ⨟ᴿ (x ∙ᴿ ξ′) ≡ x ∙ᴿ (ξ ⨟ᴿ ξ′)
  lift-consᴿ {ξ = ξ} {x = x} {ξ′ = ξ′} = cong (x ∙ᴿ_) (wk*ᴿ-⨟ᴿ ξ x ξ′)

  assocᴿ : (ξ₁ ⨟ᴿ ξ₂) ⨟ᴿ ξ₃ ≡ ξ₁ ⨟ᴿ (ξ₂ ⨟ᴿ ξ₃)
  assocᴿ {ξ₁ = []}      = refl
  assocᴿ {ξ₁ = x ∙ᴿ ξ₁} = cong2 _∙ᴿ_ (sym (compositionalityᴿᴿ-var x)) assocᴿ

  wk*ᴿ-comp : ∀ (ξ₁ : S₁ →ᴿ S₂) (ξ₂ : S₂ →ᴿ S₃) →
    wk*ᴿ s ξ₁ ⨟ᴿ (ξ₂ ↑ᴿ s) ≡ wk*ᴿ s (ξ₁ ⨟ᴿ ξ₂)
  wk*ᴿ-comp []        ξ₂ = refl
  wk*ᴿ-comp (x ∙ᴿ ξ₁) ξ₂ = cong2 _∙ᴿ_ (lookup-wk*ᴿ x ξ₂) (wk*ᴿ-comp ξ₁ ξ₂)

  ⨟ᴿ-wk*ᴿ : ∀ (ξ₁ : S₁ →ᴿ S₂) (ξ₂ : S₂ →ᴿ S₃) →
    ξ₁ ⨟ᴿ wk*ᴿ s ξ₂ ≡ wk*ᴿ s (ξ₁ ⨟ᴿ ξ₂)
  ⨟ᴿ-wk*ᴿ []        ξ₂ = refl
  ⨟ᴿ-wk*ᴿ (x ∙ᴿ ξ₁) ξ₂ = cong2 _∙ᴿ_ (lookup-wk*ᴿ x ξ₂) (⨟ᴿ-wk*ᴿ ξ₁ ξ₂)

  lift-dist-compᴿᴿ : ((ξ₁ ↑ᴿ s) ⨟ᴿ (ξ₂ ↑ᴿ s)) ≡ ((ξ₁ ⨟ᴿ ξ₂) ↑ᴿ s)
  lift-dist-compᴿᴿ {ξ₁ = ξ₁} {ξ₂ = ξ₂} = cong (zero ∙ᴿ_) (wk*ᴿ-comp ξ₁ ξ₂)

  lift-wkᴿ : wkᴿ s ⨟ᴿ (ξ ↑ᴿ s) ≡ ξ ⨟ᴿ wkᴿ s
  lift-wkᴿ {ξ = ξ} = trans (wk*ᴿ-comp idᴿ ξ)
    (trans (cong (wk*ᴿ _) comp-idₗᴿ)
    (sym (trans (⨟ᴿ-wk*ᴿ ξ idᴿ) (cong (wk*ᴿ _) comp-idᵣᴿ))))

  -- ══ Vᴿ. monad laws, renaming world ═══════════════════════════════
  right-idᴿ : ∀ (x/t : S ⊢[ m ] s) → x/t [ idᴿ ]ᴿ ≡ x/t
  right-idᴿ zero    = refl
  right-idᴿ (suc x) = lookup-idᴿ (suc x)
  right-idᴿ (`_ x)   = cong `_ (lookup-idᴿ x)
  right-idᴿ (λx_ expr0)       = cong1 λx_ (trans (cong (expr0 [_]ᴿ) lift-idᴿ) (right-idᴿ expr0))
  right-idᴿ (_·_ expr0 expr1) = cong2 _·_ (right-idᴿ expr0) (right-idᴿ expr1)

  compositionalityᴿᴿ : ∀ (x/t : S₁ ⊢[ m ] s) {ξ₁ : S₁ →ᴿ S₂} {ξ₂ : S₂ →ᴿ S₃} →
    (x/t [ ξ₁ ]ᴿ) [ ξ₂ ]ᴿ ≡ x/t [ (ξ₁ ⨟ᴿ ξ₂) ]ᴿ
  compositionalityᴿᴿ zero    {ξ₁ = y ∙ᴿ ξ₁} = refl
  compositionalityᴿᴿ (suc x) {ξ₁ = y ∙ᴿ ξ₁} = compositionalityᴿᴿ x
  compositionalityᴿᴿ (`_ x) = cong `_ (compositionalityᴿᴿ x)
  compositionalityᴿᴿ (λx_ expr0)       = cong1 λx_ (trans (compositionalityᴿᴿ expr0) (cong (expr0 [_]ᴿ) lift-dist-compᴿᴿ))
  compositionalityᴿᴿ (_·_ expr0 expr1) = cong2 _·_ (compositionalityᴿᴿ expr0) (compositionalityᴿᴿ expr1)

-- ─── the substitution world ─────────────────────────────────────────

opaque
  unfolding wk*ᴿ idᴿ wkᴿ _↑ᴿ_ _[_]ᴿ _⨟ᴿ_ ⟨_⟩ _⨟ˢᴿ_ _↑ˢ_ _[_]ˢ _⨟_

  ⟨⟩-⨟ˢᴿ-wk : ∀ (ξ : S₁ →ᴿ S₂) → ⟨ ξ ⟩ ⨟ˢᴿ wkᴿ s ≡ ⟨ wk*ᴿ s ξ ⟩
  ⟨⟩-⨟ˢᴿ-wk []       = refl
  ⟨⟩-⨟ˢᴿ-wk (x ∙ᴿ ξ) = cong2 _∙ˢ_ (cong `_ def-wkᴿ) (⟨⟩-⨟ˢᴿ-wk ξ)

  ⟨⟩-lift : (⟨ ξ ⟩ ↑ˢ s) ≡ ⟨ ξ ↑ᴿ s ⟩
  ⟨⟩-lift {ξ = ξ} = cong ((`_ zero) ∙ˢ_) (⟨⟩-⨟ˢᴿ-wk ξ)

  coincidence-var : ∀ (x : S₁ ∋ s) (ξ : S₁ →ᴿ S₂) → x [ ⟨ ξ ⟩ ]ˢ ≡ `_ (x [ ξ ]ᴿ)
  coincidence-var zero    (y ∙ᴿ ξ) = refl
  coincidence-var (suc x) (y ∙ᴿ ξ) = coincidence-var x ξ

  coincidence : ∀ (t : S₁ ⊢ s) (ξ : S₁ →ᴿ S₂) → t [ ⟨ ξ ⟩ ]ˢ ≡ t [ ξ ]ᴿ
  coincidence (`_ x) ξ = coincidence-var x ξ
  coincidence (λx_ expr0) ξ       = cong1 λx_ (trans (cong (expr0 [_]ˢ) (⟨⟩-lift {ξ = ξ})) (coincidence expr0 (ξ ↑ᴿ expr)))
  coincidence (_·_ expr0 expr1) ξ = cong2 _·_ (coincidence expr0 ξ) (coincidence expr1 ξ)

  ⨟ˢᴿ-def : ∀ (σ : S₁ →ˢ S₂) (ξ : S₂ →ᴿ S₃) → σ ⨟ˢᴿ ξ ≡ σ ⨟ ⟨ ξ ⟩
  ⨟ˢᴿ-def []       ξ = refl
  ⨟ˢᴿ-def (t ∙ˢ σ) ξ = cong2 _∙ˢ_ (sym (coincidence t ξ)) (⨟ˢᴿ-def σ ξ)

  -- ══ Iˢ. applied rules, substitution world ════════════════════════
  def-∙ˢ-zero : zero [ (t ∙ˢ σ) ]ˢ ≡ t
  def-∙ˢ-zero = refl

  def-∙ˢ-suc : (suc {s′ = s′} x) [ (t ∙ˢ σ) ]ˢ ≡ x [ σ ]ˢ
  def-∙ˢ-suc = refl

  def-↑ˢ-zero : zero [ (σ ↑ˢ s) ]ˢ ≡ `_ zero
  def-↑ˢ-zero = refl

  def-↑ˢ-suc : (suc x) [ (σ ↑ˢ s) ]ˢ ≡ x [ (σ ⨟ ⟨ wkᴿ s ⟩) ]ˢ
  def-↑ˢ-suc {x = x} {σ = σ} {s = s} = cong (x [_]ˢ) (⨟ˢᴿ-def σ (wkᴿ s))

  -- ══ lookup through the two hybrid compositions ═══════════════════
  lookup-⨟ˢᴿ : ∀ (x : S₁ ∋ s) (σ : S₁ →ˢ S₂) (ξ : S₂ →ᴿ S₃) →
    x [ σ ⨟ˢᴿ ξ ]ˢ ≡ (x [ σ ]ˢ) [ ξ ]ᴿ
  lookup-⨟ˢᴿ zero    (t ∙ˢ σ) ξ = refl
  lookup-⨟ˢᴿ (suc x) (t ∙ˢ σ) ξ = lookup-⨟ˢᴿ x σ ξ

  -- ══ IIIˢ/IVˢ. map algebra and lifting, substitution world ════════
  dist : (t ∙ˢ σ₁) ⨟ σ₂ ≡ (t [ σ₂ ]ˢ) ∙ˢ (σ₁ ⨟ σ₂)
  dist = refl

  ⟨wk*⟩-cons : ∀ (ξ : S₁ →ᴿ S₂) (t : S₃ ⊢ s′) (σ : S₂ →ˢ S₃) →
    ⟨ wk*ᴿ s′ ξ ⟩ ⨟ (t ∙ˢ σ) ≡ ⟨ ξ ⟩ ⨟ σ
  ⟨wk*⟩-cons []       t σ = refl
  ⟨wk*⟩-cons (x ∙ᴿ ξ) t σ = cong (_ ∙ˢ_) (⟨wk*⟩-cons ξ t σ)

  comp-idₗ : ⟨ idᴿ {S₁} ⟩ ⨟ σ ≡ σ
  comp-idₗ {σ = []}     = refl
  comp-idₗ {σ = t ∙ˢ σ} = cong (t ∙ˢ_) (trans (⟨wk*⟩-cons idᴿ t σ) comp-idₗ)

  interact : ⟨ wkᴿ s ⟩ ⨟ (t ∙ˢ σ) ≡ σ
  interact {t = t} {σ = σ} = trans (⟨wk*⟩-cons idᴿ t σ) comp-idₗ

  ⟨wk*⟩-lift : ∀ (ξ : S₁ →ᴿ S₂) (σ : S₂ →ˢ S₃) →
    ⟨ wk*ᴿ s ξ ⟩ ⨟ (σ ↑ˢ s) ≡ (⟨ ξ ⟩ ⨟ σ) ⨟ˢᴿ wkᴿ s
  ⟨wk*⟩-lift []       σ = refl
  ⟨wk*⟩-lift (x ∙ᴿ ξ) σ = cong2 _∙ˢ_ (lookup-⨟ˢᴿ x σ (wkᴿ _)) (⟨wk*⟩-lift ξ σ)

  lift-dist-compᴿˢ : ⟨ ξ ↑ᴿ s ⟩ ⨟ (σ ↑ˢ s) ≡ ((⟨ ξ ⟩ ⨟ σ) ↑ˢ s)
  lift-dist-compᴿˢ {ξ = ξ} {σ = σ} = cong ((`_ zero) ∙ˢ_) (⟨wk*⟩-lift ξ σ)

  -- ══ the mixed compositionality laws, stratified ══════════════════
  compositionalityᴿˢ : ∀ (x/t : S₁ ⊢[ m ] s) {ξ : S₁ →ᴿ S₂} {σ : S₂ →ˢ S₃} →
    (x/t [ ξ ]ᴿ) [ σ ]ˢ ≡ x/t [ (⟨ ξ ⟩ ⨟ σ) ]ˢ
  compositionalityᴿˢ zero    {ξ = y ∙ᴿ ξ} = refl
  compositionalityᴿˢ (suc x) {ξ = y ∙ᴿ ξ} = compositionalityᴿˢ x
  compositionalityᴿˢ (`_ x) = compositionalityᴿˢ x
  compositionalityᴿˢ (λx_ expr0)       = cong1 λx_ (trans (compositionalityᴿˢ expr0) (cong (expr0 [_]ˢ) lift-dist-compᴿˢ))
  compositionalityᴿˢ (_·_ expr0 expr1) = cong2 _·_ (compositionalityᴿˢ expr0) (compositionalityᴿˢ expr1)

  ⨟ˢᴿ-lift : ∀ (σ : S₁ →ˢ S₂) (ξ : S₂ →ᴿ S₃) →
    (σ ⨟ˢᴿ wkᴿ s) ⨟ˢᴿ (ξ ↑ᴿ s) ≡ (σ ⨟ˢᴿ ξ) ⨟ˢᴿ wkᴿ s
  ⨟ˢᴿ-lift []       ξ = refl
  ⨟ˢᴿ-lift (t ∙ˢ σ) ξ = cong2 _∙ˢ_
    (trans (compositionalityᴿᴿ t) (trans (cong (t [_]ᴿ) lift-wkᴿ) (sym (compositionalityᴿᴿ t))))
    (⨟ˢᴿ-lift σ ξ)

  lift-⨟ˢᴿ : ∀ {σ : S₁ →ˢ S₂} {ξ : S₂ →ᴿ S₃} →
    (σ ↑ˢ s) ⨟ˢᴿ (ξ ↑ᴿ s) ≡ ((σ ⨟ˢᴿ ξ) ↑ˢ s)
  lift-⨟ˢᴿ {σ = σ} {ξ = ξ} = cong ((`_ zero) ∙ˢ_) (⨟ˢᴿ-lift σ ξ)

  compositionalityˢᴿ′ : ∀ (x/t : S₁ ⊢[ m ] s) {σ : S₁ →ˢ S₂} {ξ : S₂ →ᴿ S₃} →
    (x/t [ σ ]ˢ) [ ξ ]ᴿ ≡ x/t [ (σ ⨟ˢᴿ ξ) ]ˢ
  compositionalityˢᴿ′ zero    {σ = t ∙ˢ σ} = refl
  compositionalityˢᴿ′ (suc x) {σ = t ∙ˢ σ} = compositionalityˢᴿ′ x
  compositionalityˢᴿ′ (`_ x) = compositionalityˢᴿ′ x
  compositionalityˢᴿ′ (λx_ expr0)       = cong1 λx_ (trans (compositionalityˢᴿ′ expr0) (cong (expr0 [_]ˢ) lift-⨟ˢᴿ))
  compositionalityˢᴿ′ (_·_ expr0 expr1) = cong2 _·_ (compositionalityˢᴿ′ expr0) (compositionalityˢᴿ′ expr1)

  compositionalityˢᴿ : ∀ (x/t : S₁ ⊢[ m ] s) {σ₁ : S₁ →ˢ S₂} {ξ₂ : S₂ →ᴿ S₃} →
    (x/t [ σ₁ ]ˢ) [ ξ₂ ]ᴿ ≡ x/t [ (σ₁ ⨟ ⟨ ξ₂ ⟩) ]ˢ
  compositionalityˢᴿ x/t {σ₁ = σ} {ξ₂ = ξ} =
    trans (compositionalityˢᴿ′ x/t) (cong (x/t [_]ˢ) (⨟ˢᴿ-def σ ξ))

  lift-dist-compˢᴿ : ∀ {σ : S₁ →ˢ S₂} {ξ : S₂ →ᴿ S₃} →
    ((σ ↑ˢ s) ⨟ ⟨ ξ ↑ᴿ s ⟩) ≡ ((σ ⨟ ⟨ ξ ⟩) ↑ˢ s)
  lift-dist-compˢᴿ {σ = σ} {ξ = ξ} =
    trans (sym (⨟ˢᴿ-def (σ ↑ˢ _) (ξ ↑ᴿ _)))
          (trans lift-⨟ˢᴿ (cong (_↑ˢ _) (⨟ˢᴿ-def σ ξ)))

  lift-wk : ⟨ wkᴿ s ⟩ ⨟ (σ ↑ˢ s) ≡ σ ⨟ ⟨ wkᴿ s ⟩
  lift-wk {s = s} {σ = σ} = trans (⟨wk*⟩-lift idᴿ σ)
    (trans (cong (_⨟ˢᴿ wkᴿ s) comp-idₗ) (⨟ˢᴿ-def σ (wkᴿ s)))

  ⨟ˢᴿwk-lift : ∀ (σ₁ : S₁ →ˢ S₂) (σ₂ : S₂ →ˢ S₃) →
    (σ₁ ⨟ˢᴿ wkᴿ s) ⨟ (σ₂ ↑ˢ s) ≡ (σ₁ ⨟ σ₂) ⨟ˢᴿ wkᴿ s
  ⨟ˢᴿwk-lift []       σ₂ = refl
  ⨟ˢᴿwk-lift {s = s} (t ∙ˢ σ₁) σ₂ = cong2 _∙ˢ_
    (trans (compositionalityᴿˢ t)
      (trans (cong (t [_]ˢ) (trans lift-wk (sym (⨟ˢᴿ-def σ₂ (wkᴿ s)))))
             (sym (compositionalityˢᴿ′ t))))
    (⨟ˢᴿwk-lift σ₁ σ₂)

  lift-dist-compˢˢ : ((σ₁ ↑ˢ s) ⨟ (σ₂ ↑ˢ s)) ≡ ((σ₁ ⨟ σ₂) ↑ˢ s)
  lift-dist-compˢˢ {σ₁ = σ₁} {σ₂ = σ₂} = cong ((`_ zero) ∙ˢ_) (⨟ˢᴿwk-lift σ₁ σ₂)

  -- ══ Vˢ. monad laws, substitution world ═══════════════════════════
  compositionalityˢˢ : ∀ (x/t : S₁ ⊢[ m ] s) {σ₁ : S₁ →ˢ S₂} {σ₂ : S₂ →ˢ S₃} →
    (x/t [ σ₁ ]ˢ) [ σ₂ ]ˢ ≡ x/t [ (σ₁ ⨟ σ₂) ]ˢ
  compositionalityˢˢ zero    {σ₁ = t ∙ˢ σ₁} = refl
  compositionalityˢˢ (suc x) {σ₁ = t ∙ˢ σ₁} = compositionalityˢˢ x
  compositionalityˢˢ (`_ x) = compositionalityˢˢ x
  compositionalityˢˢ (λx_ expr0)       = cong1 λx_ (trans (compositionalityˢˢ expr0) (cong (expr0 [_]ˢ) lift-dist-compˢˢ))
  compositionalityˢˢ (_·_ expr0 expr1) = cong2 _·_ (compositionalityˢˢ expr0) (compositionalityˢˢ expr1)

  assoc : (σ₁ ⨟ σ₂) ⨟ σ₃ ≡ σ₁ ⨟ (σ₂ ⨟ σ₃)
  assoc {σ₁ = []}      = refl
  assoc {σ₁ = t ∙ˢ σ₁} = cong2 _∙ˢ_ (compositionalityˢˢ t) assoc

  comp-idᵣ : σ ⨟ ⟨ idᴿ ⟩ ≡ σ
  comp-idᵣ {σ = []}     = refl
  comp-idᵣ {σ = t ∙ˢ σ} = cong2 _∙ˢ_ (trans (coincidence t idᴿ) (right-idᴿ t)) comp-idᵣ

  ⨟ˢᴿwk-cons : ∀ (σ : S₁ →ˢ S₂) (t : S₃ ⊢ s) (τ : S₂ →ˢ S₃) →
    (σ ⨟ˢᴿ wkᴿ s) ⨟ (t ∙ˢ τ) ≡ σ ⨟ τ
  ⨟ˢᴿwk-cons []       t τ = refl
  ⨟ˢᴿwk-cons (u ∙ˢ σ) t τ =
    cong2 _∙ˢ_ (trans (compositionalityᴿˢ u) (cong (u [_]ˢ) interact)) (⨟ˢᴿwk-cons σ t τ)

  lift-cons : (σ ↑ˢ s) ⨟ (t ∙ˢ τ) ≡ t ∙ˢ (σ ⨟ τ)
  lift-cons {σ = σ} {t = t} {τ = τ} = cong (t ∙ˢ_) (⨟ˢᴿwk-cons σ t τ)

  -- ══ the collapse family: ⟨_⟩ is pushed back into the ᴿ world ═════
  ⟨⟩-comp : ⟨ ξ₁ ⟩ ⨟ ⟨ ξ₂ ⟩ ≡ ⟨ ξ₁ ⨟ᴿ ξ₂ ⟩
  ⟨⟩-comp {ξ₁ = []}      = refl
  ⟨⟩-comp {ξ₁ = x ∙ᴿ ξ₁} {ξ₂ = ξ₂} = cong2 _∙ˢ_ (coincidence-var x ξ₂) ⟨⟩-comp

  ⟨⟩-split-⨟ : ⟨ ξ₁ ⨟ᴿ ξ₂ ⟩ ⨟ σ ≡ ⟨ ξ₁ ⟩ ⨟ (⟨ ξ₂ ⟩ ⨟ σ)
  ⟨⟩-split-⨟ {ξ₁ = []}      = refl
  ⟨⟩-split-⨟ {ξ₁ = x ∙ᴿ ξ₁} = cong2 _∙ˢ_ (compositionalityᴿˢ x) ⟨⟩-split-⨟

  ⟨⟩-lift-cons : ⟨ ξ ↑ᴿ s ⟩ ⨟ (t ∙ˢ σ) ≡ t ∙ˢ (⟨ ξ ⟩ ⨟ σ)
  ⟨⟩-lift-cons {ξ = ξ} {t = t} {σ = σ} = cong (t ∙ˢ_) (⟨wk*⟩-cons ξ t σ)

  lift-id : (⟨ idᴿ {S} ⟩ ↑ˢ s) ≡ ⟨ idᴿ ⟩
  lift-id = ⟨⟩-lift


opaque
  unfolding wk*ᴿ idᴿ wkᴿ _↑ᴿ_ _[_]ᴿ _⨟ᴿ_ ⟨_⟩ _⨟ˢᴿ_ _↑ˢ_ _[_]ˢ _⨟_

  -- ══ IIˢ. traversal rules, substitution world ═════════════════════
  inst-var : (`_ x) [ σ ]ˢ ≡ x [ σ ]ˢ
  inst-λx_ : (λx_ expr0) [ σ ]ˢ       ≡ λx_ (expr0 [ σ ↑ˢ expr ]ˢ)
  inst-_·_ : (_·_ expr0 expr1) [ σ ]ˢ ≡ _·_ (expr0 [ σ ]ˢ) (expr1 [ σ ]ˢ)
  inst-var = refl
  inst-λx_ = refl
  inst-_·_ = refl

-- ─── iterated lifting: the laws ─────────────────────────────────────
--
-- Stated OUTSIDE the opaque block, where `_↑ᴿ_` and `_↑ˢ_` are stuck, so
-- that `cong (_↑ᴿ b)` has a rigid head; inside the block they unfold to
-- a cons over `wk*ᴿ` and the same `cong` cannot be solved.  Still before
-- the REWRITE block: every proof below is a theorem of the base laws.

lift*-idᴿ : ∀ b n → (idᴿ {S} ↑ᴿ*[ b ] n) ≡ idᴿ
lift*-idᴿ b zero    = refl
lift*-idᴿ b (suc n) = trans (cong (_↑ᴿ b) (lift*-idᴿ b n)) lift-idᴿ

lift*-dist-compᴿᴿ : ∀ b n → ((ξ₁ ↑ᴿ*[ b ] n) ⨟ᴿ (ξ₂ ↑ᴿ*[ b ] n)) ≡ ((ξ₁ ⨟ᴿ ξ₂) ↑ᴿ*[ b ] n)
lift*-dist-compᴿᴿ b zero = refl
lift*-dist-compᴿᴿ {ξ₁ = ξ₁} {ξ₂ = ξ₂} b (suc n) =
  trans lift-dist-compᴿᴿ (cong (_↑ᴿ b) (lift*-dist-compᴿᴿ {ξ₁ = ξ₁} {ξ₂ = ξ₂} b n))

lift*-dist-compᴿˢ : ∀ b n {ξ : S₁ →ᴿ S₂} {σ : S₂ →ˢ S₃} →
  (⟨ ξ ↑ᴿ*[ b ] n ⟩ ⨟ (σ ↑ˢ*[ b ] n)) ≡ ((⟨ ξ ⟩ ⨟ σ) ↑ˢ*[ b ] n)
lift*-dist-compᴿˢ b zero = refl
lift*-dist-compᴿˢ b (suc n) {ξ = ξ} {σ = σ} =
  trans lift-dist-compᴿˢ (cong (_↑ˢ b) (lift*-dist-compᴿˢ b n {ξ = ξ} {σ = σ}))

lift*-dist-compˢᴿ : ∀ b n {σ : S₁ →ˢ S₂} {ξ : S₂ →ᴿ S₃} →
  ((σ ↑ˢ*[ b ] n) ⨟ ⟨ ξ ↑ᴿ*[ b ] n ⟩) ≡ ((σ ⨟ ⟨ ξ ⟩) ↑ˢ*[ b ] n)
lift*-dist-compˢᴿ b zero = refl
lift*-dist-compˢᴿ b (suc n) {σ = σ} {ξ = ξ} =
  trans lift-dist-compˢᴿ (cong (_↑ˢ b) (lift*-dist-compˢᴿ b n {σ = σ} {ξ = ξ}))

lift*-dist-compˢˢ : ∀ b n → ((σ₁ ↑ˢ*[ b ] n) ⨟ (σ₂ ↑ˢ*[ b ] n)) ≡ ((σ₁ ⨟ σ₂) ↑ˢ*[ b ] n)
lift*-dist-compˢˢ b zero = refl
lift*-dist-compˢˢ {σ₁ = σ₁} {σ₂ = σ₂} b (suc n) =
  trans lift-dist-compˢˢ (cong (_↑ˢ b) (lift*-dist-compˢˢ {σ₁ = σ₁} {σ₂ = σ₂} b n))

⟨⟩-lift* : ∀ b n → (⟨ ξ ⟩ ↑ˢ*[ b ] n) ≡ ⟨ ξ ↑ᴿ*[ b ] n ⟩
⟨⟩-lift* b zero    = refl
⟨⟩-lift* {ξ = ξ} b (suc n) = trans (cong (_↑ˢ b) (⟨⟩-lift* {ξ = ξ} b n)) ⟨⟩-lift

-- The completion companions of the iterated layer, each a theorem of the
-- base algebra plus the star law above it.

lift*-dist-compᴿᴿ-var : ∀ {S₁ S₂ S₃} (b : Sort) (n : ℕ) {s} {x : (ext* b n S₁) ∋ s}
  {ξ₁ : S₁ →ᴿ S₂} {ξ₂ : S₂ →ᴿ S₃} →
  (x [ (ξ₁ ↑ᴿ*[ b ] n) ]ᴿ) [ (ξ₂ ↑ᴿ*[ b ] n) ]ᴿ ≡ x [ ((ξ₁ ⨟ᴿ ξ₂) ↑ᴿ*[ b ] n) ]ᴿ
lift*-dist-compᴿᴿ-var b n {x = x} {ξ₁ = ξ₁} {ξ₂ = ξ₂} =
  trans (compositionalityᴿᴿ x)
        (cong (λ z → x [ z ]ᴿ) (lift*-dist-compᴿᴿ {ξ₁ = ξ₁} {ξ₂ = ξ₂} b n))

lift*-dist-compᴿᴿ-⨟ᴿ : ∀ {S₁ S₂ S₃ S₄} (b : Sort) (n : ℕ) {ξ₁ : S₁ →ᴿ S₂} {ξ₂ : S₂ →ᴿ S₃}
  {ξ′ : (ext* b n S₃) →ᴿ S₄} →
  (ξ₁ ↑ᴿ*[ b ] n) ⨟ᴿ ((ξ₂ ↑ᴿ*[ b ] n) ⨟ᴿ ξ′) ≡ ((ξ₁ ⨟ᴿ ξ₂) ↑ᴿ*[ b ] n) ⨟ᴿ ξ′
lift*-dist-compᴿᴿ-⨟ᴿ b n {ξ₁ = ξ₁} {ξ₂ = ξ₂} {ξ′ = ξ′} =
  trans (sym assocᴿ) (cong (_⨟ᴿ ξ′) (lift*-dist-compᴿᴿ {ξ₁ = ξ₁} {ξ₂ = ξ₂} b n))

lift*-dist-compˢˢ-⨟ : ∀ {S₁ S₂ S₃} (b : Sort) (n : ℕ) {S₄} {σ₁ : S₁ →ˢ S₂} {σ₂ : S₂ →ˢ S₃}
  {τ : (ext* b n S₃) →ˢ S₄} →
  (σ₁ ↑ˢ*[ b ] n) ⨟ ((σ₂ ↑ˢ*[ b ] n) ⨟ τ) ≡ ((σ₁ ⨟ σ₂) ↑ˢ*[ b ] n) ⨟ τ
lift*-dist-compˢˢ-⨟ b n {σ₁ = σ₁} {σ₂ = σ₂} {τ = τ} =
  trans (sym assoc) (cong (_⨟ τ) (lift*-dist-compˢˢ {σ₁ = σ₁} {σ₂ = σ₂} b n))

lift*-dist-compᴿˢ-⨟ : ∀ {S₁ S₂ S₃} (b : Sort) (n : ℕ) {S₄} {ξ : S₁ →ᴿ S₂} {σ : S₂ →ˢ S₃}
  {τ : (ext* b n S₃) →ˢ S₄} →
  ⟨ ξ ↑ᴿ*[ b ] n ⟩ ⨟ ((σ ↑ˢ*[ b ] n) ⨟ τ) ≡ ((⟨ ξ ⟩ ⨟ σ) ↑ˢ*[ b ] n) ⨟ τ
lift*-dist-compᴿˢ-⨟ b n {ξ = ξ} {σ = σ} {τ = τ} =
  trans (sym assoc) (cong (_⨟ τ) (lift*-dist-compᴿˢ b n {ξ = ξ} {σ = σ}))

lift*-dist-compˢᴿ-⨟ : ∀ {S₁ S₂ S₃} (b : Sort) (n : ℕ) {S₄} {σ : S₁ →ˢ S₂} {ξ : S₂ →ᴿ S₃}
  {τ : (ext* b n S₃) →ˢ S₄} →
  (σ ↑ˢ*[ b ] n) ⨟ (⟨ ξ ↑ᴿ*[ b ] n ⟩ ⨟ τ) ≡ ((σ ⨟ ⟨ ξ ⟩) ↑ˢ*[ b ] n) ⨟ τ
lift*-dist-compˢᴿ-⨟ b n {σ = σ} {ξ = ξ} {τ = τ} =
  trans (sym assoc) (cong (_⨟ τ) (lift*-dist-compˢᴿ b n {σ = σ} {ξ = ξ}))

lift*-dist-compᴿˢ-var : ∀ {S₁ S₂ S₃} (b : Sort) (n : ℕ) {s} {x : (ext* b n S₁) ∋ s}
  {ξ : S₁ →ᴿ S₂} {σ : S₂ →ˢ S₃} →
  (x [ (ξ ↑ᴿ*[ b ] n) ]ᴿ) [ (σ ↑ˢ*[ b ] n) ]ˢ ≡ x [ ((⟨ ξ ⟩ ⨟ σ) ↑ˢ*[ b ] n) ]ˢ
lift*-dist-compᴿˢ-var b n {x = x} {ξ = ξ} {σ = σ} =
  trans (compositionalityᴿˢ x)
        (cong (λ z → x [ z ]ˢ) (lift*-dist-compᴿˢ b n {ξ = ξ} {σ = σ}))

⟨⟩-comp-⨟-lift*-dist-compᴿᴿ : ∀ {S₁ S₂ S₃} (b : Sort) (n : ℕ) {S₄} {ξ₁ : S₁ →ᴿ S₂} {ξ₂ : S₂ →ᴿ S₃}
  {τ : (ext* b n S₃) →ˢ S₄} →
  ⟨ ξ₁ ↑ᴿ*[ b ] n ⟩ ⨟ (⟨ ξ₂ ↑ᴿ*[ b ] n ⟩ ⨟ τ) ≡ ⟨ (ξ₁ ⨟ᴿ ξ₂) ↑ᴿ*[ b ] n ⟩ ⨟ τ
⟨⟩-comp-⨟-lift*-dist-compᴿᴿ b n {ξ₁ = ξ₁} {ξ₂ = ξ₂} {τ = τ} =
  trans (sym assoc)
        (trans (cong (_⨟ τ) ⟨⟩-comp)
               (cong (λ z → ⟨ z ⟩ ⨟ τ) (lift*-dist-compᴿᴿ {ξ₁ = ξ₁} {ξ₂ = ξ₂} b n)))

lift*-dist-compᴿˢ-⨟-var : ∀ {S₁ S₂ S₃} (b : Sort) (n : ℕ) {S₄} {s} {x : (ext* b n S₁) ∋ s}
  {ξ : S₁ →ᴿ S₂} {σ : S₂ →ˢ S₃} {τ : (ext* b n S₃) →ˢ S₄} →
  (x [ (ξ ↑ᴿ*[ b ] n) ]ᴿ) [ ((σ ↑ˢ*[ b ] n) ⨟ τ) ]ˢ ≡ x [ (((⟨ ξ ⟩ ⨟ σ) ↑ˢ*[ b ] n) ⨟ τ) ]ˢ
lift*-dist-compᴿˢ-⨟-var b n {x = x} {ξ = ξ} {σ = σ} {τ = τ} =
  trans (compositionalityᴿˢ x)
        (trans (cong (λ z → x [ z ]ˢ) (sym assoc))
               (cong (λ z → x [ (z ⨟ τ) ]ˢ) (lift*-dist-compᴿˢ b n {ξ = ξ} {σ = σ})))

⟨⟩-split*-tail : ∀ {S₁ S₂ S₃} (b : Sort) (n : ℕ) {S₄} {σ : S₁ →ˢ S₂} {ξ : S₂ →ᴿ S₃}
  {ξ′ : (ext* b n S₃) →ᴿ S₄} →
  (σ ↑ˢ*[ b ] n) ⨟ ⟨ (ξ ↑ᴿ*[ b ] n) ⨟ᴿ ξ′ ⟩ ≡ ((σ ⨟ ⟨ ξ ⟩) ↑ˢ*[ b ] n) ⨟ ⟨ ξ′ ⟩
⟨⟩-split*-tail b n {σ = σ} {ξ = ξ} {ξ′ = ξ′} =
  trans (cong ((σ ↑ˢ*[ b ] n) ⨟_) (sym ⟨⟩-comp))
        (trans (sym assoc) (cong (_⨟ ⟨ ξ′ ⟩) (lift*-dist-compˢᴿ b n {σ = σ} {ξ = ξ})))

-- ═══ THE COMPLETED TWO-WORLD SYSTEM ════════════════════════════════
--
-- The vector model needs NO completion families.  The `-⨟` continuation
-- companions, the mode-V `-var` companions and the coercion family that
-- the function model registers are all subsumed here, because a vector
-- composition reduces structurally where a function composition is
-- stuck.  closure-vec.agda states every one of those absences and
-- checks it by `refl`.

-- 54 rules -- 33 signature-independent, 15 for the
-- iterated (variable-arity) lifting, 6 traversal rules (one instᴿ-*
-- and one inst-* per constructor, plus the variable case).

{-# REWRITE
  def-wkᴿ def-∙ᴿ-zero def-∙ᴿ-suc def-↑ᴿ-zero def-↑ᴿ-suc
  instᴿ-var instᴿ-λx_ instᴿ-_·_
  assocᴿ comp-idₗᴿ comp-idᵣᴿ interactᴿ
  lift-idᴿ lift-dist-compᴿᴿ lift-wkᴿ
  right-idᴿ compositionalityᴿᴿ-var compositionalityᴿᴿ
  coincidence-var def-∙ˢ-zero def-∙ˢ-suc def-↑ˢ-zero def-↑ˢ-suc
  inst-var inst-λx_ inst-_·_
  assoc dist interact comp-idₗ comp-idᵣ
  lift-wk lift-cons lift-dist-compˢˢ
  compositionalityˢˢ compositionalityᴿˢ compositionalityˢᴿ lift-dist-compᴿˢ
  coincidence ⟨⟩-comp ⟨⟩-split-⨟ ⟨⟩-lift ⟨⟩-lift-cons
  lift*-idᴿ lift*-dist-compᴿᴿ lift*-dist-compᴿˢ lift*-dist-compˢᴿ
  lift*-dist-compˢˢ ⟨⟩-lift* lift*-dist-compᴿᴿ-var lift*-dist-compᴿᴿ-⨟ᴿ
  lift*-dist-compˢˢ-⨟ lift*-dist-compᴿˢ-⨟ lift*-dist-compˢᴿ-⨟
  lift*-dist-compᴿˢ-var ⟨⟩-comp-⨟-lift*-dist-compᴿᴿ lift*-dist-compᴿˢ-⨟-var
  ⟨⟩-split*-tail
#-}

-- ─── the derived operations ─────────────────────────────────────────
-- Neither is primitive and neither has rules of its own: weakening is a
-- renaming, single substitution is a cons onto the identity.  The
-- rewrite system computes through both without knowing they exist.

weaken : S ⊢ s → (s′ ∷ S) ⊢ s
weaken t = t [ wkᴿ _ ]ᴿ

_[_]₀ : (s′ ∷ S) ⊢ s → S ⊢ s′ → S ⊢ s
t [ t′ ]₀ = t [ (t′ ∙ˢ idˢ) ]ˢ
