{-# OPTIONS --rewriting --local-confluence-check #-}

-- Generated by generator/agdasubst.py.  DO NOT EDIT.

module Languages.FsubRecords where

open import Relation.Binary.PropositionalEquality
  using (_≡_; refl; sym; cong; trans; module ≡-Reasoning)
open ≡-Reasoning
open import Agda.Builtin.Equality.Rewrite
open import Data.List using (List; []; _∷_)
open import Data.Nat using (ℕ; zero; suc)

open import Axiom.Extensionality.Propositional using (Extensionality)
postulate
  fun-ext : ∀ {ℓ₁ ℓ₂} → Extensionality ℓ₁ ℓ₂

ext : {A : Set} {B : A → Set} {C : A → Set} → {f g : (a : A) → B a → C a} →
  (∀ {a} x → f a x ≡ g a x) → f ≡ g
ext f = fun-ext λ _ → fun-ext λ x → f x

cong1 : ∀ {A1 A2 : Set} (f : A1 → A2) {a1 a2} →
  a1 ≡ a2 → f a1 ≡ f a2
cong1 f refl = refl

cong2 : ∀ {A1 A2 A3 : Set} (f : A1 → A2 → A3) {a1 a2 a3 a4} →
  a1 ≡ a2 → a3 ≡ a4 → f a1 a3 ≡ f a2 a4
cong2 f refl refl = refl

cong3 : ∀ {A1 A2 A3 A4 : Set} (f : A1 → A2 → A3 → A4) {a1 a2 a3 a4 a5 a6} →
  a1 ≡ a2 → a3 ≡ a4 → a5 ≡ a6 → f a1 a3 a5 ≡ f a2 a4 a6
cong3 f refl refl refl = refl


Label : Set
Label = ℕ

infixr 5 _⇒_
infixl 6 _·_
infixl 6 _•_
infixl 7 _#_

-- ─── syntax ─────────────────────────────────────────────────────────

data Sort : Set where
  expr type rtype rexpr : Sort
Scope = List Sort

variable
  s s₁ s₂ s′ : Sort
  S S₁ S₂ S₃ : Scope


-- ─── iterated lifting: a binder of variable arity ───────────────────
-- `ext* b n S` extends a scope by n copies of one sort.  It computes on
-- n, so the rewrite system needs rules only for n abstract.

ext* : Sort → ℕ → Scope → Scope
ext* b zero    S = S
ext* b (suc n) S = b ∷ ext* b n S

data Mode : Set where V T : Mode

variable
  m : Mode

data _⊢[_]_ : Scope → Mode → Sort → Set

_⊢_ = _⊢[ T ]_
_∋_ = _⊢[ V ]_

data _⊢[_]_ where
  zero     : (s ∷ S) ∋ s
  suc      : S ∋ s → (s′ ∷ S) ∋ s
  `_       : S ∋ s → S ⊢ s
  Top      : S ⊢ type
  _⇒_      : S ⊢ type → S ⊢ type → S ⊢ type
  ∀[<:_]_  : S ⊢ type → (type ∷ S) ⊢ type → S ⊢ type
  RcdT     : S ⊢ rtype → S ⊢ type
  nilT     : S ⊢ rtype
  consT    : Label → S ⊢ type → S ⊢ rtype → S ⊢ rtype
  λx[_]_   : S ⊢ type → (expr ∷ S) ⊢ expr → S ⊢ expr
  Λα[<:_]_ : S ⊢ type → (type ∷ S) ⊢ expr → S ⊢ expr
  _·_      : S ⊢ expr → S ⊢ expr → S ⊢ expr
  _•_      : S ⊢ expr → S ⊢ type → S ⊢ expr
  RcdE     : S ⊢ rexpr → S ⊢ expr
  _#_      : S ⊢ expr → Label → S ⊢ expr
  nilE     : S ⊢ rexpr
  consE    : Label → S ⊢ expr → S ⊢ rexpr → S ⊢ rexpr

variable
  t t₁ t₂ t′ : S ⊢ s
  x x′       : S ∋ s
  x/t x/t′   : S ⊢[ m ] s

variable
  expr0 expr1 : S ⊢ expr
  label0 : Label
  rexpr0 : S ⊢ rexpr
  rtype0 : S ⊢ rtype
  type0 type1 : S ⊢ type

-- ─── maps ───────────────────────────────────────────────────────────

_→[_]_ : Scope → Mode → Scope → Set
S₁ →[ m ] S₂ = ∀ s → S₁ ∋ s → S₂ ⊢[ m ] s

_→ᴿ_ : Scope → Scope → Set
S₁ →ᴿ S₂ = S₁ →[ V ] S₂

_→ˢ_ : Scope → Scope → Set
S₁ →ˢ S₂ = S₁ →[ T ] S₂

variable
  ξ ξ′ ξ₁ ξ₂ ξ₃ : S₁ →ᴿ S₂
  σ σ₁ σ₂ σ₃ τ : S₁ →ˢ S₂

-- ─── the renaming world ─────────────────────────────────────────────

opaque
  idᴿ : S →ᴿ S
  idᴿ _ x = x

  wkᴿ : ∀ s′ → S →ᴿ (s′ ∷ S)
  wkᴿ _ _ x = suc x

  _∙ᴿ_ : S₂ ∋ s → S₁ →ᴿ S₂ → (s ∷ S₁) →ᴿ S₂
  (x ∙ᴿ ξ) _ zero    = x
  (_ ∙ᴿ ξ) _ (suc x) = ξ _ x

opaque
  unfolding wkᴿ

  _↑ᴿ_ : S₁ →ᴿ S₂ → ∀ s → (s ∷ S₁) →ᴿ (s ∷ S₂)
  (ξ ↑ᴿ _) _ zero    = zero
  (ξ ↑ᴿ _) _ (suc x) = suc (ξ _ x)

-- The n-fold renaming lift.  Derived and transparent, and defined
-- between the _↑ᴿ_ block and the _[_]ᴿ block, because the traversal of a
-- variable-arity binder uses it.

_↑ᴿ*[_]_ : S₁ →ᴿ S₂ → ∀ b n → (ext* b n S₁) →ᴿ (ext* b n S₂)
ξ ↑ᴿ*[ b ] zero    = ξ
ξ ↑ᴿ*[ b ] (suc n) = (ξ ↑ᴿ*[ b ] n) ↑ᴿ b

opaque
  unfolding wkᴿ _↑ᴿ_

  _[_]ᴿ : S₁ ⊢[ m ] s → S₁ →ᴿ S₂ → S₂ ⊢[ m ] s
  _[_]ᴿ {m = V} x ξ    = ξ _ x
  (`_ x) [ ξ ]ᴿ = `_ (x [ ξ ]ᴿ)
  Top                         [ ξ ]ᴿ = Top
  (_⇒_ type0 type1)           [ ξ ]ᴿ = _⇒_ (type0 [ ξ ]ᴿ) (type1 [ ξ ]ᴿ)
  (∀[<:_]_ type0 type1)       [ ξ ]ᴿ = ∀[<:_]_ (type0 [ ξ ]ᴿ) (type1 [ ξ ↑ᴿ type ]ᴿ)
  (RcdT rtype0)               [ ξ ]ᴿ = RcdT (rtype0 [ ξ ]ᴿ)
  nilT                        [ ξ ]ᴿ = nilT
  (consT label0 type0 rtype0) [ ξ ]ᴿ = consT label0 (type0 [ ξ ]ᴿ) (rtype0 [ ξ ]ᴿ)
  (λx[_]_ type0 expr0)        [ ξ ]ᴿ = λx[_]_ (type0 [ ξ ]ᴿ) (expr0 [ ξ ↑ᴿ expr ]ᴿ)
  (Λα[<:_]_ type0 expr0)      [ ξ ]ᴿ = Λα[<:_]_ (type0 [ ξ ]ᴿ) (expr0 [ ξ ↑ᴿ type ]ᴿ)
  (_·_ expr0 expr1)           [ ξ ]ᴿ = _·_ (expr0 [ ξ ]ᴿ) (expr1 [ ξ ]ᴿ)
  (_•_ expr0 type0)           [ ξ ]ᴿ = _•_ (expr0 [ ξ ]ᴿ) (type0 [ ξ ]ᴿ)
  (RcdE rexpr0)               [ ξ ]ᴿ = RcdE (rexpr0 [ ξ ]ᴿ)
  (_#_ expr0 label0)          [ ξ ]ᴿ = _#_ (expr0 [ ξ ]ᴿ) label0
  nilE                        [ ξ ]ᴿ = nilE
  (consE label0 expr0 rexpr0) [ ξ ]ᴿ = consE label0 (expr0 [ ξ ]ᴿ) (rexpr0 [ ξ ]ᴿ)

  _⨟ᴿ_ : S₁ →ᴿ S₂ → S₂ →ᴿ S₃ → S₁ →ᴿ S₃
  (ξ₁ ⨟ᴿ ξ₂) _ x = (ξ₁ _ x) [ ξ₂ ]ᴿ

-- ─── the substitution world ─────────────────────────────────────────

opaque
  ⟨_⟩ : S₁ →ᴿ S₂ → S₁ →ˢ S₂
  ⟨ ξ ⟩ _ x = `_ (x [ ξ ]ᴿ)

idˢ : S →ˢ S
idˢ = ⟨ idᴿ ⟩

wkˢ : ∀ s′ → S →ˢ (s′ ∷ S)
wkˢ s′ = ⟨ wkᴿ s′ ⟩

opaque
  _∙ˢ_ : S₂ ⊢ s → S₁ →ˢ S₂ → (s ∷ S₁) →ˢ S₂
  (t ∙ˢ σ) _ zero    = t
  (t ∙ˢ σ) _ (suc x) = σ _ x
opaque
  unfolding _∙ˢ_
  _↑ˢ_ : S₁ →ˢ S₂ → ∀ s → (s ∷ S₁) →ˢ (s ∷ S₂)
  (σ ↑ˢ _) _ zero    = `_ zero
  (σ ↑ˢ _) _ (suc x) = (σ _ x) [ wkᴿ _ ]ᴿ

-- The n-fold substitution lift, likewise between _↑ˢ_ and _[_]ˢ.

_↑ˢ*[_]_ : S₁ →ˢ S₂ → ∀ b n → (ext* b n S₁) →ˢ (ext* b n S₂)
σ ↑ˢ*[ b ] zero    = σ
σ ↑ˢ*[ b ] (suc n) = (σ ↑ˢ*[ b ] n) ↑ˢ b

opaque
  unfolding _∙ˢ_ _↑ˢ_
  _[_]ˢ : S₁ ⊢[ m ] s → S₁ →ˢ S₂ → S₂ ⊢ s
  _[_]ˢ {m = V} x σ    = σ _ x
  (`_ x) [ σ ]ˢ = σ _ x
  Top                         [ σ ]ˢ = Top
  (_⇒_ type0 type1)           [ σ ]ˢ = _⇒_ (type0 [ σ ]ˢ) (type1 [ σ ]ˢ)
  (∀[<:_]_ type0 type1)       [ σ ]ˢ = ∀[<:_]_ (type0 [ σ ]ˢ) (type1 [ σ ↑ˢ type ]ˢ)
  (RcdT rtype0)               [ σ ]ˢ = RcdT (rtype0 [ σ ]ˢ)
  nilT                        [ σ ]ˢ = nilT
  (consT label0 type0 rtype0) [ σ ]ˢ = consT label0 (type0 [ σ ]ˢ) (rtype0 [ σ ]ˢ)
  (λx[_]_ type0 expr0)        [ σ ]ˢ = λx[_]_ (type0 [ σ ]ˢ) (expr0 [ σ ↑ˢ expr ]ˢ)
  (Λα[<:_]_ type0 expr0)      [ σ ]ˢ = Λα[<:_]_ (type0 [ σ ]ˢ) (expr0 [ σ ↑ˢ type ]ˢ)
  (_·_ expr0 expr1)           [ σ ]ˢ = _·_ (expr0 [ σ ]ˢ) (expr1 [ σ ]ˢ)
  (_•_ expr0 type0)           [ σ ]ˢ = _•_ (expr0 [ σ ]ˢ) (type0 [ σ ]ˢ)
  (RcdE rexpr0)               [ σ ]ˢ = RcdE (rexpr0 [ σ ]ˢ)
  (_#_ expr0 label0)          [ σ ]ˢ = _#_ (expr0 [ σ ]ˢ) label0
  nilE                        [ σ ]ˢ = nilE
  (consE label0 expr0 rexpr0) [ σ ]ˢ = consE label0 (expr0 [ σ ]ˢ) (rexpr0 [ σ ]ˢ)

  _⨟_ : S₁ →ˢ S₂ → S₂ →ˢ S₃ → S₁ →ˢ S₃
  (σ₁ ⨟ σ₂) _ x = (σ₁ _ x) [ σ₂ ]ˢ


-- ─── the two-world rewrite system ───────────────────────────────────

opaque
  unfolding idᴿ wkᴿ _∙ᴿ_ _↑ᴿ_ _[_]ᴿ _⨟ᴿ_ ⟨_⟩ _∙ˢ_ _[_]ˢ _↑ˢ_ _⨟_

  -- ══ Iᴿ. applied rules, renaming world ═════════════════════════════
  def-wkᴿ       : x [ wkᴿ s′ ]ᴿ ≡ suc x
  def-∙ᴿ-zero   : zero [ (x ∙ᴿ ξ) ]ᴿ ≡ x
  def-∙ᴿ-suc    : (suc {s′ = s′} x′) [ (x ∙ᴿ ξ) ]ᴿ ≡ x′ [ ξ ]ᴿ
  def-↑ᴿ-zero   : zero [ (ξ ↑ᴿ s) ]ᴿ ≡ zero
  def-↑ᴿ-suc    : (suc x) [ (ξ ↑ᴿ s) ]ᴿ ≡ suc (x [ ξ ]ᴿ)

  -- ══ IIᴿ. traversal rules, renaming world ═════════════════════════
  instᴿ-var : (`_ x) [ ξ ]ᴿ ≡ `_ (x [ ξ ]ᴿ)
  instᴿ-Top      : Top {S = S} [ ξ ]ᴿ                 ≡ Top
  instᴿ-_⇒_      : (_⇒_ type0 type1) [ ξ ]ᴿ           ≡ _⇒_ (type0 [ ξ ]ᴿ) (type1 [ ξ ]ᴿ)
  instᴿ-∀[<:_]_  : (∀[<:_]_ type0 type1) [ ξ ]ᴿ       ≡ ∀[<:_]_ (type0 [ ξ ]ᴿ) (type1 [ ξ ↑ᴿ type ]ᴿ)
  instᴿ-RcdT     : (RcdT rtype0) [ ξ ]ᴿ               ≡ RcdT (rtype0 [ ξ ]ᴿ)
  instᴿ-nilT     : nilT {S = S} [ ξ ]ᴿ                ≡ nilT
  instᴿ-consT    : (consT label0 type0 rtype0) [ ξ ]ᴿ ≡ consT label0 (type0 [ ξ ]ᴿ) (rtype0 [ ξ ]ᴿ)
  instᴿ-λx[_]_   : (λx[_]_ type0 expr0) [ ξ ]ᴿ        ≡ λx[_]_ (type0 [ ξ ]ᴿ) (expr0 [ ξ ↑ᴿ expr ]ᴿ)
  instᴿ-Λα[<:_]_ : (Λα[<:_]_ type0 expr0) [ ξ ]ᴿ      ≡ Λα[<:_]_ (type0 [ ξ ]ᴿ) (expr0 [ ξ ↑ᴿ type ]ᴿ)
  instᴿ-_·_      : (_·_ expr0 expr1) [ ξ ]ᴿ           ≡ _·_ (expr0 [ ξ ]ᴿ) (expr1 [ ξ ]ᴿ)
  instᴿ-_•_      : (_•_ expr0 type0) [ ξ ]ᴿ           ≡ _•_ (expr0 [ ξ ]ᴿ) (type0 [ ξ ]ᴿ)
  instᴿ-RcdE     : (RcdE rexpr0) [ ξ ]ᴿ               ≡ RcdE (rexpr0 [ ξ ]ᴿ)
  instᴿ-_#_      : (_#_ expr0 label0) [ ξ ]ᴿ          ≡ _#_ (expr0 [ ξ ]ᴿ) label0
  instᴿ-nilE     : nilE {S = S} [ ξ ]ᴿ                ≡ nilE
  instᴿ-consE    : (consE label0 expr0 rexpr0) [ ξ ]ᴿ ≡ consE label0 (expr0 [ ξ ]ᴿ) (rexpr0 [ ξ ]ᴿ)

  -- ══ IIIᴿ. map algebra, renaming world ════════════════════════════
  assocᴿ      : (ξ₁ ⨟ᴿ ξ₂) ⨟ᴿ ξ₃ ≡ ξ₁ ⨟ᴿ (ξ₂ ⨟ᴿ ξ₃)
  comp-idₗᴿ   : idᴿ ⨟ᴿ ξ ≡ ξ
  comp-idᵣᴿ   : ξ ⨟ᴿ idᴿ ≡ ξ
  distᴿ       : (x ∙ᴿ ξ₁) ⨟ᴿ ξ₂ ≡ (x [ ξ₂ ]ᴿ) ∙ᴿ (ξ₁ ⨟ᴿ ξ₂)
  interactᴿ   : wkᴿ s ⨟ᴿ (x ∙ᴿ ξ) ≡ ξ

  -- ══ IVᴿ. lifting rules, renaming world ═══════════════════════════
  lift-idᴿ     : (idᴿ {S} ↑ᴿ s) ≡ idᴿ
  lift-dist-compᴿᴿ : ((ξ₁ ↑ᴿ s) ⨟ᴿ (ξ₂ ↑ᴿ s)) ≡ ((ξ₁ ⨟ᴿ ξ₂) ↑ᴿ s)
  lift-wkᴿ     : wkᴿ s ⨟ᴿ (ξ ↑ᴿ s) ≡ ξ ⨟ᴿ wkᴿ s
  lift-consᴿ   : (ξ ↑ᴿ s) ⨟ᴿ (x ∙ᴿ ξ′) ≡ x ∙ᴿ (ξ ⨟ᴿ ξ′)

  -- ══ Vᴿ. monad laws, renaming world ═══════════════════════════════
  right-idᴿ : ∀ (x/t : S ⊢[ m ] s) → x/t [ idᴿ ]ᴿ ≡ x/t
  compositionalityᴿᴿ-var  : ∀ (x : S₁ ∋ s) {ξ₁ : S₁ →ᴿ S₂} {ξ₂ : S₂ →ᴿ S₃} →
    x [ (ξ₁ ⨟ᴿ ξ₂) ]ᴿ ≡ (x [ ξ₁ ]ᴿ) [ ξ₂ ]ᴿ
  compositionalityᴿᴿ   : ∀ (t : S₁ ⊢ s) {ξ₁ : S₁ →ᴿ S₂} {ξ₂ : S₂ →ᴿ S₃} →
    (t [ ξ₁ ]ᴿ) [ ξ₂ ]ᴿ ≡ t [ (ξ₁ ⨟ᴿ ξ₂) ]ᴿ

  -- ══ VIᴿ. completion companions, renaming world ═══════════════════
  lift-dist-compᴿᴿ-var  : (x [ (ξ₁ ↑ᴿ s) ]ᴿ) [ (ξ₂ ↑ᴿ s) ]ᴿ ≡ x [ ((ξ₁ ⨟ᴿ ξ₂) ↑ᴿ s) ]ᴿ
  interactᴿ-⨟ᴿ    : wkᴿ s ⨟ᴿ ((x ∙ᴿ ξ) ⨟ᴿ ξ′) ≡ ξ ⨟ᴿ ξ′
  lift-wkᴿ-⨟ᴿ     : wkᴿ s ⨟ᴿ ((ξ ↑ᴿ s) ⨟ᴿ ξ′) ≡ ξ ⨟ᴿ (wkᴿ s ⨟ᴿ ξ′)
  lift-dist-compᴿᴿ-⨟ᴿ : (ξ₁ ↑ᴿ s) ⨟ᴿ ((ξ₂ ↑ᴿ s) ⨟ᴿ ξ′) ≡ ((ξ₁ ⨟ᴿ ξ₂) ↑ᴿ s) ⨟ᴿ ξ′

  -- ══ Iˢ. applied rules, substitution world ════════════════════════
  coincidence-var : x [ ⟨ ξ ⟩ ]ˢ ≡ `_ (x [ ξ ]ᴿ)
  def-∙ˢ-zero  : zero [ (t ∙ˢ σ) ]ˢ ≡ t
  def-∙ˢ-suc   : (suc {s′ = s′} x) [ (t ∙ˢ σ) ]ˢ ≡ x [ σ ]ˢ
  def-↑ˢ-zero  : zero [ (σ ↑ˢ s) ]ˢ ≡ `_ zero
  def-↑ˢ-suc   : (suc x) [ (σ ↑ˢ s) ]ˢ ≡ x [ (σ ⨟ ⟨ wkᴿ s ⟩) ]ˢ

  -- ══ IIˢ. traversal rules, substitution world ═════════════════════
  inst-var : (`_ x) [ σ ]ˢ ≡ x [ σ ]ˢ
  inst-Top      : Top {S = S} [ σ ]ˢ                 ≡ Top
  inst-_⇒_      : (_⇒_ type0 type1) [ σ ]ˢ           ≡ _⇒_ (type0 [ σ ]ˢ) (type1 [ σ ]ˢ)
  inst-∀[<:_]_  : (∀[<:_]_ type0 type1) [ σ ]ˢ       ≡ ∀[<:_]_ (type0 [ σ ]ˢ) (type1 [ σ ↑ˢ type ]ˢ)
  inst-RcdT     : (RcdT rtype0) [ σ ]ˢ               ≡ RcdT (rtype0 [ σ ]ˢ)
  inst-nilT     : nilT {S = S} [ σ ]ˢ                ≡ nilT
  inst-consT    : (consT label0 type0 rtype0) [ σ ]ˢ ≡ consT label0 (type0 [ σ ]ˢ) (rtype0 [ σ ]ˢ)
  inst-λx[_]_   : (λx[_]_ type0 expr0) [ σ ]ˢ        ≡ λx[_]_ (type0 [ σ ]ˢ) (expr0 [ σ ↑ˢ expr ]ˢ)
  inst-Λα[<:_]_ : (Λα[<:_]_ type0 expr0) [ σ ]ˢ      ≡ Λα[<:_]_ (type0 [ σ ]ˢ) (expr0 [ σ ↑ˢ type ]ˢ)
  inst-_·_      : (_·_ expr0 expr1) [ σ ]ˢ           ≡ _·_ (expr0 [ σ ]ˢ) (expr1 [ σ ]ˢ)
  inst-_•_      : (_•_ expr0 type0) [ σ ]ˢ           ≡ _•_ (expr0 [ σ ]ˢ) (type0 [ σ ]ˢ)
  inst-RcdE     : (RcdE rexpr0) [ σ ]ˢ               ≡ RcdE (rexpr0 [ σ ]ˢ)
  inst-_#_      : (_#_ expr0 label0) [ σ ]ˢ          ≡ _#_ (expr0 [ σ ]ˢ) label0
  inst-nilE     : nilE {S = S} [ σ ]ˢ                ≡ nilE
  inst-consE    : (consE label0 expr0 rexpr0) [ σ ]ˢ ≡ consE label0 (expr0 [ σ ]ˢ) (rexpr0 [ σ ]ˢ)

  -- ══ VIˢ. completion companions, substitution world ══════════════
  compositionalityᴿˢ-⨟-var      : x [ (⟨ ξ ⟩ ⨟ σ) ]ˢ ≡ (x [ ξ ]ᴿ) [ σ ]ˢ
  def-↑ˢ-zero-⨟  : zero [ ((σ ↑ˢ s) ⨟ τ) ]ˢ ≡ zero [ τ ]ˢ
  def-↑ˢ-suc-⨟   : (suc x) [ ((σ ↑ˢ s) ⨟ τ) ]ˢ ≡ x [ (σ ⨟ (⟨ wkᴿ s ⟩ ⨟ τ)) ]ˢ
  lift-wk-⨟     : ⟨ wkᴿ s ⟩ ⨟ ((σ ↑ˢ s) ⨟ τ) ≡ σ ⨟ (⟨ wkᴿ s ⟩ ⨟ τ)
  lift-dist-compˢˢ-⨟ : (σ₁ ↑ˢ s) ⨟ ((σ₂ ↑ˢ s) ⨟ τ) ≡ ((σ₁ ⨟ σ₂) ↑ˢ s) ⨟ τ

  -- ══ IIIˢ/IVˢ. map algebra and lifting, substitution world ════════
  interact    : ⟨ wkᴿ s ⟩ ⨟ (t ∙ˢ σ) ≡ σ
  comp-idₗ    : ⟨ idᴿ {S₁} ⟩ ⨟ σ ≡ σ
  comp-idᵣ    : σ ⨟ ⟨ idᴿ ⟩ ≡ σ
  lift-wk     : ⟨ wkᴿ s ⟩ ⨟ (σ ↑ˢ s) ≡ σ ⨟ ⟨ wkᴿ s ⟩
  assoc       : (σ₁ ⨟ σ₂) ⨟ σ₃ ≡ σ₁ ⨟ (σ₂ ⨟ σ₃)
  dist        : (t ∙ˢ σ₁) ⨟ σ₂ ≡ (t [ σ₂ ]ˢ) ∙ˢ (σ₁ ⨟ σ₂)
  lift-cons   : (σ ↑ˢ s) ⨟ (t ∙ˢ τ) ≡ t ∙ˢ (σ ⨟ τ)
  lift-dist-compˢˢ : ((σ₁ ↑ˢ s) ⨟ (σ₂ ↑ˢ s)) ≡ ((σ₁ ⨟ σ₂) ↑ˢ s)

  -- ══ Vˢ. monad laws, substitution world ═══════════════════════════
  compositionalityˢˢ : ∀ (x/t : S₁ ⊢[ m ] s) {σ₁ : S₁ →ˢ S₂} {σ₂ : S₂ →ˢ S₃} →
    (x/t [ σ₁ ]ˢ) [ σ₂ ]ˢ ≡ x/t [ (σ₁ ⨟ σ₂) ]ˢ

  -- ══ the two mixed compositionality laws ══════════════════════════
  compositionalityᴿˢ : ∀ (t : S₁ ⊢ s) {ξ₁ : S₁ →ᴿ S₂} {σ₂ : S₂ →ˢ S₃} →
    (t [ ξ₁ ]ᴿ) [ σ₂ ]ˢ ≡ t [ (⟨ ξ₁ ⟩ ⨟ σ₂) ]ˢ
  compositionalityˢᴿ : ∀ (x/t : S₁ ⊢[ m ] s) {σ₁ : S₁ →ˢ S₂} {ξ₂ : S₂ →ᴿ S₃} →
    (x/t [ σ₁ ]ˢ) [ ξ₂ ]ᴿ ≡ x/t [ (σ₁ ⨟ ⟨ ξ₂ ⟩) ]ˢ

  lift-dist-compᴿˢ-⨟ : ∀ {S₄} {ξ : S₁ →ᴿ S₂} {σ : S₂ →ˢ S₃} {τ : (s ∷ S₃) →ˢ S₄} →
    ⟨ ξ ↑ᴿ s ⟩ ⨟ ((σ ↑ˢ s) ⨟ τ) ≡ ((⟨ ξ ⟩ ⨟ σ) ↑ˢ s) ⨟ τ
  lift-dist-compˢᴿ-⨟ : ∀ {S₄} {σ : S₁ →ˢ S₂} {ξ : S₂ →ᴿ S₃} {τ : (s ∷ S₃) →ˢ S₄} →
    (σ ↑ˢ s) ⨟ (⟨ ξ ↑ᴿ s ⟩ ⨟ τ) ≡ ((σ ⨟ ⟨ ξ ⟩) ↑ˢ s) ⨟ τ
  lift-dist-compᴿˢ-var  : (x [ (ξ ↑ᴿ s) ]ᴿ) [ (σ ↑ˢ s) ]ˢ ≡ x [ ((⟨ ξ ⟩ ⨟ σ) ↑ˢ s) ]ˢ
  lift-dist-compᴿˢ-⨟-var : ∀ {S₄} {ξ : S₁ →ᴿ S₂} {σ : S₂ →ˢ S₃} {τ : (s ∷ S₃) →ˢ S₄} →
    (x [ (ξ ↑ᴿ s) ]ᴿ) [ ((σ ↑ˢ s) ⨟ τ) ]ˢ ≡ x [ (((⟨ ξ ⟩ ⨟ σ) ↑ˢ s) ⨟ τ) ]ˢ

  ⟨⟩-lift-cons : ⟨ ξ ↑ᴿ s ⟩ ⨟ (t ∙ˢ σ) ≡ t ∙ˢ (⟨ ξ ⟩ ⨟ σ)
  ⟨⟩-lift-cons-var : (x [ (ξ ↑ᴿ s) ]ᴿ) [ (t ∙ˢ σ) ]ˢ ≡ x [ (t ∙ˢ (⟨ ξ ⟩ ⨟ σ)) ]ˢ

  ⟨⟩-comp-⨟-lift-wkᴿ  : ∀ {S₄} {ξ : S₁ →ᴿ S₂} {τ : (s ∷ S₂) →ˢ S₄} →
    ⟨ wkᴿ s ⟩ ⨟ (⟨ ξ ↑ᴿ s ⟩ ⨟ τ) ≡ ⟨ ξ ⟩ ⨟ (⟨ wkᴿ s ⟩ ⨟ τ)
  ⟨⟩-comp-⨟-interactᴿ  : ∀ {ξ : S₁ →ᴿ S₂} {x : S₂ ∋ s} {τ : S₂ →ˢ S₃} →
    ⟨ wkᴿ s ⟩ ⨟ (⟨ x ∙ᴿ ξ ⟩ ⨟ τ) ≡ ⟨ ξ ⟩ ⨟ τ
  ⟨⟩-comp-⨟-lift-dist-compᴿᴿ : ∀ {S₄} {ξ₁ : S₁ →ᴿ S₂} {ξ₂ : S₂ →ᴿ S₃} {τ : (s ∷ S₃) →ˢ S₄} →
    ⟨ ξ₁ ↑ᴿ s ⟩ ⨟ (⟨ ξ₂ ↑ᴿ s ⟩ ⨟ τ) ≡ ⟨ (ξ₁ ⨟ᴿ ξ₂) ↑ᴿ s ⟩ ⨟ τ
  ⟨⟩-split-tail : ∀ {S₄} {σ : S₁ →ˢ S₂} {ξ : S₂ →ᴿ S₃} {ξ′ : (s ∷ S₃) →ᴿ S₄} →
    (σ ↑ˢ s) ⨟ ⟨ (ξ ↑ᴿ s) ⨟ᴿ ξ′ ⟩ ≡ ((σ ⨟ ⟨ ξ ⟩) ↑ˢ s) ⨟ ⟨ ξ′ ⟩

  -- ══ the collapse family ══════════════════════════════════════════
  coincidence  : ∀ (t : S ⊢ s) (ξ : S →ᴿ S₂) → t [ ⟨ ξ ⟩ ]ˢ ≡ t [ ξ ]ᴿ
  ⟨⟩-comp      : ⟨ ξ₁ ⟩ ⨟ ⟨ ξ₂ ⟩ ≡ ⟨ ξ₁ ⨟ᴿ ξ₂ ⟩
  ⟨⟩-split-⨟   : ⟨ ξ₁ ⨟ᴿ ξ₂ ⟩ ⨟ σ ≡ ⟨ ξ₁ ⟩ ⨟ (⟨ ξ₂ ⟩ ⨟ σ)
  ⟨⟩-lift      : (⟨ ξ ⟩ ↑ˢ s) ≡ ⟨ ξ ↑ᴿ s ⟩

  -- ══ subsumed: σ⇑'s LiftId is a lemma, not a rule ════════════════
  -- ⟨⟩-lift already sends its LHS to ⟨ idᴿ ↑ᴿ s ⟩, where lift-idᴿ
  -- finishes under the coercion.  A base rule subsumed by its own
  -- coercion image is redundant; it still holds by refl for user code.
  lift-id     : (⟨ idᴿ {S} ⟩ ↑ˢ s) ≡ ⟨ idᴿ ⟩

  -- ══ η: lemmas only ═══════════════════════════════════════════════
  η-idᴿ  : (zero {s = s} {S = S}) ∙ᴿ (wkᴿ s) ≡ idᴿ
  η-lawᴿ : (zero [ ξ ]ᴿ) ∙ᴿ (wkᴿ s ⨟ᴿ ξ) ≡ ξ
  η-id   : (`_ zero) ∙ˢ (wkˢ s) ≡ idˢ {S = s ∷ S}
  η-law  : (zero [ σ ]ˢ) ∙ˢ (wkˢ s ⨟ σ) ≡ σ
  def-↑ᴿ : ξ ↑ᴿ s ≡ zero ∙ᴿ (ξ ⨟ᴿ wkᴿ s)
  def-↑ˢ  : σ ↑ˢ s ≡ (`_ zero) ∙ˢ (σ ⨟ wkˢ s)


  -- iterated lifting.  Unlike records, patterns force these to be
  -- REWRITE rules: without lift*-idᴿ the pair (right-idᴿ, instᴿ-let) is
  -- not joinable, because `e₂ [ idᴿ ↑ᴿ*[ b ] n ]ᴿ` is stuck for abstract n.
  lift*-idᴿ         : ∀ b n → (idᴿ {S} ↑ᴿ*[ b ] n) ≡ idᴿ
  lift*-dist-compᴿᴿ : ∀ b n → ((ξ₁ ↑ᴿ*[ b ] n) ⨟ᴿ (ξ₂ ↑ᴿ*[ b ] n)) ≡ ((ξ₁ ⨟ᴿ ξ₂) ↑ᴿ*[ b ] n)
  lift*-dist-compᴿˢ : ∀ b n {ξ : S₁ →ᴿ S₂} {σ : S₂ →ˢ S₃} →
    (⟨ ξ ↑ᴿ*[ b ] n ⟩ ⨟ (σ ↑ˢ*[ b ] n)) ≡ ((⟨ ξ ⟩ ⨟ σ) ↑ˢ*[ b ] n)
  lift*-dist-compˢᴿ : ∀ b n {σ : S₁ →ˢ S₂} {ξ : S₂ →ᴿ S₃} →
    ((σ ↑ˢ*[ b ] n) ⨟ ⟨ ξ ↑ᴿ*[ b ] n ⟩) ≡ ((σ ⨟ ⟨ ξ ⟩) ↑ˢ*[ b ] n)
  lift*-dist-compˢˢ : ∀ b n → ((σ₁ ↑ˢ*[ b ] n) ⨟ (σ₂ ↑ˢ*[ b ] n)) ≡ ((σ₁ ⨟ σ₂) ↑ˢ*[ b ] n)
  ⟨⟩-lift*          : ∀ b n → (⟨ ξ ⟩ ↑ˢ*[ b ] n) ≡ ⟨ ξ ↑ᴿ*[ b ] n ⟩
  -- the iterated completion companions.  One for each `-var` / `-⨟ᴿ` /
  -- `-⨟` companion of the single-lifting layer; each closes exactly the
  -- pair that its single-lifting counterpart closes, one level up.
  lift*-dist-compᴿᴿ-var : ∀ {S₁ S₂ S₃} (b : Sort) (n : ℕ) {s} {x : (ext* b n S₁) ∋ s}
    {ξ₁ : S₁ →ᴿ S₂} {ξ₂ : S₂ →ᴿ S₃} →
    (x [ (ξ₁ ↑ᴿ*[ b ] n) ]ᴿ) [ (ξ₂ ↑ᴿ*[ b ] n) ]ᴿ ≡ x [ ((ξ₁ ⨟ᴿ ξ₂) ↑ᴿ*[ b ] n) ]ᴿ
  lift*-dist-compᴿᴿ-⨟ᴿ : ∀ {S₁ S₂ S₃ S₄} (b : Sort) (n : ℕ) {ξ₁ : S₁ →ᴿ S₂} {ξ₂ : S₂ →ᴿ S₃}
    {ξ′ : (ext* b n S₃) →ᴿ S₄} →
    (ξ₁ ↑ᴿ*[ b ] n) ⨟ᴿ ((ξ₂ ↑ᴿ*[ b ] n) ⨟ᴿ ξ′) ≡ ((ξ₁ ⨟ᴿ ξ₂) ↑ᴿ*[ b ] n) ⨟ᴿ ξ′
  lift*-dist-compˢˢ-⨟ : ∀ {S₁ S₂ S₃} (b : Sort) (n : ℕ) {S₄} {σ₁ : S₁ →ˢ S₂} {σ₂ : S₂ →ˢ S₃}
    {τ : (ext* b n S₃) →ˢ S₄} →
    (σ₁ ↑ˢ*[ b ] n) ⨟ ((σ₂ ↑ˢ*[ b ] n) ⨟ τ) ≡ ((σ₁ ⨟ σ₂) ↑ˢ*[ b ] n) ⨟ τ
  lift*-dist-compᴿˢ-⨟ : ∀ {S₁ S₂ S₃} (b : Sort) (n : ℕ) {S₄} {ξ : S₁ →ᴿ S₂} {σ : S₂ →ˢ S₃}
    {τ : (ext* b n S₃) →ˢ S₄} →
    ⟨ ξ ↑ᴿ*[ b ] n ⟩ ⨟ ((σ ↑ˢ*[ b ] n) ⨟ τ) ≡ ((⟨ ξ ⟩ ⨟ σ) ↑ˢ*[ b ] n) ⨟ τ
  lift*-dist-compˢᴿ-⨟ : ∀ {S₁ S₂ S₃} (b : Sort) (n : ℕ) {S₄} {σ : S₁ →ˢ S₂} {ξ : S₂ →ᴿ S₃}
    {τ : (ext* b n S₃) →ˢ S₄} →
    (σ ↑ˢ*[ b ] n) ⨟ (⟨ ξ ↑ᴿ*[ b ] n ⟩ ⨟ τ) ≡ ((σ ⨟ ⟨ ξ ⟩) ↑ˢ*[ b ] n) ⨟ τ
  lift*-dist-compᴿˢ-var : ∀ {S₁ S₂ S₃} (b : Sort) (n : ℕ) {s} {x : (ext* b n S₁) ∋ s}
    {ξ : S₁ →ᴿ S₂} {σ : S₂ →ˢ S₃} →
    (x [ (ξ ↑ᴿ*[ b ] n) ]ᴿ) [ (σ ↑ˢ*[ b ] n) ]ˢ ≡ x [ ((⟨ ξ ⟩ ⨟ σ) ↑ˢ*[ b ] n) ]ˢ
  ⟨⟩-comp-⨟-lift*-dist-compᴿᴿ : ∀ {S₁ S₂ S₃} (b : Sort) (n : ℕ) {S₄} {ξ₁ : S₁ →ᴿ S₂} {ξ₂ : S₂ →ᴿ S₃}
    {τ : (ext* b n S₃) →ˢ S₄} →
    ⟨ ξ₁ ↑ᴿ*[ b ] n ⟩ ⨟ (⟨ ξ₂ ↑ᴿ*[ b ] n ⟩ ⨟ τ) ≡ ⟨ (ξ₁ ⨟ᴿ ξ₂) ↑ᴿ*[ b ] n ⟩ ⨟ τ
  lift*-dist-compᴿˢ-⨟-var : ∀ {S₁ S₂ S₃} (b : Sort) (n : ℕ) {S₄} {s} {x : (ext* b n S₁) ∋ s}
    {ξ : S₁ →ᴿ S₂} {σ : S₂ →ˢ S₃} {τ : (ext* b n S₃) →ˢ S₄} →
    (x [ (ξ ↑ᴿ*[ b ] n) ]ᴿ) [ ((σ ↑ˢ*[ b ] n) ⨟ τ) ]ˢ ≡ x [ (((⟨ ξ ⟩ ⨟ σ) ↑ˢ*[ b ] n) ⨟ τ) ]ˢ
  ⟨⟩-split*-tail : ∀ {S₁ S₂ S₃} (b : Sort) (n : ℕ) {S₄} {σ : S₁ →ˢ S₂} {ξ : S₂ →ᴿ S₃}
    {ξ′ : (ext* b n S₃) →ᴿ S₄} →
    (σ ↑ˢ*[ b ] n) ⨟ ⟨ (ξ ↑ᴿ*[ b ] n) ⨟ᴿ ξ′ ⟩ ≡ ((σ ⨟ ⟨ ξ ⟩) ↑ˢ*[ b ] n) ⨟ ⟨ ξ′ ⟩
  -- ── proofs ────────────────────────────────────────────────────────

  def-wkᴿ     = refl
  def-∙ᴿ-zero = refl
  def-∙ᴿ-suc  = refl
  def-↑ᴿ-zero = refl
  def-↑ᴿ-suc  = refl

  instᴿ-var = refl
  instᴿ-Top      = refl
  instᴿ-_⇒_      = refl
  instᴿ-∀[<:_]_  = refl
  instᴿ-RcdT     = refl
  instᴿ-nilT     = refl
  instᴿ-consT    = refl
  instᴿ-λx[_]_   = refl
  instᴿ-Λα[<:_]_ = refl
  instᴿ-_·_      = refl
  instᴿ-_•_      = refl
  instᴿ-RcdE     = refl
  instᴿ-_#_      = refl
  instᴿ-nilE     = refl
  instᴿ-consE    = refl

  assocᴿ {ξ₁ = ξ₁} {ξ₂ = ξ₂} {ξ₃ = ξ₃} = ext λ x → sym (compositionalityᴿᴿ-var (ξ₁ _ x) {ξ₁ = ξ₂} {ξ₂ = ξ₃})
  comp-idₗᴿ = refl
  comp-idᵣᴿ = ext λ x → right-idᴿ _
  distᴿ     = ext λ { zero → refl ; (suc x) → refl }
  interactᴿ = refl

  lift-idᴿ     = ext λ { zero → refl ; (suc x) → refl }
  lift-dist-compᴿᴿ = ext λ { zero → refl ; (suc x) → refl }
  lift-wkᴿ     = refl
  lift-consᴿ   = ext λ { zero → refl ; (suc x) → refl }

  right-idᴿ {m = V} x = refl
  right-idᴿ (`_ x)   = refl
  right-idᴿ Top                         = refl
  right-idᴿ (_⇒_ type0 type1)           = cong2 _⇒_ (right-idᴿ type0) (right-idᴿ type1)
  right-idᴿ (∀[<:_]_ type0 type1)       = cong2 ∀[<:_]_ (right-idᴿ type0) (trans (cong (type1 [_]ᴿ) lift-idᴿ) (right-idᴿ type1))
  right-idᴿ (RcdT rtype0)               = cong1 RcdT (right-idᴿ rtype0)
  right-idᴿ nilT                        = refl
  right-idᴿ (consT label0 type0 rtype0) = cong3 consT refl (right-idᴿ type0) (right-idᴿ rtype0)
  right-idᴿ (λx[_]_ type0 expr0)        = cong2 λx[_]_ (right-idᴿ type0) (trans (cong (expr0 [_]ᴿ) lift-idᴿ) (right-idᴿ expr0))
  right-idᴿ (Λα[<:_]_ type0 expr0)      = cong2 Λα[<:_]_ (right-idᴿ type0) (trans (cong (expr0 [_]ᴿ) lift-idᴿ) (right-idᴿ expr0))
  right-idᴿ (_·_ expr0 expr1)           = cong2 _·_ (right-idᴿ expr0) (right-idᴿ expr1)
  right-idᴿ (_•_ expr0 type0)           = cong2 _•_ (right-idᴿ expr0) (right-idᴿ type0)
  right-idᴿ (RcdE rexpr0)               = cong1 RcdE (right-idᴿ rexpr0)
  right-idᴿ (_#_ expr0 label0)          = cong2 _#_ (right-idᴿ expr0) refl
  right-idᴿ nilE                        = refl
  right-idᴿ (consE label0 expr0 rexpr0) = cong3 consE refl (right-idᴿ expr0) (right-idᴿ rexpr0)

  compositionalityᴿᴿ-var x           = refl
  compositionalityᴿᴿ (`_ x) {ξ₁ = ξ₁} {ξ₂ = ξ₂} = cong `_ (sym (compositionalityᴿᴿ-var x {ξ₁ = ξ₁} {ξ₂ = ξ₂}))
  compositionalityᴿᴿ Top                         = refl
  compositionalityᴿᴿ (_⇒_ type0 type1)           = cong2 _⇒_ (compositionalityᴿᴿ type0) (compositionalityᴿᴿ type1)
  compositionalityᴿᴿ (∀[<:_]_ type0 type1)       = cong2 ∀[<:_]_ (compositionalityᴿᴿ type0) (trans (compositionalityᴿᴿ type1) (cong (type1 [_]ᴿ) lift-dist-compᴿᴿ))
  compositionalityᴿᴿ (RcdT rtype0)               = cong1 RcdT (compositionalityᴿᴿ rtype0)
  compositionalityᴿᴿ nilT                        = refl
  compositionalityᴿᴿ (consT label0 type0 rtype0) = cong3 consT refl (compositionalityᴿᴿ type0) (compositionalityᴿᴿ rtype0)
  compositionalityᴿᴿ (λx[_]_ type0 expr0)        = cong2 λx[_]_ (compositionalityᴿᴿ type0) (trans (compositionalityᴿᴿ expr0) (cong (expr0 [_]ᴿ) lift-dist-compᴿᴿ))
  compositionalityᴿᴿ (Λα[<:_]_ type0 expr0)      = cong2 Λα[<:_]_ (compositionalityᴿᴿ type0) (trans (compositionalityᴿᴿ expr0) (cong (expr0 [_]ᴿ) lift-dist-compᴿᴿ))
  compositionalityᴿᴿ (_·_ expr0 expr1)           = cong2 _·_ (compositionalityᴿᴿ expr0) (compositionalityᴿᴿ expr1)
  compositionalityᴿᴿ (_•_ expr0 type0)           = cong2 _•_ (compositionalityᴿᴿ expr0) (compositionalityᴿᴿ type0)
  compositionalityᴿᴿ (RcdE rexpr0)               = cong1 RcdE (compositionalityᴿᴿ rexpr0)
  compositionalityᴿᴿ (_#_ expr0 label0)          = cong2 _#_ (compositionalityᴿᴿ expr0) refl
  compositionalityᴿᴿ nilE                        = refl
  compositionalityᴿᴿ (consE label0 expr0 rexpr0) = cong3 consE refl (compositionalityᴿᴿ expr0) (compositionalityᴿᴿ rexpr0)

  lift-dist-compᴿᴿ-var {x = zero}  = refl
  lift-dist-compᴿᴿ-var {x = suc x} = refl
  interactᴿ-⨟ᴿ    = refl
  lift-wkᴿ-⨟ᴿ {s = s} {ξ = ξ} {ξ′ = ξ′} =
    trans (sym (assocᴿ {ξ₁ = wkᴿ s} {ξ₂ = ξ ↑ᴿ s} {ξ₃ = ξ′}))
          (trans (cong (_⨟ᴿ ξ′) (lift-wkᴿ {s = s} {ξ = ξ}))
                 (assocᴿ {ξ₁ = ξ} {ξ₂ = wkᴿ s} {ξ₃ = ξ′}))
  lift-dist-compᴿᴿ-⨟ᴿ {ξ₁ = ξ₁} {ξ₂ = ξ₂} {ξ′ = ξ′} =
    trans (sym (assocᴿ {ξ₁ = ξ₁ ↑ᴿ _} {ξ₂ = ξ₂ ↑ᴿ _} {ξ₃ = ξ′}))
          (cong (_⨟ᴿ ξ′) (lift-dist-compᴿᴿ {ξ₁ = ξ₁} {ξ₂ = ξ₂}))

  coincidence-var = refl
  def-∙ˢ-zero  = refl
  def-∙ˢ-suc   = refl
  def-↑ˢ-zero  = refl
  def-↑ˢ-suc {x = x} {σ = σ} {s = s} = sym (coincidence (σ _ x) (wkᴿ s))
  compositionalityᴿˢ-⨟-var     = refl
  def-↑ˢ-zero-⨟ = refl
  def-↑ˢ-suc-⨟ {x = x} {σ = σ} {s = s} {τ = τ} =
    trans (compositionalityᴿˢ (σ _ x)) (cong ((σ _ x) [_]ˢ) (ext λ y → refl))
  interact  = refl
  comp-idₗ  = refl
  comp-idᵣ {σ = σ} = ext λ y → trans (coincidence (σ _ y) idᴿ) (right-idᴿ (σ _ y))
  lift-wk {s = s} {σ = σ} = ext λ y → sym (coincidence (σ _ y) (wkᴿ s))
  lift-id   = ext λ { zero → refl ; (suc x) → refl }
  lift-wk-⨟ {s = s} {σ = σ} {τ = τ} =
    trans (sym (assoc {σ₁ = ⟨ wkᴿ s ⟩} {σ₂ = σ ↑ˢ s} {σ₃ = τ}))
          (trans (cong (_⨟ τ) (lift-wk {s = s} {σ = σ}))
                 (assoc {σ₁ = σ} {σ₂ = ⟨ wkᴿ s ⟩} {σ₃ = τ}))
  lift-dist-compˢˢ-⨟ {σ₁ = σ₁} {s = s} {σ₂ = σ₂} {τ = τ} =
    trans (sym (assoc {σ₁ = σ₁ ↑ˢ s} {σ₂ = σ₂ ↑ˢ s} {σ₃ = τ}))
          (cong (_⨟ τ) (lift-dist-compˢˢ {σ₁ = σ₁} {s = s} {σ₂ = σ₂}))

  inst-var = refl
  inst-Top      = refl
  inst-_⇒_      = refl
  inst-∀[<:_]_  = refl
  inst-RcdT     = refl
  inst-nilT     = refl
  inst-consT    = refl
  inst-λx[_]_   = refl
  inst-Λα[<:_]_ = refl
  inst-_·_      = refl
  inst-_•_      = refl
  inst-RcdE     = refl
  inst-_#_      = refl
  inst-nilE     = refl
  inst-consE    = refl

  lift-dist-compᴿˢ : ∀ {ξ : S₁ →ᴿ S₂} {σ : S₂ →ˢ S₃} →
    (⟨ ξ ↑ᴿ s ⟩ ⨟ (σ ↑ˢ s)) ≡ ((⟨ ξ ⟩ ⨟ σ) ↑ˢ s)
  lift-dist-compᴿˢ = ext λ { zero → refl ; (suc x) → refl }

  compositionalityᴿˢ (`_ x) = refl
  compositionalityᴿˢ Top                         = refl
  compositionalityᴿˢ (_⇒_ type0 type1)           = cong2 _⇒_ (compositionalityᴿˢ type0) (compositionalityᴿˢ type1)
  compositionalityᴿˢ (∀[<:_]_ type0 type1)       = cong2 ∀[<:_]_ (compositionalityᴿˢ type0) (trans (compositionalityᴿˢ type1) (cong (type1 [_]ˢ) lift-dist-compᴿˢ))
  compositionalityᴿˢ (RcdT rtype0)               = cong1 RcdT (compositionalityᴿˢ rtype0)
  compositionalityᴿˢ nilT                        = refl
  compositionalityᴿˢ (consT label0 type0 rtype0) = cong3 consT refl (compositionalityᴿˢ type0) (compositionalityᴿˢ rtype0)
  compositionalityᴿˢ (λx[_]_ type0 expr0)        = cong2 λx[_]_ (compositionalityᴿˢ type0) (trans (compositionalityᴿˢ expr0) (cong (expr0 [_]ˢ) lift-dist-compᴿˢ))
  compositionalityᴿˢ (Λα[<:_]_ type0 expr0)      = cong2 Λα[<:_]_ (compositionalityᴿˢ type0) (trans (compositionalityᴿˢ expr0) (cong (expr0 [_]ˢ) lift-dist-compᴿˢ))
  compositionalityᴿˢ (_·_ expr0 expr1)           = cong2 _·_ (compositionalityᴿˢ expr0) (compositionalityᴿˢ expr1)
  compositionalityᴿˢ (_•_ expr0 type0)           = cong2 _•_ (compositionalityᴿˢ expr0) (compositionalityᴿˢ type0)
  compositionalityᴿˢ (RcdE rexpr0)               = cong1 RcdE (compositionalityᴿˢ rexpr0)
  compositionalityᴿˢ (_#_ expr0 label0)          = cong2 _#_ (compositionalityᴿˢ expr0) refl
  compositionalityᴿˢ nilE                        = refl
  compositionalityᴿˢ (consE label0 expr0 rexpr0) = cong3 consE refl (compositionalityᴿˢ expr0) (compositionalityᴿˢ rexpr0)

  lift-dist-compˢᴿ : ∀ {σ : S₁ →ˢ S₂} {ξ : S₂ →ᴿ S₃} →
    ((σ ↑ˢ s) ⨟ ⟨ ξ ↑ᴿ s ⟩) ≡ ((σ ⨟ ⟨ ξ ⟩) ↑ˢ s)
  lift-dist-compˢᴿ {s = s} {σ = σ} {ξ = ξ} = ext λ where
    zero    → refl
    (suc x) → let t = σ _ x in
      trans (coincidence (t [ wkᴿ s ]ᴿ) (ξ ↑ᴿ s))
      (trans (compositionalityᴿᴿ t {ξ₁ = wkᴿ s} {ξ₂ = ξ ↑ᴿ s})
      (trans (cong (t [_]ᴿ) (lift-wkᴿ {s = s} {ξ = ξ}))
      (trans (sym (compositionalityᴿᴿ t {ξ₁ = ξ} {ξ₂ = wkᴿ s}))
             (cong (_[ wkᴿ s ]ᴿ) (sym (coincidence t ξ))))))

  compositionalityˢᴿ {m = V} x {σ₁ = σ₁} {ξ₂ = ξ₂} = sym (coincidence (σ₁ _ x) ξ₂)
  compositionalityˢᴿ (`_ x) {σ₁ = σ₁} {ξ₂ = ξ₂} = sym (coincidence (σ₁ _ x) ξ₂)
  compositionalityˢᴿ Top                         = refl
  compositionalityˢᴿ (_⇒_ type0 type1)           = cong2 _⇒_ (compositionalityˢᴿ type0) (compositionalityˢᴿ type1)
  compositionalityˢᴿ (∀[<:_]_ type0 type1)       = cong2 ∀[<:_]_ (compositionalityˢᴿ type0) (trans (compositionalityˢᴿ type1) (cong (type1 [_]ˢ) lift-dist-compˢᴿ))
  compositionalityˢᴿ (RcdT rtype0)               = cong1 RcdT (compositionalityˢᴿ rtype0)
  compositionalityˢᴿ nilT                        = refl
  compositionalityˢᴿ (consT label0 type0 rtype0) = cong3 consT refl (compositionalityˢᴿ type0) (compositionalityˢᴿ rtype0)
  compositionalityˢᴿ (λx[_]_ type0 expr0)        = cong2 λx[_]_ (compositionalityˢᴿ type0) (trans (compositionalityˢᴿ expr0) (cong (expr0 [_]ˢ) lift-dist-compˢᴿ))
  compositionalityˢᴿ (Λα[<:_]_ type0 expr0)      = cong2 Λα[<:_]_ (compositionalityˢᴿ type0) (trans (compositionalityˢᴿ expr0) (cong (expr0 [_]ˢ) lift-dist-compˢᴿ))
  compositionalityˢᴿ (_·_ expr0 expr1)           = cong2 _·_ (compositionalityˢᴿ expr0) (compositionalityˢᴿ expr1)
  compositionalityˢᴿ (_•_ expr0 type0)           = cong2 _•_ (compositionalityˢᴿ expr0) (compositionalityˢᴿ type0)
  compositionalityˢᴿ (RcdE rexpr0)               = cong1 RcdE (compositionalityˢᴿ rexpr0)
  compositionalityˢᴿ (_#_ expr0 label0)          = cong2 _#_ (compositionalityˢᴿ expr0) refl
  compositionalityˢᴿ nilE                        = refl
  compositionalityˢᴿ (consE label0 expr0 rexpr0) = cong3 consE refl (compositionalityˢᴿ expr0) (compositionalityˢᴿ rexpr0)

  lift-dist-compˢˢ {σ₁ = σ₁} {s = s} {σ₂ = σ₂} = ext λ where
    zero    → refl
    (suc x) → let t = σ₁ _ x in
      trans (compositionalityᴿˢ t)
      (trans (cong (t [_]ˢ) (ext λ y → sym (coincidence (σ₂ _ y) (wkᴿ s))))
             (sym (compositionalityˢᴿ t)))

  compositionalityˢˢ {m = V} x = refl
  compositionalityˢˢ (`_ x)   = refl
  compositionalityˢˢ Top                         = refl
  compositionalityˢˢ (_⇒_ type0 type1)           = cong2 _⇒_ (compositionalityˢˢ type0) (compositionalityˢˢ type1)
  compositionalityˢˢ (∀[<:_]_ type0 type1)       = cong2 ∀[<:_]_ (compositionalityˢˢ type0) (trans (compositionalityˢˢ type1) (cong (type1 [_]ˢ) lift-dist-compˢˢ))
  compositionalityˢˢ (RcdT rtype0)               = cong1 RcdT (compositionalityˢˢ rtype0)
  compositionalityˢˢ nilT                        = refl
  compositionalityˢˢ (consT label0 type0 rtype0) = cong3 consT refl (compositionalityˢˢ type0) (compositionalityˢˢ rtype0)
  compositionalityˢˢ (λx[_]_ type0 expr0)        = cong2 λx[_]_ (compositionalityˢˢ type0) (trans (compositionalityˢˢ expr0) (cong (expr0 [_]ˢ) lift-dist-compˢˢ))
  compositionalityˢˢ (Λα[<:_]_ type0 expr0)      = cong2 Λα[<:_]_ (compositionalityˢˢ type0) (trans (compositionalityˢˢ expr0) (cong (expr0 [_]ˢ) lift-dist-compˢˢ))
  compositionalityˢˢ (_·_ expr0 expr1)           = cong2 _·_ (compositionalityˢˢ expr0) (compositionalityˢˢ expr1)
  compositionalityˢˢ (_•_ expr0 type0)           = cong2 _•_ (compositionalityˢˢ expr0) (compositionalityˢˢ type0)
  compositionalityˢˢ (RcdE rexpr0)               = cong1 RcdE (compositionalityˢˢ rexpr0)
  compositionalityˢˢ (_#_ expr0 label0)          = cong2 _#_ (compositionalityˢˢ expr0) refl
  compositionalityˢˢ nilE                        = refl
  compositionalityˢˢ (consE label0 expr0 rexpr0) = cong3 consE refl (compositionalityˢˢ expr0) (compositionalityˢˢ rexpr0)

  assoc {σ₁ = σ₁} {σ₂ = σ₂} {σ₃ = σ₃} = ext λ x → compositionalityˢˢ (σ₁ _ x) {σ₁ = σ₂} {σ₂ = σ₃}
  dist            = ext λ { zero → refl ; (suc x) → refl }
  lift-cons {σ = σ} {t = t} {τ = τ} = ext λ where
    zero    → refl
    (suc x) → trans (compositionalityᴿˢ (σ _ x)) (cong ((σ _ x) [_]ˢ) (ext λ y → refl))

  coincidence (`_ x) ξ = refl
  coincidence Top ξ                         = refl
  coincidence (_⇒_ type0 type1) ξ           = cong2 _⇒_ (coincidence type0 ξ) (coincidence type1 ξ)
  coincidence (∀[<:_]_ type0 type1) ξ       = cong2 ∀[<:_]_ (coincidence type0 ξ) (trans (cong (type1 [_]ˢ) (⟨⟩-lift {ξ = ξ})) (coincidence type1 (ξ ↑ᴿ type)))
  coincidence (RcdT rtype0) ξ               = cong1 RcdT (coincidence rtype0 ξ)
  coincidence nilT ξ                        = refl
  coincidence (consT label0 type0 rtype0) ξ = cong3 consT refl (coincidence type0 ξ) (coincidence rtype0 ξ)
  coincidence (λx[_]_ type0 expr0) ξ        = cong2 λx[_]_ (coincidence type0 ξ) (trans (cong (expr0 [_]ˢ) (⟨⟩-lift {ξ = ξ})) (coincidence expr0 (ξ ↑ᴿ expr)))
  coincidence (Λα[<:_]_ type0 expr0) ξ      = cong2 Λα[<:_]_ (coincidence type0 ξ) (trans (cong (expr0 [_]ˢ) (⟨⟩-lift {ξ = ξ})) (coincidence expr0 (ξ ↑ᴿ type)))
  coincidence (_·_ expr0 expr1) ξ           = cong2 _·_ (coincidence expr0 ξ) (coincidence expr1 ξ)
  coincidence (_•_ expr0 type0) ξ           = cong2 _•_ (coincidence expr0 ξ) (coincidence type0 ξ)
  coincidence (RcdE rexpr0) ξ               = cong1 RcdE (coincidence rexpr0 ξ)
  coincidence (_#_ expr0 label0) ξ          = cong2 _#_ (coincidence expr0 ξ) refl
  coincidence nilE ξ                        = refl
  coincidence (consE label0 expr0 rexpr0) ξ = cong3 consE refl (coincidence expr0 ξ) (coincidence rexpr0 ξ)

  lift-dist-compᴿˢ-⨟ {s = s} {ξ = ξ} {σ = σ} {τ = τ} =
    trans (sym (assoc {σ₁ = ⟨ ξ ↑ᴿ s ⟩} {σ₂ = σ ↑ˢ s} {σ₃ = τ}))
          (cong (_⨟ τ) (lift-dist-compᴿˢ {s = s} {ξ = ξ} {σ = σ}))
  lift-dist-compˢᴿ-⨟ {s = s} {σ = σ} {ξ = ξ} {τ = τ} =
    trans (sym (assoc {σ₁ = σ ↑ˢ s} {σ₂ = ⟨ ξ ↑ᴿ s ⟩} {σ₃ = τ}))
          (cong (_⨟ τ) (lift-dist-compˢᴿ {s = s} {σ = σ} {ξ = ξ}))
  lift-dist-compᴿˢ-var {x = zero}  = refl
  lift-dist-compᴿˢ-var {x = suc x} = refl
  lift-dist-compᴿˢ-⨟-var {x = zero}  = refl
  lift-dist-compᴿˢ-⨟-var {x = suc x} = refl
  ⟨⟩-comp-⨟-lift-wkᴿ    = ext λ x → refl
  ⟨⟩-comp-⨟-interactᴿ    = ext λ x → refl
  ⟨⟩-comp-⨟-lift-dist-compᴿᴿ  = ext λ { zero → refl ; (suc x) → refl }
  ⟨⟩-split-tail {s = s} {σ = σ} {ξ = ξ} {ξ′ = ξ′} = ext λ where
    zero    → refl
    (suc x) → let t = σ _ x in begin
        (t [ wkᴿ s ]ᴿ) [ ⟨ (ξ ↑ᴿ s) ⨟ᴿ ξ′ ⟩ ]ˢ
      ≡⟨ coincidence (t [ wkᴿ s ]ᴿ) ((ξ ↑ᴿ s) ⨟ᴿ ξ′) ⟩
        (t [ wkᴿ s ]ᴿ) [ ((ξ ↑ᴿ s) ⨟ᴿ ξ′) ]ᴿ
      ≡⟨ compositionalityᴿᴿ t {ξ₁ = wkᴿ s} {ξ₂ = (ξ ↑ᴿ s) ⨟ᴿ ξ′} ⟩
        t [ (wkᴿ s ⨟ᴿ ((ξ ↑ᴿ s) ⨟ᴿ ξ′)) ]ᴿ
      ≡⟨ cong (t [_]ᴿ) (lift-wkᴿ-⨟ᴿ {s = s} {ξ = ξ} {ξ′ = ξ′}) ⟩
        t [ (ξ ⨟ᴿ (wkᴿ s ⨟ᴿ ξ′)) ]ᴿ
      ≡⟨ sym (compositionalityᴿᴿ t {ξ₁ = ξ} {ξ₂ = wkᴿ s ⨟ᴿ ξ′}) ⟩
        (t [ ξ ]ᴿ) [ (wkᴿ s ⨟ᴿ ξ′) ]ᴿ
      ≡⟨ cong (_[ (wkᴿ s ⨟ᴿ ξ′) ]ᴿ) (sym (coincidence t ξ)) ⟩
        (t [ ⟨ ξ ⟩ ]ˢ) [ (wkᴿ s ⨟ᴿ ξ′) ]ᴿ
      ≡⟨ sym (compositionalityᴿᴿ (t [ ⟨ ξ ⟩ ]ˢ) {ξ₁ = wkᴿ s} {ξ₂ = ξ′}) ⟩
        ((t [ ⟨ ξ ⟩ ]ˢ) [ wkᴿ s ]ᴿ) [ ξ′ ]ᴿ
      ≡⟨ sym (coincidence ((t [ ⟨ ξ ⟩ ]ˢ) [ wkᴿ s ]ᴿ) ξ′) ⟩
        ((t [ ⟨ ξ ⟩ ]ˢ) [ wkᴿ s ]ᴿ) [ ⟨ ξ′ ⟩ ]ˢ
      ∎
  ⟨⟩-lift-cons  = ext λ { zero → refl ; (suc x) → refl }
  ⟨⟩-lift-cons-var {x = zero}  = refl
  ⟨⟩-lift-cons-var {x = suc x} = refl
  ⟨⟩-comp    = ext λ x → refl
  ⟨⟩-split-⨟ = ext λ x → refl
  ⟨⟩-lift    = ext λ { zero → refl ; (suc x) → refl }

  η-idᴿ  = ext λ { zero → refl ; (suc x) → refl }
  η-lawᴿ = ext λ { zero → refl ; (suc x) → refl }
  η-id   = ext λ { zero → refl ; (suc x) → refl }
  η-law  = ext λ { zero → refl ; (suc x) → refl }
  def-↑ᴿ = ext λ { zero → refl ; (suc x) → refl }
  def-↑ˢ {σ = σ} {s = s} = ext λ { zero → refl ; (suc x) → sym (coincidence (σ _ x) (wkᴿ s)) }

  lift*-idᴿ b zero    = refl
  lift*-idᴿ b (suc n) = trans (cong (_↑ᴿ b) (lift*-idᴿ b n)) lift-idᴿ
  lift*-dist-compᴿᴿ b zero = refl
  lift*-dist-compᴿᴿ {ξ₁ = ξ₁} {ξ₂ = ξ₂} b (suc n) =
    trans (lift-dist-compᴿᴿ {ξ₁ = ξ₁ ↑ᴿ*[ b ] n} {s = b} {ξ₂ = ξ₂ ↑ᴿ*[ b ] n})
          (cong (_↑ᴿ b) (lift*-dist-compᴿᴿ b n))
  lift*-dist-compᴿˢ b zero = refl
  lift*-dist-compᴿˢ b (suc n) {ξ = ξ} {σ = σ} =
    trans (lift-dist-compᴿˢ {s = b} {ξ = ξ ↑ᴿ*[ b ] n} {σ = σ ↑ˢ*[ b ] n})
          (cong (_↑ˢ b) (lift*-dist-compᴿˢ b n))
  lift*-dist-compˢᴿ b zero = refl
  lift*-dist-compˢᴿ b (suc n) {σ = σ} {ξ = ξ} =
    trans (lift-dist-compˢᴿ {s = b} {σ = σ ↑ˢ*[ b ] n} {ξ = ξ ↑ᴿ*[ b ] n})
          (cong (_↑ˢ b) (lift*-dist-compˢᴿ b n))
  lift*-dist-compˢˢ b zero = refl
  lift*-dist-compˢˢ {σ₁ = σ₁} {σ₂ = σ₂} b (suc n) =
    trans (lift-dist-compˢˢ {σ₁ = σ₁ ↑ˢ*[ b ] n} {s = b} {σ₂ = σ₂ ↑ˢ*[ b ] n})
          (cong (_↑ˢ b) (lift*-dist-compˢˢ b n))
  ⟨⟩-lift* b zero    = refl
  ⟨⟩-lift* {ξ = ξ} b (suc n) =
    trans (cong (_↑ˢ b) (⟨⟩-lift* b n)) (⟨⟩-lift {ξ = ξ ↑ᴿ*[ b ] n} {s = b})

  lift*-dist-compᴿᴿ-var b zero = refl
  lift*-dist-compᴿᴿ-var b (suc n) {x = x} {ξ₁ = ξ₁} {ξ₂ = ξ₂} =
    trans (lift-dist-compᴿᴿ-var {x = x} {ξ₁ = ξ₁ ↑ᴿ*[ b ] n} {ξ₂ = ξ₂ ↑ᴿ*[ b ] n})
          (cong (λ z → x [ (z ↑ᴿ b) ]ᴿ) (lift*-dist-compᴿᴿ b n))
  lift*-dist-compᴿᴿ-⨟ᴿ b zero {ξ₁ = ξ₁} {ξ₂ = ξ₂} {ξ′ = ξ′} =
    sym (assocᴿ {ξ₁ = ξ₁} {ξ₂ = ξ₂} {ξ₃ = ξ′})
  lift*-dist-compᴿᴿ-⨟ᴿ b (suc n) {ξ₁ = ξ₁} {ξ₂ = ξ₂} {ξ′ = ξ′} =
    trans (lift-dist-compᴿᴿ-⨟ᴿ {ξ₁ = ξ₁ ↑ᴿ*[ b ] n} {ξ₂ = ξ₂ ↑ᴿ*[ b ] n} {ξ′ = ξ′})
          (cong (λ z → (z ↑ᴿ b) ⨟ᴿ ξ′) (lift*-dist-compᴿᴿ b n))
  lift*-dist-compˢˢ-⨟ b zero {σ₁ = σ₁} {σ₂ = σ₂} {τ = τ} =
    sym (assoc {σ₁ = σ₁} {σ₂ = σ₂} {σ₃ = τ})
  lift*-dist-compˢˢ-⨟ b (suc n) {σ₁ = σ₁} {σ₂ = σ₂} {τ = τ} =
    trans (lift-dist-compˢˢ-⨟ {σ₁ = σ₁ ↑ˢ*[ b ] n} {σ₂ = σ₂ ↑ˢ*[ b ] n} {τ = τ})
          (cong (λ z → (z ↑ˢ b) ⨟ τ) (lift*-dist-compˢˢ b n))
  lift*-dist-compᴿˢ-⨟ b zero {ξ = ξ} {σ = σ} {τ = τ} =
    sym (assoc {σ₁ = ⟨ ξ ⟩} {σ₂ = σ} {σ₃ = τ})
  lift*-dist-compᴿˢ-⨟ b (suc n) {ξ = ξ} {σ = σ} {τ = τ} =
    trans (lift-dist-compᴿˢ-⨟ {s = b} {ξ = ξ ↑ᴿ*[ b ] n} {σ = σ ↑ˢ*[ b ] n} {τ = τ})
          (cong (λ z → (z ↑ˢ b) ⨟ τ) (lift*-dist-compᴿˢ b n))
  lift*-dist-compˢᴿ-⨟ b zero {σ = σ} {ξ = ξ} {τ = τ} =
    sym (assoc {σ₁ = σ} {σ₂ = ⟨ ξ ⟩} {σ₃ = τ})
  lift*-dist-compˢᴿ-⨟ b (suc n) {σ = σ} {ξ = ξ} {τ = τ} =
    trans (lift-dist-compˢᴿ-⨟ {s = b} {σ = σ ↑ˢ*[ b ] n} {ξ = ξ ↑ᴿ*[ b ] n} {τ = τ})
          (cong (λ z → (z ↑ˢ b) ⨟ τ) (lift*-dist-compˢᴿ b n))
  lift*-dist-compᴿˢ-var b zero {x = x} {ξ = ξ} {σ = σ} = sym (compositionalityᴿˢ-⨟-var {x = x} {ξ = ξ} {σ = σ})
  lift*-dist-compᴿˢ-var b (suc n) {x = x} {ξ = ξ} {σ = σ} =
    trans (lift-dist-compᴿˢ-var {x = x} {ξ = ξ ↑ᴿ*[ b ] n} {σ = σ ↑ˢ*[ b ] n})
          (cong (λ z → x [ (z ↑ˢ b) ]ˢ) (lift*-dist-compᴿˢ b n))
  ⟨⟩-comp-⨟-lift*-dist-compᴿᴿ b zero {ξ₁ = ξ₁} {ξ₂ = ξ₂} {τ = τ} =
    sym (⟨⟩-split-⨟ {ξ₁ = ξ₁} {ξ₂ = ξ₂} {σ = τ})
  ⟨⟩-comp-⨟-lift*-dist-compᴿᴿ b (suc n) {ξ₁ = ξ₁} {ξ₂ = ξ₂} {τ = τ} =
    trans (⟨⟩-comp-⨟-lift-dist-compᴿᴿ {ξ₁ = ξ₁ ↑ᴿ*[ b ] n} {ξ₂ = ξ₂ ↑ᴿ*[ b ] n} {τ = τ})
          (cong (λ z → ⟨ z ↑ᴿ b ⟩ ⨟ τ) (lift*-dist-compᴿᴿ b n))

  lift*-dist-compᴿˢ-⨟-var b zero {x = x} {ξ = ξ} {σ = σ} {τ = τ} =
    trans (sym (compositionalityᴿˢ-⨟-var {x = x} {ξ = ξ} {σ = σ ⨟ τ}))
          (cong (x [_]ˢ) (sym (assoc {σ₁ = ⟨ ξ ⟩} {σ₂ = σ} {σ₃ = τ})))
  lift*-dist-compᴿˢ-⨟-var b (suc n) {x = x} {ξ = ξ} {σ = σ} {τ = τ} =
    trans (lift-dist-compᴿˢ-⨟-var {x = x} {ξ = ξ ↑ᴿ*[ b ] n} {σ = σ ↑ˢ*[ b ] n} {τ = τ})
          (cong (λ z → x [ ((z ↑ˢ b) ⨟ τ) ]ˢ) (lift*-dist-compᴿˢ b n))
  ⟨⟩-split*-tail b zero {σ = σ} {ξ = ξ} {ξ′ = ξ′} =
    sym (trans (assoc {σ₁ = σ} {σ₂ = ⟨ ξ ⟩} {σ₃ = ⟨ ξ′ ⟩})
               (cong (σ ⨟_) (⟨⟩-comp {ξ₁ = ξ} {ξ₂ = ξ′})))
  ⟨⟩-split*-tail b (suc n) {σ = σ} {ξ = ξ} {ξ′ = ξ′} =
    trans (⟨⟩-split-tail {σ = σ ↑ˢ*[ b ] n} {ξ = ξ ↑ᴿ*[ b ] n} {ξ′ = ξ′})
          (cong (λ z → (z ↑ˢ b) ⨟ ⟨ ξ′ ⟩) (lift*-dist-compˢᴿ b n))

-- ═══ The completed two-world system ════════════════════════════════
--
-- The curated, locally confluent rule set:
-- 101 rules -- 56 signature-independent, 15 for the
-- iterated (variable-arity) lifting, 30 traversal rules (one instᴿ-*
-- and one inst-* per constructor, plus the variable case).

{-# REWRITE
  def-wkᴿ def-∙ᴿ-zero def-∙ᴿ-suc def-↑ᴿ-zero def-↑ᴿ-suc
  instᴿ-var instᴿ-Top instᴿ-_⇒_ instᴿ-∀[<:_]_ instᴿ-RcdT instᴿ-nilT
  instᴿ-consT instᴿ-λx[_]_ instᴿ-Λα[<:_]_ instᴿ-_·_ instᴿ-_•_ instᴿ-RcdE
  instᴿ-_#_ instᴿ-nilE instᴿ-consE
  assocᴿ comp-idₗᴿ comp-idᵣᴿ interactᴿ
  lift-idᴿ lift-dist-compᴿᴿ lift-wkᴿ
  right-idᴿ compositionalityᴿᴿ-var compositionalityᴿᴿ
  lift-dist-compᴿᴿ-var interactᴿ-⨟ᴿ lift-wkᴿ-⨟ᴿ lift-dist-compᴿᴿ-⨟ᴿ
  coincidence-var def-∙ˢ-zero def-∙ˢ-suc def-↑ˢ-zero def-↑ˢ-suc
  compositionalityᴿˢ-⨟-var def-↑ˢ-zero-⨟ def-↑ˢ-suc-⨟
  inst-var inst-Top inst-_⇒_ inst-∀[<:_]_ inst-RcdT inst-nilT inst-consT
  inst-λx[_]_ inst-Λα[<:_]_ inst-_·_ inst-_•_ inst-RcdE inst-_#_ inst-nilE
  inst-consE
  assoc dist interact comp-idₗ comp-idᵣ
  lift-wk lift-cons lift-dist-compˢˢ lift-wk-⨟ lift-dist-compˢˢ-⨟
  compositionalityˢˢ compositionalityᴿˢ compositionalityˢᴿ
  lift-dist-compᴿˢ lift-dist-compˢᴿ lift-dist-compᴿˢ-⨟ lift-dist-compˢᴿ-⨟
  lift-dist-compᴿˢ-var lift-dist-compᴿˢ-⨟-var ⟨⟩-lift-cons-var
  coincidence ⟨⟩-comp ⟨⟩-split-⨟ ⟨⟩-lift ⟨⟩-lift-cons
  ⟨⟩-comp-⨟-lift-wkᴿ ⟨⟩-comp-⨟-interactᴿ ⟨⟩-comp-⨟-lift-dist-compᴿᴿ ⟨⟩-split-tail
  lift*-idᴿ lift*-dist-compᴿᴿ lift*-dist-compᴿˢ lift*-dist-compˢᴿ
  lift*-dist-compˢˢ ⟨⟩-lift* lift*-dist-compᴿᴿ-var lift*-dist-compᴿᴿ-⨟ᴿ
  lift*-dist-compˢˢ-⨟ lift*-dist-compᴿˢ-⨟ lift*-dist-compˢᴿ-⨟
  lift*-dist-compᴿˢ-var ⟨⟩-comp-⨟-lift*-dist-compᴿᴿ lift*-dist-compᴿˢ-⨟-var
  ⟨⟩-split*-tail
#-}

-- ─── the derived operations ─────────────────────────────────────────
-- Neither is primitive and neither has rules of its own: weakening is a
-- renaming, single substitution is a cons onto the identity.  The
-- rewrite system computes through both without knowing they exist.

weaken : S ⊢ s → (s′ ∷ S) ⊢ s
weaken t = t [ wkᴿ _ ]ᴿ

_[_]₀ : (s′ ∷ S) ⊢ s → S ⊢ s′ → S ⊢ s
t [ t′ ]₀ = t [ (t′ ∙ˢ idˢ) ]ˢ
