#!/usr/bin/env bash

python3 agdatex.py -v -f -e SystemF.tex -r . \
  SystemF.agda

python3 agdatex.py -v -f -e examples.tex -r . \
  examples.agda

python3 agdatex.py -v -f -e STLC.tex -r . \
  STLC.agda
