#!/usr/bin/env bash

python3 ../../../agdatex/agdatex.py -v -f -e SystemF.tex -r . -x SystemF \
  SystemF.agda

python3 ../../../agdatex/agdatex.py -v -f -e examples.tex -r . -x examples \
  examples.agda