{-# OPTIONS --rewriting --local-confluence-check #-}

-- Martin-Löf type theory on the same machinery, as a test of whether the
-- construction carries over to a dependently typed object language.
--
-- ONE syntactic sort: types are terms.  The signature is Pi, lam, app, a
-- universe, and Nat with a natrec whose successor branch binds TWO
-- variables at once.  agdasubst.py accepted it unchanged and emitted the
-- 90 rules below, here in the vector model, so single-sortedness is the degenerate case of the
-- multi-sorted setting rather than a separate one.
--
-- Typing is extrinsic (Curry/PTS), definitional equality of types is
-- untyped conversion, and the universe is Type : Type.  The last is
-- logically inconsistent by Girard's paradox and type-safe regardless,
-- because neither preservation nor progress needs normalization.  It is
-- chosen so the universe costs nothing that would distract from the
-- measurement.
--
-- THE MEASUREMENT: subject reduction and progress are proved with ZERO
-- substitution lemmas applied by hand, the same count as systemf.agda.
-- That includes the two cases System F has no analogue of, the motive
-- commuting with a double lift and the two-variable simultaneous
-- ι-substitution of the natrec successor branch.
--
-- What MLTT adds is not substitution work but judgment plumbing:
-- stability of reduction and conversion under substitution (19 cases),
-- context conversion (13), and inversion through the conversion rule.
-- In MLTT, Π-injectivity is needed for SUBJECT REDUCTION itself, not
-- only for progress, because a lambda may reach its Π-type by
-- conversion.
--
-- NO assumptions at all.  Equality of substitutions is equality of data
-- in this model, so unlike mltt.agda this file does not need function
-- extensionality, and Church-Rosser for the untyped β/ι calculus is
-- PROVED below by Takahashi's method rather than assumed.  Π-injectivity
-- and no-confusion follow from it.
-- No postulates.  No holes.  No TERMINATING pragmas.
--
-- The positive controls are at the end: the confluence checker and the
-- refl-probes are demonstrably able to report failure.

module mltt-vec where

open import Relation.Binary.PropositionalEquality
open import Agda.Builtin.Equality.Rewrite
open import Data.List using (List; []; _∷_)
open import Data.Nat using (ℕ; zero; suc)
open import Axiom.Extensionality.Propositional using (Extensionality)
open import Relation.Binary.PropositionalEquality using (_≡_; refl; sym; cong; trans)
open import Data.List using (List; []; _∷_; drop)
open import Data.Product using (Σ; _×_; _,_; ∃; ∃-syntax; proj₁; proj₂)
open import Data.Empty using (⊥; ⊥-elim)
open import Data.Sum using (_⊎_; inj₁; inj₂)
open import Relation.Binary.PropositionalEquality using (_≡_; refl)
open import Data.Product using (_,_; ∃-syntax)
open import Data.Sum using (inj₁; inj₂)

-- ═══ THE GENERATED SUBSTITUTION CORE, VECTOR MODEL ═════════════════════════

-- Generated by gen/agdasubst.py --model=vectors.  DO NOT EDIT.
--
-- The multi-sorted, mode-merged σ-calculus with first-class renamings,
-- installed as a locally confluent Agda REWRITE system.  Maps are
-- inductive vectors, so equality of maps is equality of data and the
-- module assumes nothing: no function extensionality, no postulates.


  using (_≡_; refl; sym; cong; trans; module ≡-Reasoning)
open ≡-Reasoning

cong1 : ∀ {A1 A2 : Set} (f : A1 → A2) {a1 a2} →
  a1 ≡ a2 → f a1 ≡ f a2
cong1 f refl = refl

cong2 : ∀ {A1 A2 A3 : Set} (f : A1 → A2 → A3) {a1 a2 a3 a4} →
  a1 ≡ a2 → a3 ≡ a4 → f a1 a3 ≡ f a2 a4
cong2 f refl refl = refl

cong3 : ∀ {A1 A2 A3 A4 : Set} (f : A1 → A2 → A3 → A4) {a1 a2 a3 a4 a5 a6} →
  a1 ≡ a2 → a3 ≡ a4 → a5 ≡ a6 → f a1 a3 a5 ≡ f a2 a4 a6
cong3 f refl refl refl = refl

cong4 : ∀ {A1 A2 A3 A4 A5 : Set} (f : A1 → A2 → A3 → A4 → A5) {a1 a2 a3 a4 a5 a6 a7 a8} →
  a1 ≡ a2 → a3 ≡ a4 → a5 ≡ a6 → a7 ≡ a8 → f a1 a3 a5 a7 ≡ f a2 a4 a6 a8
cong4 f refl refl refl refl = refl

-- ─── syntax ─────────────────────────────────────────────────────────

data Sort : Set where
  tm : Sort
Scope = List Sort

variable
  s s₁ s₂ s′ : Sort
  S S₁ S₂ S₃ : Scope


-- ─── iterated lifting: a binder of variable arity ───────────────────
--
-- `ext* b n S` extends a scope by n copies of one sort.  derived and
-- transparent: it computes on n, so the rewrite system needs rules only
-- for the case where n is abstract.
--
-- Generalized from gen/Reference/FsubPatterns.agda, which fixes b := expr.

ext* : Sort → ℕ → Scope → Scope
ext* b zero    S = S
ext* b (suc n) S = b ∷ ext* b n S

data Mode : Set where V T : Mode

variable
  m : Mode

data _⊢[_]_ : Scope → Mode → Sort → Set

_⊢_ = _⊢[ T ]_
_∋_ = _⊢[ V ]_

data _⊢[_]_ where
  zero   : (s ∷ S) ∋ s
  suc    : S ∋ s → (s′ ∷ S) ∋ s
  var    : S ∋ s → S ⊢ s
  Pi     : S ⊢ tm → (tm ∷ S) ⊢ tm → S ⊢ tm
  lam    : S ⊢ tm → (tm ∷ S) ⊢ tm → S ⊢ tm
  app    : S ⊢ tm → S ⊢ tm → S ⊢ tm
  U      : S ⊢ tm
  Nat    : S ⊢ tm
  zeroN  : S ⊢ tm
  sucN   : S ⊢ tm → S ⊢ tm
  natrec : (tm ∷ S) ⊢ tm → S ⊢ tm → (tm ∷ tm ∷ S) ⊢ tm → S ⊢ tm → S ⊢ tm

variable
  t t₁ t₂ t′ : S ⊢ s
  x x′       : S ∋ s
  x/t x/t′   : S ⊢[ m ] s

variable
  tm0 tm1 tm2 tm3 : S ⊢ tm

-- ─── maps as vectors ────────────────────────────────────────────────

infixr 5 _∙ᴿ_ _∙ˢ_

data _→ᴿ_ : Scope → Scope → Set where
  []   : [] →ᴿ S
  _∙ᴿ_ : S₂ ∋ s → S₁ →ᴿ S₂ → (s ∷ S₁) →ᴿ S₂

data _→ˢ_ : Scope → Scope → Set where
  []   : [] →ˢ S
  _∙ˢ_ : S₂ ⊢ s → S₁ →ˢ S₂ → (s ∷ S₁) →ˢ S₂

variable
  ξ ξ′ ξ₁ ξ₂ ξ₃ : S₁ →ᴿ S₂
  σ σ′ σ₁ σ₂ σ₃ τ ρ : S₁ →ˢ S₂

-- ─── the renaming world ─────────────────────────────────────────────

opaque
  -- post-composition with weakening: the primitive recursion that lets
  -- lifting and the identity be defined without a composition cycle
  wk*ᴿ : ∀ s′ → S₁ →ᴿ S₂ → S₁ →ᴿ (s′ ∷ S₂)
  wk*ᴿ s′ []       = []
  wk*ᴿ s′ (x ∙ᴿ ξ) = suc x ∙ᴿ wk*ᴿ s′ ξ

  idᴿ : S →ᴿ S
  idᴿ {[]}    = []
  idᴿ {s ∷ S} = zero ∙ᴿ wk*ᴿ s idᴿ

  wkᴿ : ∀ s′ → S →ᴿ (s′ ∷ S)
  wkᴿ s′ = wk*ᴿ s′ idᴿ

  _↑ᴿ_ : S₁ →ᴿ S₂ → ∀ s → (s ∷ S₁) →ᴿ (s ∷ S₂)
  ξ ↑ᴿ s = zero ∙ᴿ wk*ᴿ s ξ

-- The n-fold renaming lift.  Derived and transparent, and defined
-- between the _↑ᴿ_ block and the _[_]ᴿ block, because the traversal of a
-- variable-arity binder uses it.

_↑ᴿ*[_]_ : S₁ →ᴿ S₂ → ∀ b n → (ext* b n S₁) →ᴿ (ext* b n S₂)
ξ ↑ᴿ*[ b ] zero    = ξ
ξ ↑ᴿ*[ b ] (suc n) = (ξ ↑ᴿ*[ b ] n) ↑ᴿ b

opaque
  unfolding wk*ᴿ idᴿ wkᴿ _↑ᴿ_

  _[_]ᴿ : S₁ ⊢[ m ] s → S₁ →ᴿ S₂ → S₂ ⊢[ m ] s
  zero    [ x ∙ᴿ ξ ]ᴿ = x
  (suc y) [ x ∙ᴿ ξ ]ᴿ = y [ ξ ]ᴿ
  (var x) [ ξ ]ᴿ = var (x [ ξ ]ᴿ)
  (Pi tm0 tm1)             [ ξ ]ᴿ = Pi (tm0 [ ξ ]ᴿ) (tm1 [ ξ ↑ᴿ tm ]ᴿ)
  (lam tm0 tm1)            [ ξ ]ᴿ = lam (tm0 [ ξ ]ᴿ) (tm1 [ ξ ↑ᴿ tm ]ᴿ)
  (app tm0 tm1)            [ ξ ]ᴿ = app (tm0 [ ξ ]ᴿ) (tm1 [ ξ ]ᴿ)
  U                        [ ξ ]ᴿ = U
  Nat                      [ ξ ]ᴿ = Nat
  zeroN                    [ ξ ]ᴿ = zeroN
  (sucN tm0)               [ ξ ]ᴿ = sucN (tm0 [ ξ ]ᴿ)
  (natrec tm0 tm1 tm2 tm3) [ ξ ]ᴿ = natrec (tm0 [ ξ ↑ᴿ tm ]ᴿ) (tm1 [ ξ ]ᴿ) (tm2 [ (ξ ↑ᴿ tm) ↑ᴿ tm ]ᴿ) (tm3 [ ξ ]ᴿ)

  _⨟ᴿ_ : S₁ →ᴿ S₂ → S₂ →ᴿ S₃ → S₁ →ᴿ S₃
  []       ⨟ᴿ ξ₂ = []
  (x ∙ᴿ ξ) ⨟ᴿ ξ₂ = (x [ ξ₂ ]ᴿ) ∙ᴿ (ξ ⨟ᴿ ξ₂)

-- ─── the substitution world ─────────────────────────────────────────

opaque
  unfolding wk*ᴿ idᴿ wkᴿ _↑ᴿ_ _[_]ᴿ _⨟ᴿ_

  ⟨_⟩ : S₁ →ᴿ S₂ → S₁ →ˢ S₂
  ⟨ [] ⟩     = []
  ⟨ x ∙ᴿ ξ ⟩ = (var x) ∙ˢ ⟨ ξ ⟩

  -- post-composition of a substitution with a renaming: keeps ↑ˢ
  -- structural, and is erased by ⨟ˢᴿ-def before any rule sees it
  _⨟ˢᴿ_ : S₁ →ˢ S₂ → S₂ →ᴿ S₃ → S₁ →ˢ S₃
  []       ⨟ˢᴿ ξ = []
  (t ∙ˢ σ) ⨟ˢᴿ ξ = (t [ ξ ]ᴿ) ∙ˢ (σ ⨟ˢᴿ ξ)

  _↑ˢ_ : S₁ →ˢ S₂ → ∀ s → (s ∷ S₁) →ˢ (s ∷ S₂)
  σ ↑ˢ s = (var zero) ∙ˢ (σ ⨟ˢᴿ wkᴿ s)

-- The n-fold substitution lift, likewise between _↑ˢ_ and _[_]ˢ.

_↑ˢ*[_]_ : S₁ →ˢ S₂ → ∀ b n → (ext* b n S₁) →ˢ (ext* b n S₂)
σ ↑ˢ*[ b ] zero    = σ
σ ↑ˢ*[ b ] (suc n) = (σ ↑ˢ*[ b ] n) ↑ˢ b

opaque
  unfolding wk*ᴿ idᴿ wkᴿ _↑ᴿ_ _[_]ᴿ ⟨_⟩ _⨟ˢᴿ_ _↑ˢ_

  _[_]ˢ : S₁ ⊢[ m ] s → S₁ →ˢ S₂ → S₂ ⊢ s
  zero    [ t ∙ˢ σ ]ˢ = t
  (suc y) [ t ∙ˢ σ ]ˢ = y [ σ ]ˢ
  (var x) [ σ ]ˢ = x [ σ ]ˢ
  (Pi tm0 tm1)             [ σ ]ˢ = Pi (tm0 [ σ ]ˢ) (tm1 [ σ ↑ˢ tm ]ˢ)
  (lam tm0 tm1)            [ σ ]ˢ = lam (tm0 [ σ ]ˢ) (tm1 [ σ ↑ˢ tm ]ˢ)
  (app tm0 tm1)            [ σ ]ˢ = app (tm0 [ σ ]ˢ) (tm1 [ σ ]ˢ)
  U                        [ σ ]ˢ = U
  Nat                      [ σ ]ˢ = Nat
  zeroN                    [ σ ]ˢ = zeroN
  (sucN tm0)               [ σ ]ˢ = sucN (tm0 [ σ ]ˢ)
  (natrec tm0 tm1 tm2 tm3) [ σ ]ˢ = natrec (tm0 [ σ ↑ˢ tm ]ˢ) (tm1 [ σ ]ˢ) (tm2 [ (σ ↑ˢ tm) ↑ˢ tm ]ˢ) (tm3 [ σ ]ˢ)

  _⨟_ : S₁ →ˢ S₂ → S₂ →ˢ S₃ → S₁ →ˢ S₃
  []       ⨟ σ₂ = []
  (t ∙ˢ σ) ⨟ σ₂ = (t [ σ₂ ]ˢ) ∙ˢ (σ ⨟ σ₂)

idˢ : S →ˢ S
idˢ = ⟨ idᴿ ⟩

wkˢ : ∀ s′ → S →ˢ (s′ ∷ S)
wkˢ s′ = ⟨ wkᴿ s′ ⟩

-- ─── the two-world rewrite system ───────────────────────────────────

opaque
  unfolding wk*ᴿ idᴿ wkᴿ _↑ᴿ_ _[_]ᴿ _⨟ᴿ_ ⟨_⟩ _⨟ˢᴿ_ _↑ˢ_ _[_]ˢ _⨟_

  -- iterated lifting.  Unlike records, patterns force these to be
  -- REWRITE rules: without lift*-idᴿ the pair (right-idᴿ, instᴿ-let) is
  -- not joinable, because `e₂ [ idᴿ ↑ᴿ*[ b ] n ]ᴿ` is stuck for abstract n.
  lift*-idᴿ         : ∀ b n → (idᴿ {S} ↑ᴿ*[ b ] n) ≡ idᴿ
  lift*-dist-compᴿᴿ : ∀ b n → ((ξ₁ ↑ᴿ*[ b ] n) ⨟ᴿ (ξ₂ ↑ᴿ*[ b ] n)) ≡ ((ξ₁ ⨟ᴿ ξ₂) ↑ᴿ*[ b ] n)
  lift*-dist-compᴿˢ : ∀ b n {ξ : S₁ →ᴿ S₂} {σ : S₂ →ˢ S₃} →
    (⟨ ξ ↑ᴿ*[ b ] n ⟩ ⨟ (σ ↑ˢ*[ b ] n)) ≡ ((⟨ ξ ⟩ ⨟ σ) ↑ˢ*[ b ] n)
  lift*-dist-compˢᴿ : ∀ b n {σ : S₁ →ˢ S₂} {ξ : S₂ →ᴿ S₃} →
    ((σ ↑ˢ*[ b ] n) ⨟ ⟨ ξ ↑ᴿ*[ b ] n ⟩) ≡ ((σ ⨟ ⟨ ξ ⟩) ↑ˢ*[ b ] n)
  lift*-dist-compˢˢ : ∀ b n → ((σ₁ ↑ˢ*[ b ] n) ⨟ (σ₂ ↑ˢ*[ b ] n)) ≡ ((σ₁ ⨟ σ₂) ↑ˢ*[ b ] n)
  ⟨⟩-lift*          : ∀ b n → (⟨ ξ ⟩ ↑ˢ*[ b ] n) ≡ ⟨ ξ ↑ᴿ*[ b ] n ⟩
  -- the iterated completion companions.  One for each `-var` / `-⨟ᴿ` /
  -- `-⨟` companion of the single-lifting layer; each closes exactly the
  -- pair that its single-lifting counterpart closes, one level up.
  lift*-dist-compᴿᴿ-var : ∀ {S₁ S₂ S₃} (b : Sort) (n : ℕ) {s} {x : (ext* b n S₁) ∋ s}
    {ξ₁ : S₁ →ᴿ S₂} {ξ₂ : S₂ →ᴿ S₃} →
    (x [ (ξ₁ ↑ᴿ*[ b ] n) ]ᴿ) [ (ξ₂ ↑ᴿ*[ b ] n) ]ᴿ ≡ x [ ((ξ₁ ⨟ᴿ ξ₂) ↑ᴿ*[ b ] n) ]ᴿ
  lift*-dist-compᴿᴿ-⨟ᴿ : ∀ {S₁ S₂ S₃ S₄} (b : Sort) (n : ℕ) {ξ₁ : S₁ →ᴿ S₂} {ξ₂ : S₂ →ᴿ S₃}
    {ξ′ : (ext* b n S₃) →ᴿ S₄} →
    (ξ₁ ↑ᴿ*[ b ] n) ⨟ᴿ ((ξ₂ ↑ᴿ*[ b ] n) ⨟ᴿ ξ′) ≡ ((ξ₁ ⨟ᴿ ξ₂) ↑ᴿ*[ b ] n) ⨟ᴿ ξ′
  lift*-dist-compˢˢ-⨟ : ∀ {S₁ S₂ S₃} (b : Sort) (n : ℕ) {S₄} {σ₁ : S₁ →ˢ S₂} {σ₂ : S₂ →ˢ S₃}
    {τ : (ext* b n S₃) →ˢ S₄} →
    (σ₁ ↑ˢ*[ b ] n) ⨟ ((σ₂ ↑ˢ*[ b ] n) ⨟ τ) ≡ ((σ₁ ⨟ σ₂) ↑ˢ*[ b ] n) ⨟ τ
  lift*-dist-compᴿˢ-⨟ : ∀ {S₁ S₂ S₃} (b : Sort) (n : ℕ) {S₄} {ξ : S₁ →ᴿ S₂} {σ : S₂ →ˢ S₃}
    {τ : (ext* b n S₃) →ˢ S₄} →
    ⟨ ξ ↑ᴿ*[ b ] n ⟩ ⨟ ((σ ↑ˢ*[ b ] n) ⨟ τ) ≡ ((⟨ ξ ⟩ ⨟ σ) ↑ˢ*[ b ] n) ⨟ τ
  lift*-dist-compˢᴿ-⨟ : ∀ {S₁ S₂ S₃} (b : Sort) (n : ℕ) {S₄} {σ : S₁ →ˢ S₂} {ξ : S₂ →ᴿ S₃}
    {τ : (ext* b n S₃) →ˢ S₄} →
    (σ ↑ˢ*[ b ] n) ⨟ (⟨ ξ ↑ᴿ*[ b ] n ⟩ ⨟ τ) ≡ ((σ ⨟ ⟨ ξ ⟩) ↑ˢ*[ b ] n) ⨟ τ
  lift*-dist-compᴿˢ-var : ∀ {S₁ S₂ S₃} (b : Sort) (n : ℕ) {s} {x : (ext* b n S₁) ∋ s}
    {ξ : S₁ →ᴿ S₂} {σ : S₂ →ˢ S₃} →
    (x [ (ξ ↑ᴿ*[ b ] n) ]ᴿ) [ (σ ↑ˢ*[ b ] n) ]ˢ ≡ x [ ((⟨ ξ ⟩ ⨟ σ) ↑ˢ*[ b ] n) ]ˢ
  ⟨⟩-comp-⨟-lift*-dist-compᴿᴿ : ∀ {S₁ S₂ S₃} (b : Sort) (n : ℕ) {S₄} {ξ₁ : S₁ →ᴿ S₂} {ξ₂ : S₂ →ᴿ S₃}
    {τ : (ext* b n S₃) →ˢ S₄} →
    ⟨ ξ₁ ↑ᴿ*[ b ] n ⟩ ⨟ (⟨ ξ₂ ↑ᴿ*[ b ] n ⟩ ⨟ τ) ≡ ⟨ (ξ₁ ⨟ᴿ ξ₂) ↑ᴿ*[ b ] n ⟩ ⨟ τ
  lift*-dist-compᴿˢ-⨟-var : ∀ {S₁ S₂ S₃} (b : Sort) (n : ℕ) {S₄} {s} {x : (ext* b n S₁) ∋ s}
    {ξ : S₁ →ᴿ S₂} {σ : S₂ →ˢ S₃} {τ : (ext* b n S₃) →ˢ S₄} →
    (x [ (ξ ↑ᴿ*[ b ] n) ]ᴿ) [ ((σ ↑ˢ*[ b ] n) ⨟ τ) ]ˢ ≡ x [ (((⟨ ξ ⟩ ⨟ σ) ↑ˢ*[ b ] n) ⨟ τ) ]ˢ
  ⟨⟩-split*-tail : ∀ {S₁ S₂ S₃} (b : Sort) (n : ℕ) {S₄} {σ : S₁ →ˢ S₂} {ξ : S₂ →ᴿ S₃}
    {ξ′ : (ext* b n S₃) →ᴿ S₄} →
    (σ ↑ˢ*[ b ] n) ⨟ ⟨ (ξ ↑ᴿ*[ b ] n) ⨟ᴿ ξ′ ⟩ ≡ ((σ ⨟ ⟨ ξ ⟩) ↑ˢ*[ b ] n) ⨟ ⟨ ξ′ ⟩

  -- vector-model only, and NOT registered: the n-fold companion of the
  -- internal `_⨟ˢᴿ_`, needed by the compositionalityˢᴿ induction for a
  -- variable-arity binder.  The registered rule set is unaffected.
  lift*-⨟ˢᴿ : ∀ b n {σ : S₁ →ˢ S₂} {ξ : S₂ →ᴿ S₃} →
    ((σ ↑ˢ*[ b ] n) ⨟ˢᴿ (ξ ↑ᴿ*[ b ] n)) ≡ ((σ ⨟ˢᴿ ξ) ↑ˢ*[ b ] n)
  -- ══ Iᴿ. applied rules, renaming world ═════════════════════════════
  def-∙ᴿ-zero : zero [ (x ∙ᴿ ξ) ]ᴿ ≡ x
  def-∙ᴿ-zero = refl

  def-∙ᴿ-suc : (suc {s′ = s′} x′) [ (x ∙ᴿ ξ) ]ᴿ ≡ x′ [ ξ ]ᴿ
  def-∙ᴿ-suc = refl

  lookup-wk*ᴿ : ∀ (x : S₁ ∋ s) (ξ : S₁ →ᴿ S₂) → x [ wk*ᴿ s′ ξ ]ᴿ ≡ suc (x [ ξ ]ᴿ)
  lookup-wk*ᴿ zero    (y ∙ᴿ ξ) = refl
  lookup-wk*ᴿ (suc x) (y ∙ᴿ ξ) = lookup-wk*ᴿ x ξ

  lookup-idᴿ : ∀ (x : S ∋ s) → x [ idᴿ ]ᴿ ≡ x
  lookup-idᴿ zero    = refl
  lookup-idᴿ (suc x) = trans (lookup-wk*ᴿ x idᴿ) (cong suc (lookup-idᴿ x))

  def-wkᴿ : x [ wkᴿ s′ ]ᴿ ≡ suc x
  def-wkᴿ {x = x} = trans (lookup-wk*ᴿ x idᴿ) (cong suc (lookup-idᴿ x))

  def-↑ᴿ-zero : zero [ (ξ ↑ᴿ s) ]ᴿ ≡ zero
  def-↑ᴿ-zero = refl

  def-↑ᴿ-suc : (suc x) [ (ξ ↑ᴿ s) ]ᴿ ≡ suc (x [ ξ ]ᴿ)
  def-↑ᴿ-suc {x = x} {ξ = ξ} = lookup-wk*ᴿ x ξ

  lift-idᴿ : (idᴿ {S} ↑ᴿ s) ≡ idᴿ
  lift-idᴿ = refl

  -- ══ IIᴿ. traversal rules, renaming world ═════════════════════════
  instᴿ-var : (var x) [ ξ ]ᴿ ≡ var (x [ ξ ]ᴿ)
  instᴿ-Pi     : (Pi tm0 tm1) [ ξ ]ᴿ             ≡ Pi (tm0 [ ξ ]ᴿ) (tm1 [ ξ ↑ᴿ tm ]ᴿ)
  instᴿ-lam    : (lam tm0 tm1) [ ξ ]ᴿ            ≡ lam (tm0 [ ξ ]ᴿ) (tm1 [ ξ ↑ᴿ tm ]ᴿ)
  instᴿ-app    : (app tm0 tm1) [ ξ ]ᴿ            ≡ app (tm0 [ ξ ]ᴿ) (tm1 [ ξ ]ᴿ)
  instᴿ-U      : U {S = S} [ ξ ]ᴿ                ≡ U
  instᴿ-Nat    : Nat {S = S} [ ξ ]ᴿ              ≡ Nat
  instᴿ-zeroN  : zeroN {S = S} [ ξ ]ᴿ            ≡ zeroN
  instᴿ-sucN   : (sucN tm0) [ ξ ]ᴿ               ≡ sucN (tm0 [ ξ ]ᴿ)
  instᴿ-natrec : (natrec tm0 tm1 tm2 tm3) [ ξ ]ᴿ ≡ natrec (tm0 [ ξ ↑ᴿ tm ]ᴿ) (tm1 [ ξ ]ᴿ) (tm2 [ (ξ ↑ᴿ tm) ↑ᴿ tm ]ᴿ) (tm3 [ ξ ]ᴿ)
  instᴿ-var = refl
  instᴿ-Pi     = refl
  instᴿ-lam    = refl
  instᴿ-app    = refl
  instᴿ-U      = refl
  instᴿ-Nat    = refl
  instᴿ-zeroN  = refl
  instᴿ-sucN   = refl
  instᴿ-natrec = refl

  -- ══ IIIᴿ. map algebra, renaming world ════════════════════════════
  distᴿ : (x ∙ᴿ ξ₁) ⨟ᴿ ξ₂ ≡ (x [ ξ₂ ]ᴿ) ∙ᴿ (ξ₁ ⨟ᴿ ξ₂)
  distᴿ = refl

  compositionalityᴿᴿ-var : ∀ (x : S₁ ∋ s) {ξ₁ : S₁ →ᴿ S₂} {ξ₂ : S₂ →ᴿ S₃} →
    x [ (ξ₁ ⨟ᴿ ξ₂) ]ᴿ ≡ (x [ ξ₁ ]ᴿ) [ ξ₂ ]ᴿ
  compositionalityᴿᴿ-var zero    {ξ₁ = y ∙ᴿ ξ₁} = refl
  compositionalityᴿᴿ-var (suc x) {ξ₁ = y ∙ᴿ ξ₁} = compositionalityᴿᴿ-var x

  wk*ᴿ-⨟ᴿ : ∀ (ξ₁ : S₁ →ᴿ S₂) (x : S₃ ∋ s′) (ξ₂ : S₂ →ᴿ S₃) →
    wk*ᴿ s′ ξ₁ ⨟ᴿ (x ∙ᴿ ξ₂) ≡ ξ₁ ⨟ᴿ ξ₂
  wk*ᴿ-⨟ᴿ []        x ξ₂ = refl
  wk*ᴿ-⨟ᴿ (y ∙ᴿ ξ₁) x ξ₂ = cong (_ ∙ᴿ_) (wk*ᴿ-⨟ᴿ ξ₁ x ξ₂)

  comp-idₗᴿ : idᴿ ⨟ᴿ ξ ≡ ξ
  comp-idₗᴿ {ξ = []}     = refl
  comp-idₗᴿ {ξ = x ∙ᴿ ξ} = cong (x ∙ᴿ_) (trans (wk*ᴿ-⨟ᴿ idᴿ x ξ) comp-idₗᴿ)

  comp-idᵣᴿ : ξ ⨟ᴿ idᴿ ≡ ξ
  comp-idᵣᴿ {ξ = []}     = refl
  comp-idᵣᴿ {ξ = x ∙ᴿ ξ} = cong2 _∙ᴿ_ (lookup-idᴿ x) comp-idᵣᴿ

  interactᴿ : wkᴿ s ⨟ᴿ (x ∙ᴿ ξ) ≡ ξ
  interactᴿ {x = x} {ξ = ξ} = trans (wk*ᴿ-⨟ᴿ idᴿ x ξ) comp-idₗᴿ

  lift-consᴿ : (ξ ↑ᴿ s) ⨟ᴿ (x ∙ᴿ ξ′) ≡ x ∙ᴿ (ξ ⨟ᴿ ξ′)
  lift-consᴿ {ξ = ξ} {x = x} {ξ′ = ξ′} = cong (x ∙ᴿ_) (wk*ᴿ-⨟ᴿ ξ x ξ′)

  assocᴿ : (ξ₁ ⨟ᴿ ξ₂) ⨟ᴿ ξ₃ ≡ ξ₁ ⨟ᴿ (ξ₂ ⨟ᴿ ξ₃)
  assocᴿ {ξ₁ = []}      = refl
  assocᴿ {ξ₁ = x ∙ᴿ ξ₁} = cong2 _∙ᴿ_ (sym (compositionalityᴿᴿ-var x)) assocᴿ

  wk*ᴿ-comp : ∀ (ξ₁ : S₁ →ᴿ S₂) (ξ₂ : S₂ →ᴿ S₃) →
    wk*ᴿ s ξ₁ ⨟ᴿ (ξ₂ ↑ᴿ s) ≡ wk*ᴿ s (ξ₁ ⨟ᴿ ξ₂)
  wk*ᴿ-comp []        ξ₂ = refl
  wk*ᴿ-comp (x ∙ᴿ ξ₁) ξ₂ = cong2 _∙ᴿ_ (lookup-wk*ᴿ x ξ₂) (wk*ᴿ-comp ξ₁ ξ₂)

  ⨟ᴿ-wk*ᴿ : ∀ (ξ₁ : S₁ →ᴿ S₂) (ξ₂ : S₂ →ᴿ S₃) →
    ξ₁ ⨟ᴿ wk*ᴿ s ξ₂ ≡ wk*ᴿ s (ξ₁ ⨟ᴿ ξ₂)
  ⨟ᴿ-wk*ᴿ []        ξ₂ = refl
  ⨟ᴿ-wk*ᴿ (x ∙ᴿ ξ₁) ξ₂ = cong2 _∙ᴿ_ (lookup-wk*ᴿ x ξ₂) (⨟ᴿ-wk*ᴿ ξ₁ ξ₂)

  lift-dist-compᴿᴿ : ((ξ₁ ↑ᴿ s) ⨟ᴿ (ξ₂ ↑ᴿ s)) ≡ ((ξ₁ ⨟ᴿ ξ₂) ↑ᴿ s)
  lift-dist-compᴿᴿ {ξ₁ = ξ₁} {ξ₂ = ξ₂} = cong (zero ∙ᴿ_) (wk*ᴿ-comp ξ₁ ξ₂)

  lift-wkᴿ : wkᴿ s ⨟ᴿ (ξ ↑ᴿ s) ≡ ξ ⨟ᴿ wkᴿ s
  lift-wkᴿ {ξ = ξ} = trans (wk*ᴿ-comp idᴿ ξ)
    (trans (cong (wk*ᴿ _) comp-idₗᴿ)
    (sym (trans (⨟ᴿ-wk*ᴿ ξ idᴿ) (cong (wk*ᴿ _) comp-idᵣᴿ))))

  -- ══ VIᴿ. completion companions, renaming world ═══════════════════
  -- `assocᴿ` right-nests ⨟ᴿ, so a rule whose right operand is not a
  -- metavariable stops matching once a continuation is appended.
  interactᴿ-⨟ᴿ : ∀ {x : S₂ ∋ s} {ξ : S₁ →ᴿ S₂} {ξ′ : S₂ →ᴿ S₃} →
    wkᴿ s ⨟ᴿ ((x ∙ᴿ ξ) ⨟ᴿ ξ′) ≡ ξ ⨟ᴿ ξ′
  interactᴿ-⨟ᴿ {s = s} {x = x} {ξ = ξ} {ξ′ = ξ′} =
    trans (sym (assocᴿ {ξ₁ = wkᴿ s} {ξ₂ = x ∙ᴿ ξ} {ξ₃ = ξ′}))
          (cong (_⨟ᴿ ξ′) (interactᴿ {s = s} {x = x} {ξ = ξ}))

  lift-wkᴿ-⨟ᴿ : ∀ {ξ : S₁ →ᴿ S₂} {ξ′ : (s ∷ S₂) →ᴿ S₃} →
    wkᴿ s ⨟ᴿ ((ξ ↑ᴿ s) ⨟ᴿ ξ′) ≡ ξ ⨟ᴿ (wkᴿ s ⨟ᴿ ξ′)
  lift-wkᴿ-⨟ᴿ {s = s} {ξ = ξ} {ξ′ = ξ′} =
    trans (sym (assocᴿ {ξ₁ = wkᴿ s} {ξ₂ = ξ ↑ᴿ s} {ξ₃ = ξ′}))
          (trans (cong (_⨟ᴿ ξ′) (lift-wkᴿ {s = s} {ξ = ξ}))
                 (assocᴿ {ξ₁ = ξ} {ξ₂ = wkᴿ s} {ξ₃ = ξ′}))

  lift-dist-compᴿᴿ-⨟ᴿ : ∀ {S₄ : Scope} {ξ₁ : S₁ →ᴿ S₂} {ξ₂ : S₂ →ᴿ S₃}
    {ξ′ : (s ∷ S₃) →ᴿ S₄} →
    (ξ₁ ↑ᴿ s) ⨟ᴿ ((ξ₂ ↑ᴿ s) ⨟ᴿ ξ′) ≡ ((ξ₁ ⨟ᴿ ξ₂) ↑ᴿ s) ⨟ᴿ ξ′
  lift-dist-compᴿᴿ-⨟ᴿ {ξ₁ = ξ₁} {ξ₂ = ξ₂} {ξ′ = ξ′} =
    trans (sym (assocᴿ {ξ₁ = ξ₁ ↑ᴿ _} {ξ₂ = ξ₂ ↑ᴿ _} {ξ₃ = ξ′}))
          (cong (_⨟ᴿ ξ′) (lift-dist-compᴿᴿ {ξ₁ = ξ₁} {ξ₂ = ξ₂}))

  lift-dist-compᴿᴿ-var : ∀ {x : (s ∷ S₁) ∋ s′} {ξ₁ : S₁ →ᴿ S₂} {ξ₂ : S₂ →ᴿ S₃} →
    (x [ (ξ₁ ↑ᴿ s) ]ᴿ) [ (ξ₂ ↑ᴿ s) ]ᴿ ≡ x [ ((ξ₁ ⨟ᴿ ξ₂) ↑ᴿ s) ]ᴿ
  lift-dist-compᴿᴿ-var {x = x} {ξ₁ = ξ₁} {ξ₂ = ξ₂} =
    trans (sym (compositionalityᴿᴿ-var x {ξ₁ = ξ₁ ↑ᴿ _} {ξ₂ = ξ₂ ↑ᴿ _}))
          (cong (λ z → x [ z ]ᴿ) (lift-dist-compᴿᴿ {ξ₁ = ξ₁} {ξ₂ = ξ₂}))

  lift-consᴿ-var : ∀ {x : (s ∷ S₁) ∋ s′} {x′ : S₃ ∋ s} {ξ : S₁ →ᴿ S₂}
    {ξ′ : S₂ →ᴿ S₃} →
    (x [ (ξ ↑ᴿ s) ]ᴿ) [ (x′ ∙ᴿ ξ′) ]ᴿ ≡ x [ (x′ ∙ᴿ (ξ ⨟ᴿ ξ′)) ]ᴿ
  lift-consᴿ-var {x = x} {x′ = x′} {ξ = ξ} {ξ′ = ξ′} =
    trans (sym (compositionalityᴿᴿ-var x {ξ₁ = ξ ↑ᴿ _} {ξ₂ = x′ ∙ᴿ ξ′}))
          (cong (λ z → x [ z ]ᴿ) (lift-consᴿ {ξ = ξ} {x = x′} {ξ′ = ξ′}))

  -- ══ Vᴿ. monad laws, renaming world ═══════════════════════════════
  right-idᴿ : ∀ (x/t : S ⊢[ m ] s) → x/t [ idᴿ ]ᴿ ≡ x/t
  right-idᴿ zero    = refl
  right-idᴿ (suc x) = lookup-idᴿ (suc x)
  right-idᴿ (var x)   = cong var (lookup-idᴿ x)
  right-idᴿ (Pi tm0 tm1)             = cong2 Pi (right-idᴿ tm0) (trans (cong (tm1 [_]ᴿ) lift-idᴿ) (right-idᴿ tm1))
  right-idᴿ (lam tm0 tm1)            = cong2 lam (right-idᴿ tm0) (trans (cong (tm1 [_]ᴿ) lift-idᴿ) (right-idᴿ tm1))
  right-idᴿ (app tm0 tm1)            = cong2 app (right-idᴿ tm0) (right-idᴿ tm1)
  right-idᴿ U                        = refl
  right-idᴿ Nat                      = refl
  right-idᴿ zeroN                    = refl
  right-idᴿ (sucN tm0)               = cong1 sucN (right-idᴿ tm0)
  right-idᴿ (natrec tm0 tm1 tm2 tm3) = cong4 natrec (trans (cong (tm0 [_]ᴿ) lift-idᴿ) (right-idᴿ tm0)) (right-idᴿ tm1) (trans (cong (tm2 [_]ᴿ) (trans (cong (_↑ᴿ tm) lift-idᴿ) lift-idᴿ)) (right-idᴿ tm2)) (right-idᴿ tm3)

  -- T-only.  Its V-instance is compositionalityᴿᴿ-var read backwards, and
  -- registering both loops: this rule folds (x [ ξ₁ ]ᴿ) [ ξ₂ ]ᴿ into
  -- x [ ξ₁ ⨟ᴿ ξ₂ ]ᴿ and compositionalityᴿᴿ-var pushes it straight back.
  compositionalityᴿᴿ : ∀ (t : S₁ ⊢ s) {ξ₁ : S₁ →ᴿ S₂} {ξ₂ : S₂ →ᴿ S₃} →
    (t [ ξ₁ ]ᴿ) [ ξ₂ ]ᴿ ≡ t [ (ξ₁ ⨟ᴿ ξ₂) ]ᴿ
  compositionalityᴿᴿ (var x) {ξ₁ = ξ₁} {ξ₂ = ξ₂} = cong var (sym (compositionalityᴿᴿ-var x {ξ₁ = ξ₁} {ξ₂ = ξ₂}))
  compositionalityᴿᴿ (Pi tm0 tm1)                                 = cong2 Pi (compositionalityᴿᴿ tm0) (trans (compositionalityᴿᴿ tm1) (cong (tm1 [_]ᴿ) lift-dist-compᴿᴿ))
  compositionalityᴿᴿ (lam tm0 tm1)                                = cong2 lam (compositionalityᴿᴿ tm0) (trans (compositionalityᴿᴿ tm1) (cong (tm1 [_]ᴿ) lift-dist-compᴿᴿ))
  compositionalityᴿᴿ (app tm0 tm1)                                = cong2 app (compositionalityᴿᴿ tm0) (compositionalityᴿᴿ tm1)
  compositionalityᴿᴿ U                                            = refl
  compositionalityᴿᴿ Nat                                          = refl
  compositionalityᴿᴿ zeroN                                        = refl
  compositionalityᴿᴿ (sucN tm0)                                   = cong1 sucN (compositionalityᴿᴿ tm0)
  compositionalityᴿᴿ (natrec tm0 tm1 tm2 tm3) {ξ₁ = ξ₁} {ξ₂ = ξ₂} = cong4 natrec (trans (compositionalityᴿᴿ tm0) (cong (tm0 [_]ᴿ) lift-dist-compᴿᴿ)) (compositionalityᴿᴿ tm1) (trans (compositionalityᴿᴿ tm2) (cong (tm2 [_]ᴿ) (trans (lift-dist-compᴿᴿ {ξ₁ = (ξ₁ ↑ᴿ tm)} {ξ₂ = (ξ₂ ↑ᴿ tm)}) (cong (_↑ᴿ tm) (lift-dist-compᴿᴿ {ξ₁ = ξ₁} {ξ₂ = ξ₂}))))) (compositionalityᴿᴿ tm3)

  -- ─── the substitution world ───────────────────────────────────────

  ⟨⟩-⨟ˢᴿ-wk : ∀ (ξ : S₁ →ᴿ S₂) → ⟨ ξ ⟩ ⨟ˢᴿ wkᴿ s ≡ ⟨ wk*ᴿ s ξ ⟩
  ⟨⟩-⨟ˢᴿ-wk []       = refl
  ⟨⟩-⨟ˢᴿ-wk (x ∙ᴿ ξ) = cong2 _∙ˢ_ (cong var def-wkᴿ) (⟨⟩-⨟ˢᴿ-wk ξ)

  ⟨⟩-lift : (⟨ ξ ⟩ ↑ˢ s) ≡ ⟨ ξ ↑ᴿ s ⟩
  ⟨⟩-lift {ξ = ξ} = cong ((var zero) ∙ˢ_) (⟨⟩-⨟ˢᴿ-wk ξ)

  coincidence-var : ∀ (x : S₁ ∋ s) (ξ : S₁ →ᴿ S₂) → x [ ⟨ ξ ⟩ ]ˢ ≡ var (x [ ξ ]ᴿ)
  coincidence-var zero    (y ∙ᴿ ξ) = refl
  coincidence-var (suc x) (y ∙ᴿ ξ) = coincidence-var x ξ

  coincidence : ∀ (t : S₁ ⊢ s) (ξ : S₁ →ᴿ S₂) → t [ ⟨ ξ ⟩ ]ˢ ≡ t [ ξ ]ᴿ
  coincidence (var x) ξ = coincidence-var x ξ
  coincidence (Pi tm0 tm1) ξ             = cong2 Pi (coincidence tm0 ξ) (trans (cong (tm1 [_]ˢ) (⟨⟩-lift {ξ = ξ})) (coincidence tm1 (ξ ↑ᴿ tm)))
  coincidence (lam tm0 tm1) ξ            = cong2 lam (coincidence tm0 ξ) (trans (cong (tm1 [_]ˢ) (⟨⟩-lift {ξ = ξ})) (coincidence tm1 (ξ ↑ᴿ tm)))
  coincidence (app tm0 tm1) ξ            = cong2 app (coincidence tm0 ξ) (coincidence tm1 ξ)
  coincidence U ξ                        = refl
  coincidence Nat ξ                      = refl
  coincidence zeroN ξ                    = refl
  coincidence (sucN tm0) ξ               = cong1 sucN (coincidence tm0 ξ)
  coincidence (natrec tm0 tm1 tm2 tm3) ξ = cong4 natrec (trans (cong (tm0 [_]ˢ) (⟨⟩-lift {ξ = ξ})) (coincidence tm0 (ξ ↑ᴿ tm))) (coincidence tm1 ξ) (trans (cong (tm2 [_]ˢ) (trans (cong (_↑ˢ tm) (⟨⟩-lift {ξ = ξ})) (⟨⟩-lift {ξ = (ξ ↑ᴿ tm)}))) (coincidence tm2 ((ξ ↑ᴿ tm) ↑ᴿ tm))) (coincidence tm3 ξ)

  ⨟ˢᴿ-def : ∀ (σ : S₁ →ˢ S₂) (ξ : S₂ →ᴿ S₃) → σ ⨟ˢᴿ ξ ≡ σ ⨟ ⟨ ξ ⟩
  ⨟ˢᴿ-def []       ξ = refl
  ⨟ˢᴿ-def (t ∙ˢ σ) ξ = cong2 _∙ˢ_ (sym (coincidence t ξ)) (⨟ˢᴿ-def σ ξ)

  -- ══ Iˢ. applied rules, substitution world ════════════════════════
  def-∙ˢ-zero : zero [ (t ∙ˢ σ) ]ˢ ≡ t
  def-∙ˢ-zero = refl

  def-∙ˢ-suc : (suc {s′ = s′} x) [ (t ∙ˢ σ) ]ˢ ≡ x [ σ ]ˢ
  def-∙ˢ-suc = refl

  def-↑ˢ-zero : zero [ (σ ↑ˢ s) ]ˢ ≡ var zero
  def-↑ˢ-zero = refl

  def-↑ˢ-suc : (suc x) [ (σ ↑ˢ s) ]ˢ ≡ x [ (σ ⨟ ⟨ wkᴿ s ⟩) ]ˢ
  def-↑ˢ-suc {x = x} {σ = σ} {s = s} = cong (x [_]ˢ) (⨟ˢᴿ-def σ (wkᴿ s))

  -- ══ lookup through the two hybrid compositions ═══════════════════
  lookup-⨟ˢᴿ : ∀ (x : S₁ ∋ s) (σ : S₁ →ˢ S₂) (ξ : S₂ →ᴿ S₃) →
    x [ σ ⨟ˢᴿ ξ ]ˢ ≡ (x [ σ ]ˢ) [ ξ ]ᴿ
  lookup-⨟ˢᴿ zero    (t ∙ˢ σ) ξ = refl
  lookup-⨟ˢᴿ (suc x) (t ∙ˢ σ) ξ = lookup-⨟ˢᴿ x σ ξ

  lookup-⨟ˢ : ∀ (x : S₁ ∋ s) (σ₁ : S₁ →ˢ S₂) (σ₂ : S₂ →ˢ S₃) →
    x [ σ₁ ⨟ σ₂ ]ˢ ≡ (x [ σ₁ ]ˢ) [ σ₂ ]ˢ
  lookup-⨟ˢ zero    (t ∙ˢ σ₁) σ₂ = refl
  lookup-⨟ˢ (suc x) (t ∙ˢ σ₁) σ₂ = lookup-⨟ˢ x σ₁ σ₂

  -- ══ IIIˢ/IVˢ. map algebra and lifting, substitution world ════════
  dist : (t ∙ˢ σ₁) ⨟ σ₂ ≡ (t [ σ₂ ]ˢ) ∙ˢ (σ₁ ⨟ σ₂)
  dist = refl

  ⟨wk*⟩-cons : ∀ (ξ : S₁ →ᴿ S₂) (t : S₃ ⊢ s′) (σ : S₂ →ˢ S₃) →
    ⟨ wk*ᴿ s′ ξ ⟩ ⨟ (t ∙ˢ σ) ≡ ⟨ ξ ⟩ ⨟ σ
  ⟨wk*⟩-cons []       t σ = refl
  ⟨wk*⟩-cons (x ∙ᴿ ξ) t σ = cong (_ ∙ˢ_) (⟨wk*⟩-cons ξ t σ)

  comp-idₗ : ⟨ idᴿ {S₁} ⟩ ⨟ σ ≡ σ
  comp-idₗ {σ = []}     = refl
  comp-idₗ {σ = t ∙ˢ σ} = cong (t ∙ˢ_) (trans (⟨wk*⟩-cons idᴿ t σ) comp-idₗ)

  interact : ⟨ wkᴿ s ⟩ ⨟ (t ∙ˢ σ) ≡ σ
  interact {t = t} {σ = σ} = trans (⟨wk*⟩-cons idᴿ t σ) comp-idₗ

  ⟨wk*⟩-lift : ∀ (ξ : S₁ →ᴿ S₂) (σ : S₂ →ˢ S₃) →
    ⟨ wk*ᴿ s ξ ⟩ ⨟ (σ ↑ˢ s) ≡ (⟨ ξ ⟩ ⨟ σ) ⨟ˢᴿ wkᴿ s
  ⟨wk*⟩-lift []       σ = refl
  ⟨wk*⟩-lift (x ∙ᴿ ξ) σ = cong2 _∙ˢ_ (lookup-⨟ˢᴿ x σ (wkᴿ _)) (⟨wk*⟩-lift ξ σ)

  lift-dist-compᴿˢ : ⟨ ξ ↑ᴿ s ⟩ ⨟ (σ ↑ˢ s) ≡ ((⟨ ξ ⟩ ⨟ σ) ↑ˢ s)
  lift-dist-compᴿˢ {ξ = ξ} {σ = σ} = cong ((var zero) ∙ˢ_) (⟨wk*⟩-lift ξ σ)

  -- ══ the mixed compositionality laws, stratified ══════════════════
  -- the variable instance, kept separate: registering it alongside a
  -- mode-generic compositionalityᴿˢ would loop, since at mode V the two
  -- are inverse.  At V everything pushes, at T everything folds.
  compositionalityᴿˢ-var : ∀ (x : S₁ ∋ s) {ξ : S₁ →ᴿ S₂} {σ : S₂ →ˢ S₃} →
    (x [ ξ ]ᴿ) [ σ ]ˢ ≡ x [ (⟨ ξ ⟩ ⨟ σ) ]ˢ
  compositionalityᴿˢ-var zero    {ξ = y ∙ᴿ ξ} = refl
  compositionalityᴿˢ-var (suc x) {ξ = y ∙ᴿ ξ} = compositionalityᴿˢ-var x

  -- T-only, for the same reason compositionalityᴿᴿ is.
  compositionalityᴿˢ : ∀ (t : S₁ ⊢ s) {ξ : S₁ →ᴿ S₂} {σ : S₂ →ˢ S₃} →
    (t [ ξ ]ᴿ) [ σ ]ˢ ≡ t [ (⟨ ξ ⟩ ⨟ σ) ]ˢ
  compositionalityᴿˢ (var x) = compositionalityᴿˢ-var x
  compositionalityᴿˢ (Pi tm0 tm1)                             = cong2 Pi (compositionalityᴿˢ tm0) (trans (compositionalityᴿˢ tm1) (cong (tm1 [_]ˢ) lift-dist-compᴿˢ))
  compositionalityᴿˢ (lam tm0 tm1)                            = cong2 lam (compositionalityᴿˢ tm0) (trans (compositionalityᴿˢ tm1) (cong (tm1 [_]ˢ) lift-dist-compᴿˢ))
  compositionalityᴿˢ (app tm0 tm1)                            = cong2 app (compositionalityᴿˢ tm0) (compositionalityᴿˢ tm1)
  compositionalityᴿˢ U                                        = refl
  compositionalityᴿˢ Nat                                      = refl
  compositionalityᴿˢ zeroN                                    = refl
  compositionalityᴿˢ (sucN tm0)                               = cong1 sucN (compositionalityᴿˢ tm0)
  compositionalityᴿˢ (natrec tm0 tm1 tm2 tm3) {ξ = ξ} {σ = σ} = cong4 natrec (trans (compositionalityᴿˢ tm0) (cong (tm0 [_]ˢ) lift-dist-compᴿˢ)) (compositionalityᴿˢ tm1) (trans (compositionalityᴿˢ tm2) (cong (tm2 [_]ˢ) (trans (lift-dist-compᴿˢ {ξ = (ξ ↑ᴿ tm)} {σ = (σ ↑ˢ tm)}) (cong (_↑ˢ tm) (lift-dist-compᴿˢ {ξ = ξ} {σ = σ}))))) (compositionalityᴿˢ tm3)

  ⨟ˢᴿ-lift : ∀ (σ : S₁ →ˢ S₂) (ξ : S₂ →ᴿ S₃) →
    (σ ⨟ˢᴿ wkᴿ s) ⨟ˢᴿ (ξ ↑ᴿ s) ≡ (σ ⨟ˢᴿ ξ) ⨟ˢᴿ wkᴿ s
  ⨟ˢᴿ-lift []       ξ = refl
  ⨟ˢᴿ-lift (t ∙ˢ σ) ξ = cong2 _∙ˢ_
    (trans (compositionalityᴿᴿ t) (trans (cong (t [_]ᴿ) lift-wkᴿ) (sym (compositionalityᴿᴿ t))))
    (⨟ˢᴿ-lift σ ξ)

  lift-⨟ˢᴿ : ∀ {σ : S₁ →ˢ S₂} {ξ : S₂ →ᴿ S₃} →
    (σ ↑ˢ s) ⨟ˢᴿ (ξ ↑ᴿ s) ≡ ((σ ⨟ˢᴿ ξ) ↑ˢ s)
  lift-⨟ˢᴿ {σ = σ} {ξ = ξ} = cong ((var zero) ∙ˢ_) (⨟ˢᴿ-lift σ ξ)

  compositionalityˢᴿ′ : ∀ (x/t : S₁ ⊢[ m ] s) {σ : S₁ →ˢ S₂} {ξ : S₂ →ᴿ S₃} →
    (x/t [ σ ]ˢ) [ ξ ]ᴿ ≡ x/t [ (σ ⨟ˢᴿ ξ) ]ˢ
  compositionalityˢᴿ′ zero    {σ = t ∙ˢ σ} = refl
  compositionalityˢᴿ′ (suc x) {σ = t ∙ˢ σ} = compositionalityˢᴿ′ x
  compositionalityˢᴿ′ (var x) = compositionalityˢᴿ′ x
  compositionalityˢᴿ′ (Pi tm0 tm1)                             = cong2 Pi (compositionalityˢᴿ′ tm0) (trans (compositionalityˢᴿ′ tm1) (cong (tm1 [_]ˢ) lift-⨟ˢᴿ))
  compositionalityˢᴿ′ (lam tm0 tm1)                            = cong2 lam (compositionalityˢᴿ′ tm0) (trans (compositionalityˢᴿ′ tm1) (cong (tm1 [_]ˢ) lift-⨟ˢᴿ))
  compositionalityˢᴿ′ (app tm0 tm1)                            = cong2 app (compositionalityˢᴿ′ tm0) (compositionalityˢᴿ′ tm1)
  compositionalityˢᴿ′ U                                        = refl
  compositionalityˢᴿ′ Nat                                      = refl
  compositionalityˢᴿ′ zeroN                                    = refl
  compositionalityˢᴿ′ (sucN tm0)                               = cong1 sucN (compositionalityˢᴿ′ tm0)
  compositionalityˢᴿ′ (natrec tm0 tm1 tm2 tm3) {σ = σ} {ξ = ξ} = cong4 natrec (trans (compositionalityˢᴿ′ tm0) (cong (tm0 [_]ˢ) lift-⨟ˢᴿ)) (compositionalityˢᴿ′ tm1) (trans (compositionalityˢᴿ′ tm2) (cong (tm2 [_]ˢ) (trans (lift-⨟ˢᴿ {σ = (σ ↑ˢ tm)} {ξ = (ξ ↑ᴿ tm)}) (cong (_↑ˢ tm) (lift-⨟ˢᴿ {σ = σ} {ξ = ξ}))))) (compositionalityˢᴿ′ tm3)

  compositionalityˢᴿ : ∀ (x/t : S₁ ⊢[ m ] s) {σ₁ : S₁ →ˢ S₂} {ξ₂ : S₂ →ᴿ S₃} →
    (x/t [ σ₁ ]ˢ) [ ξ₂ ]ᴿ ≡ x/t [ (σ₁ ⨟ ⟨ ξ₂ ⟩) ]ˢ
  compositionalityˢᴿ x/t {σ₁ = σ} {ξ₂ = ξ} =
    trans (compositionalityˢᴿ′ x/t) (cong (x/t [_]ˢ) (⨟ˢᴿ-def σ ξ))

  lift-dist-compˢᴿ : ∀ {σ : S₁ →ˢ S₂} {ξ : S₂ →ᴿ S₃} →
    ((σ ↑ˢ s) ⨟ ⟨ ξ ↑ᴿ s ⟩) ≡ ((σ ⨟ ⟨ ξ ⟩) ↑ˢ s)
  lift-dist-compˢᴿ {σ = σ} {ξ = ξ} =
    trans (sym (⨟ˢᴿ-def (σ ↑ˢ _) (ξ ↑ᴿ _)))
          (trans lift-⨟ˢᴿ (cong (_↑ˢ _) (⨟ˢᴿ-def σ ξ)))

  lift-wk : ⟨ wkᴿ s ⟩ ⨟ (σ ↑ˢ s) ≡ σ ⨟ ⟨ wkᴿ s ⟩
  lift-wk {s = s} {σ = σ} = trans (⟨wk*⟩-lift idᴿ σ)
    (trans (cong (_⨟ˢᴿ wkᴿ s) comp-idₗ) (⨟ˢᴿ-def σ (wkᴿ s)))

  ⨟ˢᴿwk-lift : ∀ (σ₁ : S₁ →ˢ S₂) (σ₂ : S₂ →ˢ S₃) →
    (σ₁ ⨟ˢᴿ wkᴿ s) ⨟ (σ₂ ↑ˢ s) ≡ (σ₁ ⨟ σ₂) ⨟ˢᴿ wkᴿ s
  ⨟ˢᴿwk-lift []       σ₂ = refl
  ⨟ˢᴿwk-lift {s = s} (t ∙ˢ σ₁) σ₂ = cong2 _∙ˢ_
    (trans (compositionalityᴿˢ t)
      (trans (cong (t [_]ˢ) (trans lift-wk (sym (⨟ˢᴿ-def σ₂ (wkᴿ s)))))
             (sym (compositionalityˢᴿ′ t))))
    (⨟ˢᴿwk-lift σ₁ σ₂)

  lift-dist-compˢˢ : ((σ₁ ↑ˢ s) ⨟ (σ₂ ↑ˢ s)) ≡ ((σ₁ ⨟ σ₂) ↑ˢ s)
  lift-dist-compˢˢ {σ₁ = σ₁} {σ₂ = σ₂} = cong ((var zero) ∙ˢ_) (⨟ˢᴿwk-lift σ₁ σ₂)

  -- ══ Vˢ. monad laws, substitution world ═══════════════════════════
  compositionalityˢˢ : ∀ (x/t : S₁ ⊢[ m ] s) {σ₁ : S₁ →ˢ S₂} {σ₂ : S₂ →ˢ S₃} →
    (x/t [ σ₁ ]ˢ) [ σ₂ ]ˢ ≡ x/t [ (σ₁ ⨟ σ₂) ]ˢ
  compositionalityˢˢ zero    {σ₁ = t ∙ˢ σ₁} = refl
  compositionalityˢˢ (suc x) {σ₁ = t ∙ˢ σ₁} = compositionalityˢˢ x
  compositionalityˢˢ (var x) = compositionalityˢˢ x
  compositionalityˢˢ (Pi tm0 tm1)                                 = cong2 Pi (compositionalityˢˢ tm0) (trans (compositionalityˢˢ tm1) (cong (tm1 [_]ˢ) lift-dist-compˢˢ))
  compositionalityˢˢ (lam tm0 tm1)                                = cong2 lam (compositionalityˢˢ tm0) (trans (compositionalityˢˢ tm1) (cong (tm1 [_]ˢ) lift-dist-compˢˢ))
  compositionalityˢˢ (app tm0 tm1)                                = cong2 app (compositionalityˢˢ tm0) (compositionalityˢˢ tm1)
  compositionalityˢˢ U                                            = refl
  compositionalityˢˢ Nat                                          = refl
  compositionalityˢˢ zeroN                                        = refl
  compositionalityˢˢ (sucN tm0)                                   = cong1 sucN (compositionalityˢˢ tm0)
  compositionalityˢˢ (natrec tm0 tm1 tm2 tm3) {σ₁ = σ₁} {σ₂ = σ₂} = cong4 natrec (trans (compositionalityˢˢ tm0) (cong (tm0 [_]ˢ) lift-dist-compˢˢ)) (compositionalityˢˢ tm1) (trans (compositionalityˢˢ tm2) (cong (tm2 [_]ˢ) (trans (lift-dist-compˢˢ {σ₁ = (σ₁ ↑ˢ tm)} {σ₂ = (σ₂ ↑ˢ tm)}) (cong (_↑ˢ tm) (lift-dist-compˢˢ {σ₁ = σ₁} {σ₂ = σ₂}))))) (compositionalityˢˢ tm3)

  assoc : (σ₁ ⨟ σ₂) ⨟ σ₃ ≡ σ₁ ⨟ (σ₂ ⨟ σ₃)
  assoc {σ₁ = []}      = refl
  assoc {σ₁ = t ∙ˢ σ₁} = cong2 _∙ˢ_ (compositionalityˢˢ t) assoc

  comp-idᵣ : σ ⨟ ⟨ idᴿ ⟩ ≡ σ
  comp-idᵣ {σ = []}     = refl
  comp-idᵣ {σ = t ∙ˢ σ} = cong2 _∙ˢ_ (trans (coincidence t idᴿ) (right-idᴿ t)) comp-idᵣ

  ⨟ˢᴿwk-cons : ∀ (σ : S₁ →ˢ S₂) (t : S₃ ⊢ s) (τ : S₂ →ˢ S₃) →
    (σ ⨟ˢᴿ wkᴿ s) ⨟ (t ∙ˢ τ) ≡ σ ⨟ τ
  ⨟ˢᴿwk-cons []       t τ = refl
  ⨟ˢᴿwk-cons (u ∙ˢ σ) t τ =
    cong2 _∙ˢ_ (trans (compositionalityᴿˢ u) (cong (u [_]ˢ) interact)) (⨟ˢᴿwk-cons σ t τ)

  lift-cons : (σ ↑ˢ s) ⨟ (t ∙ˢ τ) ≡ t ∙ˢ (σ ⨟ τ)
  lift-cons {σ = σ} {t = t} {τ = τ} = cong (t ∙ˢ_) (⨟ˢᴿwk-cons σ t τ)

  -- ══ the collapse family: ⟨_⟩ is pushed back into the ᴿ world ═════
  ⟨⟩-comp : ⟨ ξ₁ ⟩ ⨟ ⟨ ξ₂ ⟩ ≡ ⟨ ξ₁ ⨟ᴿ ξ₂ ⟩
  ⟨⟩-comp {ξ₁ = []}      = refl
  ⟨⟩-comp {ξ₁ = x ∙ᴿ ξ₁} {ξ₂ = ξ₂} = cong2 _∙ˢ_ (coincidence-var x ξ₂) ⟨⟩-comp

  ⟨⟩-split-⨟ : ⟨ ξ₁ ⨟ᴿ ξ₂ ⟩ ⨟ σ ≡ ⟨ ξ₁ ⟩ ⨟ (⟨ ξ₂ ⟩ ⨟ σ)
  ⟨⟩-split-⨟ {ξ₁ = []}      = refl
  ⟨⟩-split-⨟ {ξ₁ = x ∙ᴿ ξ₁} = cong2 _∙ˢ_ (compositionalityᴿˢ-var x) ⟨⟩-split-⨟

  ⟨⟩-lift-cons : ⟨ ξ ↑ᴿ s ⟩ ⨟ (t ∙ˢ σ) ≡ t ∙ˢ (⟨ ξ ⟩ ⨟ σ)
  ⟨⟩-lift-cons {ξ = ξ} {t = t} {σ = σ} = cong (t ∙ˢ_) (⟨wk*⟩-cons ξ t σ)


  -- ══ VIˢ. completion companions, substitution world ═══════════════
  lift-wk-⨟ : ∀ {σ : S₁ →ˢ S₂} {τ : (s ∷ S₂) →ˢ S₃} →
    ⟨ wkᴿ s ⟩ ⨟ ((σ ↑ˢ s) ⨟ τ) ≡ σ ⨟ (⟨ wkᴿ s ⟩ ⨟ τ)
  lift-wk-⨟ {σ = σ} {τ = τ} =
    trans (sym (assoc {σ₁ = ⟨ wkᴿ _ ⟩} {σ₂ = σ ↑ˢ _} {σ₃ = τ}))
          (trans (cong (_⨟ τ) (lift-wk {σ = σ}))
                 (assoc {σ₁ = σ} {σ₂ = ⟨ wkᴿ _ ⟩} {σ₃ = τ}))

  lift-dist-compˢˢ-⨟ : ∀ {S₄ : Scope} {σ₁ : S₁ →ˢ S₂} {σ₂ : S₂ →ˢ S₃}
    {τ : (s ∷ S₃) →ˢ S₄} →
    (σ₁ ↑ˢ s) ⨟ ((σ₂ ↑ˢ s) ⨟ τ) ≡ ((σ₁ ⨟ σ₂) ↑ˢ s) ⨟ τ
  lift-dist-compˢˢ-⨟ {σ₁ = σ₁} {σ₂ = σ₂} {τ = τ} =
    trans (sym (assoc {σ₁ = σ₁ ↑ˢ _} {σ₂ = σ₂ ↑ˢ _} {σ₃ = τ}))
          (cong (_⨟ τ) (lift-dist-compˢˢ {σ₁ = σ₁} {σ₂ = σ₂}))

  lift-dist-compᴿˢ-⨟ : ∀ {S₄ : Scope} {ξ : S₁ →ᴿ S₂} {σ : S₂ →ˢ S₃}
    {τ : (s ∷ S₃) →ˢ S₄} →
    ⟨ ξ ↑ᴿ s ⟩ ⨟ ((σ ↑ˢ s) ⨟ τ) ≡ ((⟨ ξ ⟩ ⨟ σ) ↑ˢ s) ⨟ τ
  lift-dist-compᴿˢ-⨟ {ξ = ξ} {σ = σ} {τ = τ} =
    trans (sym (assoc {σ₁ = ⟨ ξ ↑ᴿ _ ⟩} {σ₂ = σ ↑ˢ _} {σ₃ = τ}))
          (cong (_⨟ τ) (lift-dist-compᴿˢ {ξ = ξ} {σ = σ}))

  lift-dist-compˢᴿ-⨟ : ∀ {S₄ : Scope} {σ : S₁ →ˢ S₂} {ξ : S₂ →ᴿ S₃}
    {τ : (s ∷ S₃) →ˢ S₄} →
    (σ ↑ˢ s) ⨟ (⟨ ξ ↑ᴿ s ⟩ ⨟ τ) ≡ ((σ ⨟ ⟨ ξ ⟩) ↑ˢ s) ⨟ τ
  lift-dist-compˢᴿ-⨟ {σ = σ} {ξ = ξ} {τ = τ} =
    trans (sym (assoc {σ₁ = σ ↑ˢ _} {σ₂ = ⟨ ξ ↑ᴿ _ ⟩} {σ₃ = τ}))
          (cong (_⨟ τ) (lift-dist-compˢᴿ {σ = σ} {ξ = ξ}))

  ⟨⟩-comp-⨟-interactᴿ : ∀ {ξ : S₁ →ᴿ S₂} {x : S₂ ∋ s} {τ : S₂ →ˢ S₃} →
    ⟨ wkᴿ s ⟩ ⨟ (⟨ x ∙ᴿ ξ ⟩ ⨟ τ) ≡ ⟨ ξ ⟩ ⨟ τ
  ⟨⟩-comp-⨟-interactᴿ {ξ = ξ} {x = x} {τ = τ} =
    trans (sym (assoc {σ₁ = ⟨ wkᴿ _ ⟩} {σ₂ = ⟨ x ∙ᴿ ξ ⟩} {σ₃ = τ}))
          (trans (cong (_⨟ τ) (⟨⟩-comp {ξ₁ = wkᴿ _} {ξ₂ = x ∙ᴿ ξ}))
                 (cong (λ z → ⟨ z ⟩ ⨟ τ) (interactᴿ {x = x} {ξ = ξ})))

  ⟨⟩-comp-⨟-lift-wkᴿ : ∀ {S₄ : Scope} {ξ : S₁ →ᴿ S₂} {τ : (s ∷ S₂) →ˢ S₄} →
    ⟨ wkᴿ s ⟩ ⨟ (⟨ ξ ↑ᴿ s ⟩ ⨟ τ) ≡ ⟨ ξ ⟩ ⨟ (⟨ wkᴿ s ⟩ ⨟ τ)
  ⟨⟩-comp-⨟-lift-wkᴿ {ξ = ξ} {τ = τ} =
    trans (sym (assoc {σ₁ = ⟨ wkᴿ _ ⟩} {σ₂ = ⟨ ξ ↑ᴿ _ ⟩} {σ₃ = τ}))
          (trans (cong (_⨟ τ) (⟨⟩-comp {ξ₁ = wkᴿ _} {ξ₂ = ξ ↑ᴿ _}))
          (trans (cong (λ z → ⟨ z ⟩ ⨟ τ) (lift-wkᴿ {ξ = ξ}))
          (trans (cong (_⨟ τ) (sym (⟨⟩-comp {ξ₁ = ξ} {ξ₂ = wkᴿ _})))
                 (assoc {σ₁ = ⟨ ξ ⟩} {σ₂ = ⟨ wkᴿ _ ⟩} {σ₃ = τ}))))

  ⟨⟩-comp-⨟-lift-dist-compᴿᴿ : ∀ {S₄ : Scope} {ξ₁ : S₁ →ᴿ S₂} {ξ₂ : S₂ →ᴿ S₃}
    {τ : (s ∷ S₃) →ˢ S₄} →
    ⟨ ξ₁ ↑ᴿ s ⟩ ⨟ (⟨ ξ₂ ↑ᴿ s ⟩ ⨟ τ) ≡ ⟨ (ξ₁ ⨟ᴿ ξ₂) ↑ᴿ s ⟩ ⨟ τ
  ⟨⟩-comp-⨟-lift-dist-compᴿᴿ {ξ₁ = ξ₁} {ξ₂ = ξ₂} {τ = τ} =
    trans (sym (assoc {σ₁ = ⟨ ξ₁ ↑ᴿ _ ⟩} {σ₂ = ⟨ ξ₂ ↑ᴿ _ ⟩} {σ₃ = τ}))
          (trans (cong (_⨟ τ) (⟨⟩-comp {ξ₁ = ξ₁ ↑ᴿ _} {ξ₂ = ξ₂ ↑ᴿ _}))
                 (cong (λ z → ⟨ z ⟩ ⨟ τ) (lift-dist-compᴿᴿ {ξ₁ = ξ₁} {ξ₂ = ξ₂})))

  ⟨⟩-split-tail : ∀ {S₄ : Scope} {σ : S₁ →ˢ S₂} {ξ : S₂ →ᴿ S₃}
    {ξ′ : (s ∷ S₃) →ᴿ S₄} →
    (σ ↑ˢ s) ⨟ ⟨ (ξ ↑ᴿ s) ⨟ᴿ ξ′ ⟩ ≡ ((σ ⨟ ⟨ ξ ⟩) ↑ˢ s) ⨟ ⟨ ξ′ ⟩
  ⟨⟩-split-tail {σ = σ} {ξ = ξ} {ξ′ = ξ′} =
    trans (cong ((σ ↑ˢ _) ⨟_) (sym (⟨⟩-comp {ξ₁ = ξ ↑ᴿ _} {ξ₂ = ξ′})))
          (trans (sym (assoc {σ₁ = σ ↑ˢ _} {σ₂ = ⟨ ξ ↑ᴿ _ ⟩} {σ₃ = ⟨ ξ′ ⟩}))
                 (cong (_⨟ ⟨ ξ′ ⟩) (lift-dist-compˢᴿ {σ = σ} {ξ = ξ})))

  compositionalityᴿˢ-⨟-var : ∀ {x : S₁ ∋ s} {ξ : S₁ →ᴿ S₂} {σ : S₂ →ˢ S₃} →
    x [ (⟨ ξ ⟩ ⨟ σ) ]ˢ ≡ (x [ ξ ]ᴿ) [ σ ]ˢ
  compositionalityᴿˢ-⨟-var {x = x} = sym (compositionalityᴿˢ-var x)

  lift-dist-compᴿˢ-var : ∀ {x : (s ∷ S₁) ∋ s′} {ξ : S₁ →ᴿ S₂} {σ : S₂ →ˢ S₃} →
    (x [ (ξ ↑ᴿ s) ]ᴿ) [ (σ ↑ˢ s) ]ˢ ≡ x [ ((⟨ ξ ⟩ ⨟ σ) ↑ˢ s) ]ˢ
  lift-dist-compᴿˢ-var {x = x} {ξ = ξ} {σ = σ} =
    trans (compositionalityᴿˢ-var x)
          (cong (λ z → x [ z ]ˢ) (lift-dist-compᴿˢ {ξ = ξ} {σ = σ}))

  lift-dist-compᴿˢ-⨟-var : ∀ {S₄ : Scope} {x : (s ∷ S₁) ∋ s′} {ξ : S₁ →ᴿ S₂}
    {σ : S₂ →ˢ S₃} {τ : (s ∷ S₃) →ˢ S₄} →
    (x [ (ξ ↑ᴿ s) ]ᴿ) [ ((σ ↑ˢ s) ⨟ τ) ]ˢ ≡ x [ (((⟨ ξ ⟩ ⨟ σ) ↑ˢ s) ⨟ τ) ]ˢ
  lift-dist-compᴿˢ-⨟-var {x = x} {ξ = ξ} {σ = σ} {τ = τ} =
    trans (compositionalityᴿˢ-var x)
          (trans (cong (λ z → x [ z ]ˢ)
                       (sym (assoc {σ₁ = ⟨ ξ ↑ᴿ _ ⟩} {σ₂ = σ ↑ˢ _} {σ₃ = τ})))
                 (cong (λ z → x [ (z ⨟ τ) ]ˢ) (lift-dist-compᴿˢ {ξ = ξ} {σ = σ})))

  ⟨⟩-lift-cons-var : ∀ {x : (s ∷ S₁) ∋ s′} {ξ : S₁ →ᴿ S₂} {t : S₃ ⊢ s}
    {σ : S₂ →ˢ S₃} →
    (x [ (ξ ↑ᴿ s) ]ᴿ) [ (t ∙ˢ σ) ]ˢ ≡ x [ (t ∙ˢ (⟨ ξ ⟩ ⨟ σ)) ]ˢ
  ⟨⟩-lift-cons-var {x = x} {ξ = ξ} {t = t} {σ = σ} =
    trans (compositionalityᴿˢ-var x)
          (cong (λ z → x [ z ]ˢ) (⟨⟩-lift-cons {ξ = ξ} {t = t} {σ = σ}))

  def-↑ˢ-zero-⨟ : ∀ {σ : S₁ →ˢ S₂} {τ : (s ∷ S₂) →ˢ S₃} →
    zero [ ((σ ↑ˢ s) ⨟ τ) ]ˢ ≡ zero [ τ ]ˢ
  def-↑ˢ-zero-⨟ {σ = σ} {τ = τ} = lookup-⨟ˢ zero (σ ↑ˢ _) τ

  def-↑ˢ-suc-⨟ : ∀ {x : S₁ ∋ s′} {σ : S₁ →ˢ S₂} {τ : (s ∷ S₂) →ˢ S₃} →
    (suc x) [ ((σ ↑ˢ s) ⨟ τ) ]ˢ ≡ x [ (σ ⨟ (⟨ wkᴿ s ⟩ ⨟ τ)) ]ˢ
  def-↑ˢ-suc-⨟ {x = x} {σ = σ} {τ = τ} =
    trans (lookup-⨟ˢ (suc x) (σ ↑ˢ _) τ)
          (trans (cong (_[ τ ]ˢ) (def-↑ˢ-suc {x = x} {σ = σ}))
                 (trans (sym (lookup-⨟ˢ x (σ ⨟ ⟨ wkᴿ _ ⟩) τ))
                        (cong (x [_]ˢ) (assoc {σ₁ = σ} {σ₂ = ⟨ wkᴿ _ ⟩} {σ₃ = τ}))))

  lift-id : (⟨ idᴿ {S} ⟩ ↑ˢ s) ≡ ⟨ idᴿ ⟩
  lift-id = ⟨⟩-lift



  -- ══ IIˢ. traversal rules, substitution world ═════════════════════
  inst-var : (var x) [ σ ]ˢ ≡ x [ σ ]ˢ
  inst-Pi     : (Pi tm0 tm1) [ σ ]ˢ             ≡ Pi (tm0 [ σ ]ˢ) (tm1 [ σ ↑ˢ tm ]ˢ)
  inst-lam    : (lam tm0 tm1) [ σ ]ˢ            ≡ lam (tm0 [ σ ]ˢ) (tm1 [ σ ↑ˢ tm ]ˢ)
  inst-app    : (app tm0 tm1) [ σ ]ˢ            ≡ app (tm0 [ σ ]ˢ) (tm1 [ σ ]ˢ)
  inst-U      : U {S = S} [ σ ]ˢ                ≡ U
  inst-Nat    : Nat {S = S} [ σ ]ˢ              ≡ Nat
  inst-zeroN  : zeroN {S = S} [ σ ]ˢ            ≡ zeroN
  inst-sucN   : (sucN tm0) [ σ ]ˢ               ≡ sucN (tm0 [ σ ]ˢ)
  inst-natrec : (natrec tm0 tm1 tm2 tm3) [ σ ]ˢ ≡ natrec (tm0 [ σ ↑ˢ tm ]ˢ) (tm1 [ σ ]ˢ) (tm2 [ (σ ↑ˢ tm) ↑ˢ tm ]ˢ) (tm3 [ σ ]ˢ)
  inst-var = refl
  inst-Pi     = refl
  inst-lam    = refl
  inst-app    = refl
  inst-U      = refl
  inst-Nat    = refl
  inst-zeroN  = refl
  inst-sucN   = refl
  inst-natrec = refl
  lift*-idᴿ b zero    = refl
  lift*-idᴿ {S = S} b (suc n) =
    trans (cong (_↑ᴿ b) {x = idᴿ {S} ↑ᴿ*[ b ] n} {y = idᴿ} (lift*-idᴿ {S = S} b n))
          (lift-idᴿ {S = ext* b n S} {s = b})
  lift*-dist-compᴿᴿ b zero = refl
  lift*-dist-compᴿᴿ {ξ₁ = ξ₁} {ξ₂ = ξ₂} b (suc n) =
    trans (lift-dist-compᴿᴿ {ξ₁ = ξ₁ ↑ᴿ*[ b ] n} {s = b} {ξ₂ = ξ₂ ↑ᴿ*[ b ] n})
          (cong (_↑ᴿ b) {x = (ξ₁ ↑ᴿ*[ b ] n) ⨟ᴿ (ξ₂ ↑ᴿ*[ b ] n)} {y = (ξ₁ ⨟ᴿ ξ₂) ↑ᴿ*[ b ] n} (lift*-dist-compᴿᴿ {ξ₁ = ξ₁} {ξ₂ = ξ₂} b n))
  lift*-dist-compᴿˢ b zero = refl
  lift*-dist-compᴿˢ b (suc n) {ξ = ξ} {σ = σ} =
    trans (lift-dist-compᴿˢ {ξ = ξ ↑ᴿ*[ b ] n} {s = b} {σ = σ ↑ˢ*[ b ] n})
          (cong (_↑ˢ b) {x = ⟨ ξ ↑ᴿ*[ b ] n ⟩ ⨟ (σ ↑ˢ*[ b ] n)} {y = (⟨ ξ ⟩ ⨟ σ) ↑ˢ*[ b ] n} (lift*-dist-compᴿˢ b n {ξ = ξ} {σ = σ}))
  lift*-dist-compˢᴿ b zero = refl
  lift*-dist-compˢᴿ b (suc n) {σ = σ} {ξ = ξ} =
    trans (lift-dist-compˢᴿ {s = b} {σ = σ ↑ˢ*[ b ] n} {ξ = ξ ↑ᴿ*[ b ] n})
          (cong (_↑ˢ b) {x = (σ ↑ˢ*[ b ] n) ⨟ ⟨ ξ ↑ᴿ*[ b ] n ⟩} {y = (σ ⨟ ⟨ ξ ⟩) ↑ˢ*[ b ] n} (lift*-dist-compˢᴿ b n {σ = σ} {ξ = ξ}))
  lift*-dist-compˢˢ b zero = refl
  lift*-dist-compˢˢ {σ₁ = σ₁} {σ₂ = σ₂} b (suc n) =
    trans (lift-dist-compˢˢ {σ₁ = σ₁ ↑ˢ*[ b ] n} {s = b} {σ₂ = σ₂ ↑ˢ*[ b ] n})
          (cong (_↑ˢ b) {x = (σ₁ ↑ˢ*[ b ] n) ⨟ (σ₂ ↑ˢ*[ b ] n)} {y = (σ₁ ⨟ σ₂) ↑ˢ*[ b ] n} (lift*-dist-compˢˢ {σ₁ = σ₁} {σ₂ = σ₂} b n))
  lift*-⨟ˢᴿ b zero = refl
  lift*-⨟ˢᴿ b (suc n) {σ = σ} {ξ = ξ} =
    trans (lift-⨟ˢᴿ {σ = σ ↑ˢ*[ b ] n} {ξ = ξ ↑ᴿ*[ b ] n})
          (cong (_↑ˢ b) {x = (σ ↑ˢ*[ b ] n) ⨟ˢᴿ (ξ ↑ᴿ*[ b ] n)}
                        {y = (σ ⨟ˢᴿ ξ) ↑ˢ*[ b ] n}
                (lift*-⨟ˢᴿ b n {σ = σ} {ξ = ξ}))
  ⟨⟩-lift* b zero    = refl
  ⟨⟩-lift* {ξ = ξ} b (suc n) =
    trans (cong (_↑ˢ b) {x = ⟨ ξ ⟩ ↑ˢ*[ b ] n} {y = ⟨ ξ ↑ᴿ*[ b ] n ⟩} (⟨⟩-lift* {ξ = ξ} b n))
          (⟨⟩-lift {ξ = ξ ↑ᴿ*[ b ] n} {s = b})

  lift*-dist-compᴿᴿ-var b n {x = x} {ξ₁ = ξ₁} {ξ₂ = ξ₂} =
    trans (sym (compositionalityᴿᴿ-var x {ξ₁ = ξ₁ ↑ᴿ*[ b ] n} {ξ₂ = ξ₂ ↑ᴿ*[ b ] n}))
          (cong (λ z → x [ z ]ᴿ) {x = (ξ₁ ↑ᴿ*[ b ] n) ⨟ᴿ (ξ₂ ↑ᴿ*[ b ] n)} {y = (ξ₁ ⨟ᴿ ξ₂) ↑ᴿ*[ b ] n} (lift*-dist-compᴿᴿ {ξ₁ = ξ₁} {ξ₂ = ξ₂} b n))
  lift*-dist-compᴿᴿ-⨟ᴿ b n {ξ₁ = ξ₁} {ξ₂ = ξ₂} {ξ′ = ξ′} =
    trans (sym (assocᴿ {ξ₁ = ξ₁ ↑ᴿ*[ b ] n} {ξ₂ = ξ₂ ↑ᴿ*[ b ] n} {ξ₃ = ξ′}))
          (cong (_⨟ᴿ ξ′) {x = (ξ₁ ↑ᴿ*[ b ] n) ⨟ᴿ (ξ₂ ↑ᴿ*[ b ] n)} {y = (ξ₁ ⨟ᴿ ξ₂) ↑ᴿ*[ b ] n} (lift*-dist-compᴿᴿ {ξ₁ = ξ₁} {ξ₂ = ξ₂} b n))
  lift*-dist-compˢˢ-⨟ b n {σ₁ = σ₁} {σ₂ = σ₂} {τ = τ} =
    trans (sym (assoc {σ₁ = σ₁ ↑ˢ*[ b ] n} {σ₂ = σ₂ ↑ˢ*[ b ] n} {σ₃ = τ}))
          (cong (_⨟ τ) {x = (σ₁ ↑ˢ*[ b ] n) ⨟ (σ₂ ↑ˢ*[ b ] n)} {y = (σ₁ ⨟ σ₂) ↑ˢ*[ b ] n} (lift*-dist-compˢˢ {σ₁ = σ₁} {σ₂ = σ₂} b n))
  lift*-dist-compᴿˢ-⨟ b n {ξ = ξ} {σ = σ} {τ = τ} =
    trans (sym (assoc {σ₁ = ⟨ ξ ↑ᴿ*[ b ] n ⟩} {σ₂ = σ ↑ˢ*[ b ] n} {σ₃ = τ}))
          (cong (_⨟ τ) {x = ⟨ ξ ↑ᴿ*[ b ] n ⟩ ⨟ (σ ↑ˢ*[ b ] n)} {y = (⟨ ξ ⟩ ⨟ σ) ↑ˢ*[ b ] n} (lift*-dist-compᴿˢ b n {ξ = ξ} {σ = σ}))
  lift*-dist-compˢᴿ-⨟ b n {σ = σ} {ξ = ξ} {τ = τ} =
    trans (sym (assoc {σ₁ = σ ↑ˢ*[ b ] n} {σ₂ = ⟨ ξ ↑ᴿ*[ b ] n ⟩} {σ₃ = τ}))
          (cong (_⨟ τ) {x = (σ ↑ˢ*[ b ] n) ⨟ ⟨ ξ ↑ᴿ*[ b ] n ⟩} {y = (σ ⨟ ⟨ ξ ⟩) ↑ˢ*[ b ] n} (lift*-dist-compˢᴿ b n {σ = σ} {ξ = ξ}))
  lift*-dist-compᴿˢ-var b n {x = x} {ξ = ξ} {σ = σ} =
    trans (compositionalityᴿˢ-var x {ξ = ξ ↑ᴿ*[ b ] n} {σ = σ ↑ˢ*[ b ] n})
          (cong (λ z → x [ z ]ˢ) {x = ⟨ ξ ↑ᴿ*[ b ] n ⟩ ⨟ (σ ↑ˢ*[ b ] n)} {y = (⟨ ξ ⟩ ⨟ σ) ↑ˢ*[ b ] n} (lift*-dist-compᴿˢ b n {ξ = ξ} {σ = σ}))
  ⟨⟩-comp-⨟-lift*-dist-compᴿᴿ b n {ξ₁ = ξ₁} {ξ₂ = ξ₂} {τ = τ} =
    trans (sym (assoc {σ₁ = ⟨ ξ₁ ↑ᴿ*[ b ] n ⟩} {σ₂ = ⟨ ξ₂ ↑ᴿ*[ b ] n ⟩} {σ₃ = τ}))
          (trans (cong (_⨟ τ) {x = ⟨ ξ₁ ↑ᴿ*[ b ] n ⟩ ⨟ ⟨ ξ₂ ↑ᴿ*[ b ] n ⟩} {y = ⟨ (ξ₁ ↑ᴿ*[ b ] n) ⨟ᴿ (ξ₂ ↑ᴿ*[ b ] n) ⟩} (⟨⟩-comp {ξ₁ = ξ₁ ↑ᴿ*[ b ] n} {ξ₂ = ξ₂ ↑ᴿ*[ b ] n}))
                 (cong (λ z → ⟨ z ⟩ ⨟ τ) {x = (ξ₁ ↑ᴿ*[ b ] n) ⨟ᴿ (ξ₂ ↑ᴿ*[ b ] n)} {y = (ξ₁ ⨟ᴿ ξ₂) ↑ᴿ*[ b ] n} (lift*-dist-compᴿᴿ {ξ₁ = ξ₁} {ξ₂ = ξ₂} b n)))
  lift*-dist-compᴿˢ-⨟-var b n {x = x} {ξ = ξ} {σ = σ} {τ = τ} =
    trans (compositionalityᴿˢ-var x {ξ = ξ ↑ᴿ*[ b ] n} {σ = (σ ↑ˢ*[ b ] n) ⨟ τ})
          (trans (cong (λ z → x [ z ]ˢ) {x = ⟨ ξ ↑ᴿ*[ b ] n ⟩ ⨟ ((σ ↑ˢ*[ b ] n) ⨟ τ)} {y = (⟨ ξ ↑ᴿ*[ b ] n ⟩ ⨟ (σ ↑ˢ*[ b ] n)) ⨟ τ}
                       (sym (assoc {σ₁ = ⟨ ξ ↑ᴿ*[ b ] n ⟩} {σ₂ = σ ↑ˢ*[ b ] n} {σ₃ = τ})))
                 (cong (λ z → x [ (z ⨟ τ) ]ˢ) {x = ⟨ ξ ↑ᴿ*[ b ] n ⟩ ⨟ (σ ↑ˢ*[ b ] n)} {y = (⟨ ξ ⟩ ⨟ σ) ↑ˢ*[ b ] n} (lift*-dist-compᴿˢ b n {ξ = ξ} {σ = σ})))
  ⟨⟩-split*-tail b n {σ = σ} {ξ = ξ} {ξ′ = ξ′} =
    trans (cong ((σ ↑ˢ*[ b ] n) ⨟_) {x = ⟨ (ξ ↑ᴿ*[ b ] n) ⨟ᴿ ξ′ ⟩} {y = ⟨ ξ ↑ᴿ*[ b ] n ⟩ ⨟ ⟨ ξ′ ⟩}
                (sym (⟨⟩-comp {ξ₁ = ξ ↑ᴿ*[ b ] n} {ξ₂ = ξ′})))
          (trans (sym (assoc {σ₁ = σ ↑ˢ*[ b ] n} {σ₂ = ⟨ ξ ↑ᴿ*[ b ] n ⟩} {σ₃ = ⟨ ξ′ ⟩}))
                 (cong (_⨟ ⟨ ξ′ ⟩) {x = (σ ↑ˢ*[ b ] n) ⨟ ⟨ ξ ↑ᴿ*[ b ] n ⟩} {y = (σ ⨟ ⟨ ξ ⟩) ↑ˢ*[ b ] n} (lift*-dist-compˢᴿ b n {σ = σ} {ξ = ξ})))

-- ═══ The completed two-world system ════════════════════════════════
--
-- The vector model needs no completion families.  The `-⨟` continuation
-- companions, the mode-V `-var` companions and the coercion family that
-- the function model registers are all subsumed here, because a vector
-- composition reduces structurally where a function composition is
-- stuck.  closure-vec.agda states every one of those absences and
-- checks it by `refl`.

-- 90 rules -- 57 signature-independent, 15 for the
-- iterated (variable-arity) lifting, 18 traversal rules (one instᴿ-*
-- and one inst-* per constructor, plus the variable case).

{-# REWRITE
  def-wkᴿ def-∙ᴿ-zero def-∙ᴿ-suc def-↑ᴿ-zero def-↑ᴿ-suc
  instᴿ-var instᴿ-Pi instᴿ-lam instᴿ-app instᴿ-U instᴿ-Nat instᴿ-zeroN
  instᴿ-sucN instᴿ-natrec
  assocᴿ comp-idₗᴿ comp-idᵣᴿ interactᴿ
  lift-idᴿ lift-dist-compᴿᴿ lift-wkᴿ
  right-idᴿ compositionalityᴿᴿ-var compositionalityᴿᴿ
  lift-dist-compᴿᴿ-var lift-consᴿ-var interactᴿ-⨟ᴿ lift-wkᴿ-⨟ᴿ lift-dist-compᴿᴿ-⨟ᴿ
  coincidence-var def-∙ˢ-zero def-∙ˢ-suc def-↑ˢ-zero def-↑ˢ-suc
  inst-var inst-Pi inst-lam inst-app inst-U inst-Nat inst-zeroN inst-sucN
  inst-natrec
  assoc dist interact comp-idₗ comp-idᵣ
  lift-wk lift-cons lift-dist-compˢˢ lift-wk-⨟ lift-dist-compˢˢ-⨟
  compositionalityᴿˢ-⨟-var def-↑ˢ-zero-⨟ def-↑ˢ-suc-⨟
  compositionalityˢˢ compositionalityᴿˢ compositionalityˢᴿ
  lift-dist-compᴿˢ lift-dist-compˢᴿ lift-dist-compᴿˢ-⨟ lift-dist-compˢᴿ-⨟
  lift-dist-compᴿˢ-var lift-dist-compᴿˢ-⨟-var ⟨⟩-lift-cons-var
  ⟨⟩-comp-⨟-lift-wkᴿ ⟨⟩-comp-⨟-interactᴿ ⟨⟩-comp-⨟-lift-dist-compᴿᴿ ⟨⟩-split-tail
  coincidence ⟨⟩-comp ⟨⟩-split-⨟ ⟨⟩-lift ⟨⟩-lift-cons
  lift*-idᴿ lift*-dist-compᴿᴿ lift*-dist-compᴿˢ lift*-dist-compˢᴿ
  lift*-dist-compˢˢ ⟨⟩-lift* lift*-dist-compᴿᴿ-var lift*-dist-compᴿᴿ-⨟ᴿ
  lift*-dist-compˢˢ-⨟ lift*-dist-compᴿˢ-⨟ lift*-dist-compˢᴿ-⨟
  lift*-dist-compᴿˢ-var ⟨⟩-comp-⨟-lift*-dist-compᴿᴿ lift*-dist-compᴿˢ-⨟-var
  ⟨⟩-split*-tail
#-}

-- ─── the derived operations ─────────────────────────────────────────
-- Neither is primitive and neither has rules of its own: weakening is a
-- renaming, single substitution is a cons onto the identity.  The
-- rewrite system computes through both without knowing they exist.

weaken : S ⊢ s → (s′ ∷ S) ⊢ s
weaken t = t [ wkᴿ _ ]ᴿ

_[_]₀ : (s′ ∷ S) ⊢ s → S ⊢ s′ → S ⊢ s
t [ t′ ]₀ = t [ (t′ ∙ˢ idˢ) ]ˢ

-- ═══ SYNTAX OF REDUCTION, CONVERSION AND TYPING ═══════════════════════════════════════════

-- Martin-Löf type theory on top of the generated σ-calculus core.
--
-- PRESENTATION:
--   * ONE syntactic sort.  Types ARE terms.
--   * Extrinsic (Curry/PTS) typing:  Γ ⊢ t ∶ A  with A : S ⊢ tm.
--   * Definitional equality is UNTYPED conversion _≡β_, the
--     reflexive-symmetric-transitive closure of the compatible
--     one-step reduction _↪_ on raw terms (Barendregt/PTS style).
--   * Type : Type.  Logically inconsistent (Girard) but type-SAFE.



-- ─── contexts: the framework's telescopes, verbatim from systemf.agda ─

↑ˢᵗ_ : Sort → Sort
↑ˢᵗ tm = tm

_∶⊢_ : Scope → Sort → Set
S ∶⊢ s = S ⊢ (↑ˢᵗ s)

depth : S ∋ s → ℕ
depth zero    = zero
depth (suc x) = suc (depth x)

drop-∈ : S ∋ s → Scope → Scope
drop-∈ x S = drop (suc (depth x)) S

Ctx : Scope → Set
Ctx S = ∀ s → (x : S ∋ s) → drop-∈ x S ∶⊢ s

_∷ₜ_ : S ∶⊢ s → Ctx S → Ctx (s ∷ S)
(t ∷ₜ Γ) _ zero    = t
(t ∷ₜ Γ) _ (suc x) = Γ _ x

wk-drop-∈ : (x : S ∋ s) → drop-∈ x S ⊢ s′ → S ⊢ s′
wk-drop-∈ zero    t = weaken t
wk-drop-∈ (suc x) t = weaken (wk-drop-∈ x t)

wk-telescope : Ctx S → S ∋ s → S ∶⊢ s
wk-telescope Γ x = wk-drop-∈ x (Γ _ x)

_∋_∶_ : Ctx S → S ∋ s → S ∶⊢ s → Set
Γ ∋ x ∶ t = wk-telescope Γ x ≡ t

variable
  Γ Γ₁ Γ₂ : Ctx S
  A B A′ B′ P z sc n f a b : S ⊢ tm

-- ─── the successor-branch motive ────────────────────────────────────
-- P lives over (Nat ∷ S).  The successor branch is checked in
-- (P ∷ Nat ∷ S) at "P (suc n)": P with its variable set to
-- sucN (var zero), then weakened past the induction hypothesis.

sucMotive : (tm ∷ S) ⊢ tm → (tm ∷ tm ∷ S) ⊢ tm
sucMotive P = weaken (P [ sucN (var zero) ∙ˢ wkˢ tm ]ˢ)

-- ─── one-step reduction on RAW terms (β and ι, full congruence) ─────

data _↪_ : S ⊢ tm → S ⊢ tm → Set where
  β-app   : app (lam A b) a ↪ (b [ a ]₀)
  ι-zero  : natrec P z sc zeroN ↪ z
  ι-suc   : natrec P z sc (sucN n) ↪ (sc [ natrec P z sc n ∙ˢ (n ∙ˢ idˢ) ]ˢ)

  ξ-Pi₁     : A ↪ A′ → Pi A B ↪ Pi A′ B
  ξ-Pi₂     : B ↪ B′ → Pi A B ↪ Pi A B′
  ξ-lam₁    : A ↪ A′ → lam A b ↪ lam A′ b
  ξ-lam₂    : b ↪ B′ → lam A b ↪ lam A B′
  ξ-app₁    : f ↪ A′ → app f a ↪ app A′ a
  ξ-app₂    : a ↪ A′ → app f a ↪ app f A′
  ξ-sucN    : n ↪ A′ → sucN n ↪ sucN A′
  ξ-natrec₁ : P ↪ A′ → natrec P z sc n ↪ natrec A′ z sc n
  ξ-natrec₂ : z ↪ A′ → natrec P z sc n ↪ natrec P A′ sc n
  ξ-natrec₃ : sc ↪ B′ → natrec P z sc n ↪ natrec P z B′ n
  ξ-natrec₄ : n ↪ A′ → natrec P z sc n ↪ natrec P z sc A′

-- ─── untyped conversion: the definitional equality of types ─────────

data _≡β_ : S ⊢ tm → S ⊢ tm → Set where
  β-refl  : A ≡β A
  β-step  : A ↪ B → A ≡β B
  β-sym   : A ≡β B → B ≡β A
  β-trans : A ≡β B → B ≡β A′ → A ≡β A′

-- ─── the typing judgment ────────────────────────────────────────────

data _⊢_∶_ : Ctx S → S ⊢ tm → S ⊢ tm → Set where
  ⊢var : ∀ {x : S ∋ tm} →
    Γ ∋ x ∶ A →
    Γ ⊢ (var x) ∶ A

  ⊢U : Γ ⊢ U ∶ U

  ⊢Pi :
    Γ ⊢ A ∶ U →
    (A ∷ₜ Γ) ⊢ B ∶ U →
    Γ ⊢ (Pi A B) ∶ U

  ⊢lam :
    Γ ⊢ A ∶ U →
    (A ∷ₜ Γ) ⊢ b ∶ B →
    Γ ⊢ (lam A b) ∶ (Pi A B)

  ⊢app :
    Γ ⊢ f ∶ (Pi A B) →
    Γ ⊢ a ∶ A →
    Γ ⊢ (app f a) ∶ (B [ a ]₀)

  ⊢Nat : Γ ⊢ Nat ∶ U

  ⊢zeroN : Γ ⊢ zeroN ∶ Nat

  ⊢sucN :
    Γ ⊢ n ∶ Nat →
    Γ ⊢ (sucN n) ∶ Nat

  ⊢natrec :
    (Nat ∷ₜ Γ) ⊢ P ∶ U →
    Γ ⊢ z ∶ (P [ zeroN ]₀) →
    (P ∷ₜ (Nat ∷ₜ Γ)) ⊢ sc ∶ (sucMotive P) →
    Γ ⊢ n ∶ Nat →
    Γ ⊢ (natrec P z sc n) ∶ (P [ n ]₀)

  -- NOTE.  The well-formedness premise `Γ ⊢ B ∶ U` is deliberately
  -- OMITTED.  Keeping it would force the validity ("type correctness")
  -- lemma  Γ ⊢ t ∶ A → Γ ⊢ A ∶ U,  whose ⊢var case needs a separate
  -- context-well-formedness judgment.  That machinery is orthogonal to
  -- the substitution question this experiment measures.  The cost is
  -- that the system admits Γ ⊢ t ∶ B for some ill-formed B; it does not
  -- affect preservation, progress, or any substitution count.
  ⊢conv :
    Γ ⊢ a ∶ A →
    A ≡β B →
    Γ ⊢ a ∶ B

-- ═══ CONSEQUENCES OF CHURCH-ROSSER ═══════════════════════════════════════════

-- Consequences of Church-Rosser for the untyped calculus.
--
-- Church-Rosser for the untyped calculus, PROVED below by Takahashi's
-- method.  Everything in this section is
-- PROVED from it.  CR is the Takahashi/parallel-reduction theorem for
-- the untyped β/ι calculus; it has nothing to do with the substitution
-- framework, which is why it is assumed rather than proved.



-- multi-step reduction
data _↠_ : S ⊢ tm → S ⊢ tm → Set where
  ↠-refl : A ↠ A
  ↠-step : A ↪ B → B ↠ A′ → A ↠ A′

↠→≡β : ∀ {S} {A B : S ⊢ tm} → A ↠ B → A ≡β B
↠→≡β ↠-refl        = β-refl
↠→≡β (↠-step r rs) = β-trans (β-step r) (↠→≡β rs)

-- ════════════════════════════════════════════════════════════════════
-- CHURCH-ROSSER, PROVED.  Takahashi's method of complete developments.
--
-- No postulate, no hole, no TERMINATING pragma.  The only substitution
-- fact the proof needs is that parallel reduction is stable under
-- substitutions that agree pointwise up to ⇛; every equation that this
-- raises -- including the β-redex law and the TWO-VARIABLE ι-suc law --
-- is already one of the 89 rewrite rules, so each of them closes by
-- `refl` and none of them is stated by hand.
-- ════════════════════════════════════════════════════════════════════

variable
  P′ z′ sc′ n′ f′ a′ b′ : S ⊢ tm

-- ─── 1.  parallel reduction ─────────────────────────────────────────
-- One constructor per term former, plus one per redex form.

infix 3 _⇛_

data _⇛_ : S ⊢ tm → S ⊢ tm → Set where
  ⇛-var    : ∀ {S} {x : S ∋ tm} → var x ⇛ var x
  ⇛-U      : U {S = S} ⇛ U
  ⇛-Nat    : Nat {S = S} ⇛ Nat
  ⇛-zeroN  : zeroN {S = S} ⇛ zeroN
  ⇛-Pi     : A ⇛ A′ → B ⇛ B′ → Pi A B ⇛ Pi A′ B′
  ⇛-lam    : A ⇛ A′ → b ⇛ b′ → lam A b ⇛ lam A′ b′
  ⇛-app    : f ⇛ f′ → a ⇛ a′ → app f a ⇛ app f′ a′
  ⇛-sucN   : n ⇛ n′ → sucN n ⇛ sucN n′
  ⇛-natrec : P ⇛ P′ → z ⇛ z′ → sc ⇛ sc′ → n ⇛ n′ →
             natrec P z sc n ⇛ natrec P′ z′ sc′ n′
  ⇛-beta   : b ⇛ b′ → a ⇛ a′ → app (lam A b) a ⇛ (b′ [ a′ ]₀)
  ⇛-ιzero  : z ⇛ z′ → natrec P z sc zeroN ⇛ z′
  ⇛-ιsuc   : P ⇛ P′ → z ⇛ z′ → sc ⇛ sc′ → n ⇛ n′ →
             natrec P z sc (sucN n) ⇛
             (sc′ [ natrec P′ z′ sc′ n′ ∙ˢ (n′ ∙ˢ idˢ) ]ˢ)

⇛-refl : ∀ {S} (t : S ⊢ tm) → t ⇛ t
⇛-refl (var x)             = ⇛-var
⇛-refl U                   = ⇛-U
⇛-refl Nat                 = ⇛-Nat
⇛-refl zeroN               = ⇛-zeroN
⇛-refl (Pi A B)            = ⇛-Pi (⇛-refl A) (⇛-refl B)
⇛-refl (lam A b)           = ⇛-lam (⇛-refl A) (⇛-refl b)
⇛-refl (app f a)           = ⇛-app (⇛-refl f) (⇛-refl a)
⇛-refl (sucN n)            = ⇛-sucN (⇛-refl n)
⇛-refl (natrec P z sc n)   = ⇛-natrec (⇛-refl P) (⇛-refl z) (⇛-refl sc) (⇛-refl n)

-- ─── 2.  ⇛ is stable under renaming ─────────────────────────────────
-- The three redex cases PIN the constructor's implicits, exactly as
-- `↪-sub` does above: the two-world rule set has already rewritten the
-- goal's index, so Agda can no longer read the arguments back off it.
-- Once pinned every case closes by the constructor alone -- the β law
-- and the two-variable ι-suc law are both definitional.

⇛-ren : ∀ {S₁ S₂} {t t′ : S₁ ⊢ tm} {ξ : S₁ →ᴿ S₂} →
  t ⇛ t′ → (t [ ξ ]ᴿ) ⇛ (t′ [ ξ ]ᴿ)
⇛-ren ⇛-var   = ⇛-var
⇛-ren ⇛-U     = ⇛-U
⇛-ren ⇛-Nat   = ⇛-Nat
⇛-ren ⇛-zeroN = ⇛-zeroN
⇛-ren {ξ = ξ} (⇛-Pi p q)  = ⇛-Pi  (⇛-ren {ξ = ξ} p) (⇛-ren {ξ = ξ ↑ᴿ tm} q)
⇛-ren {ξ = ξ} (⇛-lam p q) = ⇛-lam (⇛-ren {ξ = ξ} p) (⇛-ren {ξ = ξ ↑ᴿ tm} q)
⇛-ren {ξ = ξ} (⇛-app p q) = ⇛-app (⇛-ren {ξ = ξ} p) (⇛-ren {ξ = ξ} q)
⇛-ren {ξ = ξ} (⇛-sucN p)  = ⇛-sucN (⇛-ren {ξ = ξ} p)
⇛-ren {ξ = ξ} (⇛-natrec p q r s) =
  ⇛-natrec (⇛-ren {ξ = ξ ↑ᴿ tm} p) (⇛-ren {ξ = ξ} q)
           (⇛-ren {ξ = (ξ ↑ᴿ tm) ↑ᴿ tm} r) (⇛-ren {ξ = ξ} s)
-- definitional: (b′ [ a′ ]₀) [ ξ ]ᴿ ≡ (b′ [ ξ ↑ᴿ tm ]ᴿ) [ a′ [ ξ ]ᴿ ]₀
⇛-ren {ξ = ξ} (⇛-beta {b = b} {b′ = b′} {a = a} {a′ = a′} {A = A} p q) =
  ⇛-beta {b = b [ ξ ↑ᴿ tm ]ᴿ} {b′ = b′ [ ξ ↑ᴿ tm ]ᴿ}
         {a = a [ ξ ]ᴿ} {a′ = a′ [ ξ ]ᴿ} {A = A [ ξ ]ᴿ}
         (⇛-ren {ξ = ξ ↑ᴿ tm} p) (⇛-ren {ξ = ξ} q)
⇛-ren {ξ = ξ} (⇛-ιzero {z′ = z′} {P = P} {sc = sc} p) =
  ⇛-ιzero {z′ = z′ [ ξ ]ᴿ} {P = P [ ξ ↑ᴿ tm ]ᴿ} {sc = sc [ (ξ ↑ᴿ tm) ↑ᴿ tm ]ᴿ}
          (⇛-ren {ξ = ξ} p)
-- definitional: the two-variable ι-suc law under a renaming
⇛-ren {ξ = ξ} (⇛-ιsuc {P = P} {P′ = P′} {z = z} {z′ = z′}
                      {sc = sc} {sc′ = sc′} {n = n} {n′ = n′} p q r s) =
  ⇛-ιsuc {P = P [ ξ ↑ᴿ tm ]ᴿ} {P′ = P′ [ ξ ↑ᴿ tm ]ᴿ}
         {z = z [ ξ ]ᴿ} {z′ = z′ [ ξ ]ᴿ}
         {sc = sc [ (ξ ↑ᴿ tm) ↑ᴿ tm ]ᴿ} {sc′ = sc′ [ (ξ ↑ᴿ tm) ↑ᴿ tm ]ᴿ}
         {n = n [ ξ ]ᴿ} {n′ = n′ [ ξ ]ᴿ}
         (⇛-ren {ξ = ξ ↑ᴿ tm} p) (⇛-ren {ξ = ξ} q)
         (⇛-ren {ξ = (ξ ↑ᴿ tm) ↑ᴿ tm} r) (⇛-ren {ξ = ξ} s)

-- ─── 3.  pointwise lifting of ⇛ to substitutions ────────────────────

-- A RECORD, not a Π-type: σ and σ′ occur in the field's type only
-- under `_[_]ˢ`, so as a bare function type they would never be
-- solvable by unification.  As record parameters they are.

record _⇛ˢ_ {S₁ S₂ : Scope} (σ σ′ : S₁ →ˢ S₂) : Set where
  constructor ⇛ˢ⟨_⟩
  field ⇛ˢ-at : ∀ (x : S₁ ∋ tm) → (x [ σ ]ˢ) ⇛ (x [ σ′ ]ˢ)
open _⇛ˢ_

-- definitional: at `zero` both sides are `var zero` (def-↑ˢ-zero); at
-- `suc x` the goal is `x [ σ ⨟ ⟨ wkᴿ tm ⟩ ]ˢ ⇛ …` (def-↑ˢ-suc), which
-- is what ⇛-ren at wkᴿ delivers after compositionalityˢᴿ.  No lemma.
⇛ˢ-↑ : ∀ {S₁ S₂} {σ σ′ : S₁ →ˢ S₂} → σ ⇛ˢ σ′ → (σ ↑ˢ tm) ⇛ˢ (σ′ ↑ˢ tm)
⇛ˢ-↑ p = ⇛ˢ⟨ (λ where
  zero    → ⇛-var
  (suc x) → ⇛-ren {ξ = wkᴿ tm} (⇛ˢ-at p x)) ⟩

-- definitional: def-∙ˢ-zero and def-∙ˢ-suc
⇛ˢ-∙ : ∀ {S₁ S₂} {t t′ : S₂ ⊢ tm} {σ σ′ : S₁ →ˢ S₂} →
  t ⇛ t′ → σ ⇛ˢ σ′ → (t ∙ˢ σ) ⇛ˢ (t′ ∙ˢ σ′)
⇛ˢ-∙ p q = ⇛ˢ⟨ (λ where
  zero    → p
  (suc x) → ⇛ˢ-at q x) ⟩

-- definitional: coincidence-var then right-idᴿ turn `x [ idˢ ]ˢ` into `var x`
⇛ˢ-id : ∀ {S} → idˢ {S} ⇛ˢ idˢ
⇛ˢ-id = ⇛ˢ⟨ (λ x → ⇛-var) ⟩

-- ─── 4.  the substitution lemma for ⇛ ───────────────────────────────

⇛-sub : ∀ {S₁ S₂} {t t′ : S₁ ⊢ tm} {σ σ′ : S₁ →ˢ S₂} →
  t ⇛ t′ → σ ⇛ˢ σ′ → (t [ σ ]ˢ) ⇛ (t′ [ σ′ ]ˢ)
⇛-sub (⇛-var {x = x}) pσ = ⇛ˢ-at pσ x
⇛-sub ⇛-U     pσ = ⇛-U
⇛-sub ⇛-Nat   pσ = ⇛-Nat
⇛-sub ⇛-zeroN pσ = ⇛-zeroN
⇛-sub {σ = σ} {σ′ = σ′} (⇛-Pi p q) pσ =
  ⇛-Pi (⇛-sub {σ = σ} {σ′ = σ′} p pσ)
       (⇛-sub {σ = σ ↑ˢ tm} {σ′ = σ′ ↑ˢ tm} q (⇛ˢ-↑ pσ))
⇛-sub {σ = σ} {σ′ = σ′} (⇛-lam p q) pσ =
  ⇛-lam (⇛-sub {σ = σ} {σ′ = σ′} p pσ)
        (⇛-sub {σ = σ ↑ˢ tm} {σ′ = σ′ ↑ˢ tm} q (⇛ˢ-↑ pσ))
⇛-sub {σ = σ} {σ′ = σ′} (⇛-app p q) pσ =
  ⇛-app (⇛-sub {σ = σ} {σ′ = σ′} p pσ) (⇛-sub {σ = σ} {σ′ = σ′} q pσ)
⇛-sub {σ = σ} {σ′ = σ′} (⇛-sucN p) pσ = ⇛-sucN (⇛-sub {σ = σ} {σ′ = σ′} p pσ)
⇛-sub {σ = σ} {σ′ = σ′} (⇛-natrec p q r s) pσ =
  ⇛-natrec (⇛-sub {σ = σ ↑ˢ tm} {σ′ = σ′ ↑ˢ tm} p (⇛ˢ-↑ pσ))
           (⇛-sub {σ = σ} {σ′ = σ′} q pσ)
           (⇛-sub {σ = (σ ↑ˢ tm) ↑ˢ tm} {σ′ = (σ′ ↑ˢ tm) ↑ˢ tm} r (⇛ˢ-↑ (⇛ˢ-↑ pσ)))
           (⇛-sub {σ = σ} {σ′ = σ′} s pσ)
-- definitional: (b′ [ a′ ]₀) [ σ′ ]ˢ ≡ (b′ [ σ′ ↑ˢ tm ]ˢ) [ a′ [ σ′ ]ˢ ]₀
⇛-sub {σ = σ} {σ′ = σ′} (⇛-beta {b = b} {b′ = b′} {a = a} {a′ = a′} {A = A} p q) pσ =
  ⇛-beta {b = b [ σ ↑ˢ tm ]ˢ} {b′ = b′ [ σ′ ↑ˢ tm ]ˢ}
         {a = a [ σ ]ˢ} {a′ = a′ [ σ′ ]ˢ} {A = A [ σ ]ˢ}
         (⇛-sub {σ = σ ↑ˢ tm} {σ′ = σ′ ↑ˢ tm} p (⇛ˢ-↑ pσ))
         (⇛-sub {σ = σ} {σ′ = σ′} q pσ)
⇛-sub {σ = σ} {σ′ = σ′} (⇛-ιzero {z′ = z′} {P = P} {sc = sc} p) pσ =
  ⇛-ιzero {z′ = z′ [ σ′ ]ˢ} {P = P [ σ ↑ˢ tm ]ˢ} {sc = sc [ (σ ↑ˢ tm) ↑ˢ tm ]ˢ}
          (⇛-sub {σ = σ} {σ′ = σ′} p pσ)
-- definitional: the TWO-VARIABLE ι-suc law commuting with σ.  The RHS
-- of ⇛-ιsuc is a substitution by a two-element cons; pushing σ′ through
-- it is `dist` twice followed by `comp-idₗ`, and pulling the double
-- lift out of sc′ is `lift-cons` twice.  Both sides land on the same
-- normal form, so the constructor alone closes the case.
⇛-sub {σ = σ} {σ′ = σ′} (⇛-ιsuc {P = P} {P′ = P′} {z = z} {z′ = z′}
                                {sc = sc} {sc′ = sc′} {n = n} {n′ = n′} p q r s) pσ =
  ⇛-ιsuc {P = P [ σ ↑ˢ tm ]ˢ} {P′ = P′ [ σ′ ↑ˢ tm ]ˢ}
         {z = z [ σ ]ˢ} {z′ = z′ [ σ′ ]ˢ}
         {sc = sc [ (σ ↑ˢ tm) ↑ˢ tm ]ˢ} {sc′ = sc′ [ (σ′ ↑ˢ tm) ↑ˢ tm ]ˢ}
         {n = n [ σ ]ˢ} {n′ = n′ [ σ′ ]ˢ}
         (⇛-sub {σ = σ ↑ˢ tm} {σ′ = σ′ ↑ˢ tm} p (⇛ˢ-↑ pσ))
         (⇛-sub {σ = σ} {σ′ = σ′} q pσ)
         (⇛-sub {σ = (σ ↑ˢ tm) ↑ˢ tm} {σ′ = (σ′ ↑ˢ tm) ↑ˢ tm} r (⇛ˢ-↑ (⇛ˢ-↑ pσ)))
         (⇛-sub {σ = σ} {σ′ = σ′} s pσ)

-- ─── 5.  the complete development ───────────────────────────────────
-- Structural recursion on the term, contracting every redex present.

_* : S ⊢ tm → S ⊢ tm
(var x) *                = var x
U *                      = U
Nat *                    = Nat
zeroN *                  = zeroN
(sucN t) *               = sucN (t *)
(Pi A B) *               = Pi (A *) (B *)
(lam A b) *              = lam (A *) (b *)
(app (lam A b) a) *      = (b *) [ (a *) ]₀
(app f a) *              = app (f *) (a *)
(natrec P z sc zeroN) *  = z *
(natrec P z sc (sucN n)) * =
  (sc *) [ natrec (P *) (z *) (sc *) (n *) ∙ˢ ((n *) ∙ˢ idˢ) ]ˢ
(natrec P z sc n) *      = natrec (P *) (z *) (sc *) (n *)

-- ─── 6.  the triangle:  t ⇛ u  implies  u ⇛ t*  ─────────────────────
-- The head of an application (resp. the argument of a natrec) has to be
-- split so that _*_ computes; every branch but the redex one is uniform.

⇛-△ : ∀ {S} {t u : S ⊢ tm} → t ⇛ u → u ⇛ (t *)
⇛-△ ⇛-var   = ⇛-var
⇛-△ ⇛-U     = ⇛-U
⇛-△ ⇛-Nat   = ⇛-Nat
⇛-△ ⇛-zeroN = ⇛-zeroN
⇛-△ (⇛-Pi p q)   = ⇛-Pi (⇛-△ p) (⇛-△ q)
⇛-△ (⇛-lam p q)  = ⇛-lam (⇛-△ p) (⇛-△ q)
⇛-△ (⇛-sucN p)   = ⇛-sucN (⇛-△ p)
⇛-△ (⇛-app {f = var _}      p q) = ⇛-app (⇛-△ p) (⇛-△ q)
⇛-△ (⇛-app {f = U}          p q) = ⇛-app (⇛-△ p) (⇛-△ q)
⇛-△ (⇛-app {f = Nat}        p q) = ⇛-app (⇛-△ p) (⇛-△ q)
⇛-△ (⇛-app {f = zeroN}      p q) = ⇛-app (⇛-△ p) (⇛-△ q)
⇛-△ (⇛-app {f = sucN _}     p q) = ⇛-app (⇛-△ p) (⇛-△ q)
⇛-△ (⇛-app {f = Pi _ _}     p q) = ⇛-app (⇛-△ p) (⇛-△ q)
⇛-△ (⇛-app {f = app _ _}    p q) = ⇛-app (⇛-△ p) (⇛-△ q)
⇛-△ (⇛-app {f = natrec _ _ _ _} p q) = ⇛-app (⇛-△ p) (⇛-△ q)
⇛-△ (⇛-app {f = lam _ _} (⇛-lam _ p) q) = ⇛-beta (⇛-△ p) (⇛-△ q)
⇛-△ (⇛-natrec {n = var _}    p q r s) = ⇛-natrec (⇛-△ p) (⇛-△ q) (⇛-△ r) (⇛-△ s)
⇛-△ (⇛-natrec {n = U}        p q r s) = ⇛-natrec (⇛-△ p) (⇛-△ q) (⇛-△ r) (⇛-△ s)
⇛-△ (⇛-natrec {n = Nat}      p q r s) = ⇛-natrec (⇛-△ p) (⇛-△ q) (⇛-△ r) (⇛-△ s)
⇛-△ (⇛-natrec {n = Pi _ _}   p q r s) = ⇛-natrec (⇛-△ p) (⇛-△ q) (⇛-△ r) (⇛-△ s)
⇛-△ (⇛-natrec {n = lam _ _}  p q r s) = ⇛-natrec (⇛-△ p) (⇛-△ q) (⇛-△ r) (⇛-△ s)
⇛-△ (⇛-natrec {n = app _ _}  p q r s) = ⇛-natrec (⇛-△ p) (⇛-△ q) (⇛-△ r) (⇛-△ s)
⇛-△ (⇛-natrec {n = natrec _ _ _ _} p q r s) =
  ⇛-natrec (⇛-△ p) (⇛-△ q) (⇛-△ r) (⇛-△ s)
⇛-△ (⇛-natrec {n = zeroN}    p q r ⇛-zeroN)     = ⇛-ιzero (⇛-△ q)
⇛-△ (⇛-natrec {n = sucN _}   p q r (⇛-sucN s))  = ⇛-ιsuc (⇛-△ p) (⇛-△ q) (⇛-△ r) (⇛-△ s)
-- the two redex constructors: here the substitution lemma does the work
⇛-△ (⇛-beta {b′ = b′} {a′ = a′} p q) =
  ⇛-sub {σ = a′ ∙ˢ idˢ} p′ (⇛ˢ-∙ q′ ⇛ˢ-id)
  where p′ = ⇛-△ p
        q′ = ⇛-△ q
⇛-△ (⇛-ιzero p) = ⇛-△ p
⇛-△ (⇛-ιsuc {P′ = P′} {z′ = z′} {sc′ = sc′} {n′ = n′} p q r s) =
  ⇛-sub {σ = natrec P′ z′ sc′ n′ ∙ˢ (n′ ∙ˢ idˢ)}
        (⇛-△ r)
        (⇛ˢ-∙ (⇛-natrec (⇛-△ p) (⇛-△ q) (⇛-△ r) (⇛-△ s))
              (⇛ˢ-∙ (⇛-△ s) ⇛ˢ-id))

-- ─── 7.  diamond, and confluence of ⇛* ──────────────────────────────

⇛-diamond : ∀ {S} {t u v : S ⊢ tm} → t ⇛ u → t ⇛ v → ∃[ w ] ((u ⇛ w) × (v ⇛ w))
⇛-diamond {t = t} p q = t * , ⇛-△ p , ⇛-△ q

data _⇛*_ : S ⊢ tm → S ⊢ tm → Set where
  ⇛*-refl : ∀ {S} {t : S ⊢ tm} → t ⇛* t
  ⇛*-step : ∀ {S} {t u v : S ⊢ tm} → t ⇛ u → u ⇛* v → t ⇛* v

⇛*-strip : ∀ {S} {t u v : S ⊢ tm} → t ⇛ u → t ⇛* v → ∃[ w ] ((u ⇛* w) × (v ⇛ w))
⇛*-strip {u = u} p ⇛*-refl = u , ⇛*-refl , p
⇛*-strip p (⇛*-step q qs) with ⇛-diamond p q
... | w , pw , qw with ⇛*-strip qw qs
... | w′ , pw′ , qw′ = w′ , ⇛*-step pw pw′ , qw′

⇛*-confluent : ∀ {S} {t u v : S ⊢ tm} →
  t ⇛* u → t ⇛* v → ∃[ w ] ((u ⇛* w) × (v ⇛* w))
⇛*-confluent ⇛*-refl q = _ , q , ⇛*-refl
⇛*-confluent (⇛*-step p ps) q with ⇛*-strip p q
... | w , qw , pw with ⇛*-confluent ps qw
... | w′ , pw′ , qw′ = w′ , pw′ , ⇛*-step pw qw′

-- ─── 8.  ↪ ⊆ ⇛ ⊆ ↠, hence ⇛* and ↠ coincide ────────────────────────

↠-trans : ∀ {S} {A B C : S ⊢ tm} → A ↠ B → B ↠ C → A ↠ C
↠-trans ↠-refl        q = q
↠-trans (↠-step r rs) q = ↠-step r (↠-trans rs q)

↠-map : ∀ {S₁ S₂} (g : S₁ ⊢ tm → S₂ ⊢ tm) →
  (∀ {u v} → u ↪ v → g u ↪ g v) → ∀ {u v} → u ↠ v → g u ↠ g v
↠-map g c ↠-refl        = ↠-refl
↠-map g c (↠-step r rs) = ↠-step (c r) (↠-map g c rs)

↪→⇛ : ∀ {S} {A B : S ⊢ tm} → A ↪ B → A ⇛ B
↪→⇛ (β-app {A = A} {b = b} {a = a}) = ⇛-beta (⇛-refl b) (⇛-refl a)
↪→⇛ (ι-zero {z = z}) = ⇛-ιzero (⇛-refl z)
↪→⇛ (ι-suc {P = P} {z = z} {sc = sc} {n = n}) =
  ⇛-ιsuc (⇛-refl P) (⇛-refl z) (⇛-refl sc) (⇛-refl n)
↪→⇛ (ξ-Pi₁ {B = B} r)  = ⇛-Pi (↪→⇛ r) (⇛-refl B)
↪→⇛ (ξ-Pi₂ {A = A} r)  = ⇛-Pi (⇛-refl A) (↪→⇛ r)
↪→⇛ (ξ-lam₁ {b = b} r) = ⇛-lam (↪→⇛ r) (⇛-refl b)
↪→⇛ (ξ-lam₂ {A = A} r) = ⇛-lam (⇛-refl A) (↪→⇛ r)
↪→⇛ (ξ-app₁ {a = a} r) = ⇛-app (↪→⇛ r) (⇛-refl a)
↪→⇛ (ξ-app₂ {f = f} r) = ⇛-app (⇛-refl f) (↪→⇛ r)
↪→⇛ (ξ-sucN r)         = ⇛-sucN (↪→⇛ r)
↪→⇛ (ξ-natrec₁ {z = z} {sc = sc} {n = n} r) =
  ⇛-natrec (↪→⇛ r) (⇛-refl z) (⇛-refl sc) (⇛-refl n)
↪→⇛ (ξ-natrec₂ {P = P} {sc = sc} {n = n} r) =
  ⇛-natrec (⇛-refl P) (↪→⇛ r) (⇛-refl sc) (⇛-refl n)
↪→⇛ (ξ-natrec₃ {P = P} {z = z} {n = n} r) =
  ⇛-natrec (⇛-refl P) (⇛-refl z) (↪→⇛ r) (⇛-refl n)
↪→⇛ (ξ-natrec₄ {P = P} {z = z} {sc = sc} r) =
  ⇛-natrec (⇛-refl P) (⇛-refl z) (⇛-refl sc) (↪→⇛ r)

⇛→↠ : ∀ {S} {A B : S ⊢ tm} → A ⇛ B → A ↠ B
⇛→↠ ⇛-var   = ↠-refl
⇛→↠ ⇛-U     = ↠-refl
⇛→↠ ⇛-Nat   = ↠-refl
⇛→↠ ⇛-zeroN = ↠-refl
⇛→↠ (⇛-Pi {A = A} {A′ = A′} {B = B} {B′ = B′} p q) =
  ↠-trans (↠-map (λ x → Pi x B)  ξ-Pi₁ (⇛→↠ p))
          (↠-map (λ x → Pi A′ x) ξ-Pi₂ (⇛→↠ q))
⇛→↠ (⇛-lam {A = A} {A′ = A′} {b = b} {b′ = b′} p q) =
  ↠-trans (↠-map (λ x → lam x b)  ξ-lam₁ (⇛→↠ p))
          (↠-map (λ x → lam A′ x) ξ-lam₂ (⇛→↠ q))
⇛→↠ (⇛-app {f = f} {f′ = f′} {a = a} {a′ = a′} p q) =
  ↠-trans (↠-map (λ x → app x a)  ξ-app₁ (⇛→↠ p))
          (↠-map (λ x → app f′ x) ξ-app₂ (⇛→↠ q))
⇛→↠ (⇛-sucN p) = ↠-map sucN ξ-sucN (⇛→↠ p)
⇛→↠ (⇛-natrec {P = P} {P′ = P′} {z = z} {z′ = z′}
              {sc = sc} {sc′ = sc′} {n = n} {n′ = n′} p q r s) =
  ↠-trans (↠-map (λ x → natrec x z sc n)     ξ-natrec₁ (⇛→↠ p))
  (↠-trans (↠-map (λ x → natrec P′ x sc n)   ξ-natrec₂ (⇛→↠ q))
  (↠-trans (↠-map (λ x → natrec P′ z′ x n)   ξ-natrec₃ (⇛→↠ r))
           (↠-map (λ x → natrec P′ z′ sc′ x) ξ-natrec₄ (⇛→↠ s))))
⇛→↠ (⇛-beta {b = b} {b′ = b′} {a = a} {a′ = a′} {A = A} p q) =
  ↠-trans (↠-map (λ x → app (lam A x) a) (λ e → ξ-app₁ (ξ-lam₂ e)) (⇛→↠ p))
  (↠-trans (↠-map (λ x → app (lam A b′) x) ξ-app₂ (⇛→↠ q))
           (↠-step (β-app {A = A} {b = b′} {a = a′}) ↠-refl))
⇛→↠ (⇛-ιzero {z = z} {z′ = z′} {P = P} {sc = sc} p) =
  ↠-step (ι-zero {P = P} {z = z} {sc = sc}) (⇛→↠ p)
⇛→↠ (⇛-ιsuc {P = P} {P′ = P′} {z = z} {z′ = z′}
            {sc = sc} {sc′ = sc′} {n = n} {n′ = n′} p q r s) =
  ↠-trans (↠-map (λ x → natrec x z sc (sucN n))      ξ-natrec₁ (⇛→↠ p))
  (↠-trans (↠-map (λ x → natrec P′ x sc (sucN n))    ξ-natrec₂ (⇛→↠ q))
  (↠-trans (↠-map (λ x → natrec P′ z′ x (sucN n))    ξ-natrec₃ (⇛→↠ r))
  (↠-trans (↠-map (λ x → natrec P′ z′ sc′ (sucN x))
                  (λ e → ξ-natrec₄ (ξ-sucN e)) (⇛→↠ s))
           (↠-step (ι-suc {P = P′} {z = z′} {sc = sc′} {n = n′}) ↠-refl))))

↠→⇛* : ∀ {S} {A B : S ⊢ tm} → A ↠ B → A ⇛* B
↠→⇛* ↠-refl        = ⇛*-refl
↠→⇛* (↠-step r rs) = ⇛*-step (↪→⇛ r) (↠→⇛* rs)

⇛*→↠ : ∀ {S} {A B : S ⊢ tm} → A ⇛* B → A ↠ B
⇛*→↠ ⇛*-refl        = ↠-refl
⇛*→↠ (⇛*-step p ps) = ↠-trans (⇛→↠ p) (⇛*→↠ ps)

-- ─── 9.  confluence of ↠, and Church-Rosser ─────────────────────────

↠-confluent : ∀ {S} {A B C : S ⊢ tm} → A ↠ B → A ↠ C →
  ∃[ D ] ((B ↠ D) × (C ↠ D))
↠-confluent p q with ⇛*-confluent (↠→⇛* p) (↠→⇛* q)
... | D , r , s = D , ⇛*→↠ r , ⇛*→↠ s

CR : ∀ {S} {A B : S ⊢ tm} → A ≡β B → ∃[ C ] ((A ↠ C) × (B ↠ C))
CR {A = A} β-refl   = A , ↠-refl , ↠-refl
CR {B = B} (β-step r) = B , ↠-step r ↠-refl , ↠-refl
CR (β-sym e) with CR e
... | C , p , q = C , q , p
CR (β-trans e f) with CR e | CR f
... | C₁ , p₁ , q₁ | C₂ , p₂ , q₂ with ↠-confluent q₁ p₂
... | D , r , s = D , ↠-trans p₁ r , ↠-trans q₂ s

-- ─── 10.  positive controls for the Church-Rosser proof ─────────────
-- Without these, `_*`, `⇛-△` and `CR` could all be vacuously fine.

-- The complete development really contracts the β-redex, and the
-- REWRITE system computes the resulting substitution:
dev-β : (app (lam U (sucN (var zero))) Nat) * ≡ sucN {S = []} Nat
dev-β = refl

-- …and the ι-suc redex, whose contractum is the TWO-VARIABLE
-- substitution.  Here the successor branch is `var (suc zero)`, the
-- predecessor slot, so the development must return `n *`:
dev-ι : (natrec U Nat (var (suc zero)) (sucN zeroN)) * ≡ zeroN {S = []}
dev-ι = refl

-- …and `var zero`, the induction-hypothesis slot, must return the
-- recursive call:
dev-ι-IH : (natrec U Nat (var zero) (sucN zeroN)) *
         ≡ natrec {S = []} U Nat (var zero) zeroN
dev-ι-IH = refl

-- A genuine critical pair: one term, two different one-step reducts,
-- joined by the confluence theorem.
cp-src : [] ⊢ tm
cp-src = app (lam U (sucN (var zero))) (natrec Nat zeroN (var zero) zeroN)

cp-β : cp-src ↪ sucN (natrec Nat zeroN (var zero) zeroN)
cp-β = β-app

cp-ι : cp-src ↪ app (lam U (sucN (var zero))) zeroN
cp-ι = ξ-app₂ ι-zero

cp-join : ∃[ D ] ((sucN (natrec Nat zeroN (var zero) zeroN) ↠ D)
                × (app (lam U (sucN (var zero))) zeroN ↠ D))
cp-join = ↠-confluent (↠-step cp-β ↠-refl) (↠-step cp-ι ↠-refl)

-- and the join really is the normal form `sucN zeroN`
cp-join-is : proj₁ cp-join ≡ sucN {S = []} zeroN
cp-join-is = refl

-- CR itself, on a conversion built from both redexes
cr-probe : ∃[ C ] ((sucN (natrec Nat zeroN (var zero) zeroN) ↠ C)
                 × (app (lam U (sucN (var zero))) zeroN ↠ C))
cr-probe = CR (β-trans (β-sym (β-step cp-β)) (β-step cp-ι))

-- ════════════════════════════════════════════════════════════════════
-- Head analysis of ↠ for the three type formers.  All PROVED.
-- ════════════════════════════════════════════════════════════════════

↠-Pi-inv : ∀ {S} {A C : S ⊢ tm} {B : (tm ∷ S) ⊢ tm} → Pi A B ↠ C →
  ∃[ A′ ] ∃[ B′ ] ((C ≡ Pi A′ B′) × (A ↠ A′) × (B ↠ B′))
↠-Pi-inv ↠-refl = _ , _ , refl , ↠-refl , ↠-refl
↠-Pi-inv (↠-step (ξ-Pi₁ r) rs) with ↠-Pi-inv rs
... | A′ , B′ , refl , rA , rB = A′ , B′ , refl , ↠-step r rA , rB
↠-Pi-inv (↠-step (ξ-Pi₂ r) rs) with ↠-Pi-inv rs
... | A′ , B′ , refl , rA , rB = A′ , B′ , refl , rA , ↠-step r rB

↠-U-inv : ∀ {S} {C : S ⊢ tm} → U ↠ C → C ≡ U
↠-U-inv ↠-refl = refl

↠-Nat-inv : ∀ {S} {C : S ⊢ tm} → Nat ↠ C → C ≡ Nat
↠-Nat-inv ↠-refl = refl

-- ════════════════════════════════════════════════════════════════════
-- Pi-injectivity and no-confusion.  All PROVED from CR.
-- ════════════════════════════════════════════════════════════════════

Pi-inj : ∀ {S} {A A′ : S ⊢ tm} {B B′ : (tm ∷ S) ⊢ tm} →
  Pi A B ≡β Pi A′ B′ → (A ≡β A′) × (B ≡β B′)
Pi-inj e with CR e
... | C , r₁ , r₂ with ↠-Pi-inv r₁ | ↠-Pi-inv r₂
... | A₁ , B₁ , refl , rA₁ , rB₁ | A₂ , B₂ , eq , rA₂ , rB₂ with eq
... | refl = β-trans (↠→≡β rA₁) (β-sym (↠→≡β rA₂))
           , β-trans (↠→≡β rB₁) (β-sym (↠→≡β rB₂))

U≁Pi : ∀ {S} {A : S ⊢ tm} {B : (tm ∷ S) ⊢ tm} → U ≡β Pi A B → ⊥
U≁Pi e with CR e
... | C , r₁ , r₂ with ↠-U-inv r₁
... | refl with ↠-Pi-inv r₂
... | _ , _ , () , _ , _

Nat≁Pi : ∀ {S} {A : S ⊢ tm} {B : (tm ∷ S) ⊢ tm} → Nat ≡β Pi A B → ⊥
Nat≁Pi e with CR e
... | C , r₁ , r₂ with ↠-Nat-inv r₁
... | refl with ↠-Pi-inv r₂
... | _ , _ , () , _ , _

U≁Nat : ∀ {S} → U {S = S} ≡β Nat → ⊥
U≁Nat e with CR e
... | C , r₁ , r₂ with ↠-U-inv r₁
... | refl with ↠-Nat-inv r₂
... | ()

-- ═══ RENAMING AND SUBSTITUTION PRESERVE TYPING ═══════════════════════════════════════════

-- Preservation (subject reduction) for β and ι.
--
-- Bookkeeping for the experiment.  Every place where a substitution
-- equation had to be stated and applied BY HAND is marked
--    -- HAND-LEMMA n: <name>
-- every place where the framework discharged one definitionally is
--    -- definitional: <name>



-- ════════════════════════════════════════════════════════════════════
-- 1.  Reduction and conversion are stable under substitution.
--
-- This obligation does NOT exist in the System F development: there,
-- conversion does not occur in the typing rules, so `sub-pres` never has
-- to push a substitution through a reduction.  In MLTT the conversion
-- rule forces it.  It is new WORK, but it costs no new substitution
-- lemma: every equation it raises is already a rewrite.
-- ════════════════════════════════════════════════════════════════════

↪-sub : ∀ {S₁ S₂} {t t′ : S₁ ⊢ tm} {σ : S₁ →ˢ S₂} →
  t ↪ t′ → (t [ σ ]ˢ) ↪ (t′ [ σ ]ˢ)
-- The three redex cases must PIN the constructor's implicits: with the
-- two-world rule set the goal's index has already been rewritten, so
-- Agda can no longer read the arguments back off it.  This is exactly
-- the note in systemf.agda's `sr`.  It is a UNIFICATION cost, not a
-- substitution lemma: once pinned, the equation closes by refl.
-- definitional: probe 1 (subst-commute)
↪-sub {σ = σ} (β-app {A = A} {b = b} {a = a}) =
  β-app {A = A [ σ ]ˢ} {b = b [ σ ↑ˢ tm ]ˢ} {a = a [ σ ]ˢ}
↪-sub {σ = σ} (ι-zero {P = P} {z = z} {sc = sc}) =
  ι-zero {P = P [ σ ↑ˢ tm ]ˢ} {z = z [ σ ]ˢ} {sc = sc [ (σ ↑ˢ tm) ↑ˢ tm ]ˢ}
-- definitional: probe 3 (the two-variable ι-suc law)
↪-sub {σ = σ} (ι-suc {P = P} {z = z} {sc = sc} {n = n}) =
  ι-suc {P = P [ σ ↑ˢ tm ]ˢ} {z = z [ σ ]ˢ}
        {sc = sc [ (σ ↑ˢ tm) ↑ˢ tm ]ˢ} {n = n [ σ ]ˢ}
↪-sub {σ = σ} (ξ-Pi₁ r)     = ξ-Pi₁     (↪-sub {σ = σ} r)
↪-sub {σ = σ} (ξ-Pi₂ r)     = ξ-Pi₂     (↪-sub {σ = σ ↑ˢ tm} r)
↪-sub {σ = σ} (ξ-lam₁ r)    = ξ-lam₁    (↪-sub {σ = σ} r)
↪-sub {σ = σ} (ξ-lam₂ r)    = ξ-lam₂    (↪-sub {σ = σ ↑ˢ tm} r)
↪-sub {σ = σ} (ξ-app₁ r)    = ξ-app₁    (↪-sub {σ = σ} r)
↪-sub {σ = σ} (ξ-app₂ r)    = ξ-app₂    (↪-sub {σ = σ} r)
↪-sub {σ = σ} (ξ-sucN r)    = ξ-sucN    (↪-sub {σ = σ} r)
↪-sub {σ = σ} (ξ-natrec₁ r) = ξ-natrec₁ (↪-sub {σ = σ ↑ˢ tm} r)
↪-sub {σ = σ} (ξ-natrec₂ r) = ξ-natrec₂ (↪-sub {σ = σ} r)
↪-sub {σ = σ} (ξ-natrec₃ r) = ξ-natrec₃ (↪-sub {σ = (σ ↑ˢ tm) ↑ˢ tm} r)
↪-sub {σ = σ} (ξ-natrec₄ r) = ξ-natrec₄ (↪-sub {σ = σ} r)

≡β-sub : ∀ {S₁ S₂} {A B : S₁ ⊢ tm} {σ : S₁ →ˢ S₂} →
  A ≡β B → (A [ σ ]ˢ) ≡β (B [ σ ]ˢ)
≡β-sub β-refl        = β-refl
≡β-sub {σ = σ} (β-step r)    = β-step (↪-sub {σ = σ} r)
≡β-sub {σ = σ} (β-sym e)     = β-sym (≡β-sub {σ = σ} e)
≡β-sub {σ = σ} (β-trans e f) = β-trans (≡β-sub {σ = σ} e) (≡β-sub {σ = σ} f)

-- definitional: probe 6 (coincidence).  The renaming versions are the
-- σ-versions at σ := ⟨ ξ ⟩.  No separate induction, no transport.
↪-ren : ∀ {S₁ S₂} {t t′ : S₁ ⊢ tm} {ξ : S₁ →ᴿ S₂} →
  t ↪ t′ → (t [ ξ ]ᴿ) ↪ (t′ [ ξ ]ᴿ)
↪-ren {ξ = ξ} r = ↪-sub {σ = ⟨ ξ ⟩} r

≡β-ren : ∀ {S₁ S₂} {A B : S₁ ⊢ tm} {ξ : S₁ →ᴿ S₂} →
  A ≡β B → (A [ ξ ]ᴿ) ≡β (B [ ξ ]ᴿ)
≡β-ren {ξ = ξ} e = ≡β-sub {σ = ⟨ ξ ⟩} e

-- ════════════════════════════════════════════════════════════════════
-- 2.  Typed maps: phase 1 renamings, phase 2 substitutions.
-- ════════════════════════════════════════════════════════════════════

_∶_→ᴿ_ : S₁ →ᴿ S₂ → Ctx S₁ → Ctx S₂ → Set
_∶_→ᴿ_ {S₁} ξ Γ₁ Γ₂ = ∀ (x : S₁ ∋ tm) (t : S₁ ∶⊢ tm) →
  Γ₁ ∋ x ∶ t → Γ₂ ∋ (x [ ξ ]ᴿ) ∶ (t [ ξ ]ᴿ)

_∶_→ˢ_ : S₁ →ˢ S₂ → Ctx S₁ → Ctx S₂ → Set
_∶_→ˢ_ {S₁} σ Γ₁ Γ₂ = ∀ (x : S₁ ∋ tm) (t : S₁ ∶⊢ tm) →
  Γ₁ ∋ x ∶ t → Γ₂ ⊢ (x [ σ ]ˢ) ∶ (t [ σ ]ˢ)

⊢wkᴿ : ∀ {S} {Γ : Ctx S} (t′ : S ∶⊢ tm) → wkᴿ tm ∶ Γ →ᴿ (t′ ∷ₜ Γ)
⊢wkᴿ t′ x _ refl = refl

⊢↑ᴿ : ∀ {S₁ S₂} {ξ : S₁ →ᴿ S₂} {Γ₁ : Ctx S₁} {Γ₂ : Ctx S₂} → ξ ∶ Γ₁ →ᴿ Γ₂ →
  (t : S₁ ∶⊢ tm) → (ξ ↑ᴿ tm) ∶ (t ∷ₜ Γ₁) →ᴿ ((t [ ξ ]ᴿ) ∷ₜ Γ₂)
⊢↑ᴿ ⊢ξ t zero    _ refl = refl
⊢↑ᴿ ⊢ξ t (suc x) _ refl = cong weaken (⊢ξ x _ refl)

ren-pres : ∀ {S₁ S₂} {ξ : S₁ →ᴿ S₂} {Γ₁ : Ctx S₁} {Γ₂ : Ctx S₂}
  {e : S₁ ⊢ tm} {t : S₁ ⊢ tm} →
  Γ₁ ⊢ e ∶ t → ξ ∶ Γ₁ →ᴿ Γ₂ → Γ₂ ⊢ (e [ ξ ]ᴿ) ∶ (t [ ξ ]ᴿ)
ren-pres (⊢var ⊢x)     ⊢ξ = ⊢var (⊢ξ _ _ ⊢x)
ren-pres ⊢U            ⊢ξ = ⊢U
ren-pres (⊢Pi ⊢A ⊢B)   ⊢ξ = ⊢Pi (ren-pres ⊢A ⊢ξ) (ren-pres ⊢B (⊢↑ᴿ ⊢ξ _))
ren-pres (⊢lam ⊢A ⊢b)  ⊢ξ = ⊢lam (ren-pres ⊢A ⊢ξ) (ren-pres ⊢b (⊢↑ᴿ ⊢ξ _))
-- definitional: probe 1 at σ := ⟨ ξ ⟩
ren-pres (⊢app ⊢f ⊢a)  ⊢ξ = ⊢app (ren-pres ⊢f ⊢ξ) (ren-pres ⊢a ⊢ξ)
ren-pres ⊢Nat          ⊢ξ = ⊢Nat
ren-pres ⊢zeroN        ⊢ξ = ⊢zeroN
ren-pres (⊢sucN ⊢n)    ⊢ξ = ⊢sucN (ren-pres ⊢n ⊢ξ)
-- definitional: probes 4 and 5 at σ := ⟨ ξ ⟩
ren-pres (⊢natrec ⊢P ⊢z ⊢sc ⊢n) ⊢ξ =
  ⊢natrec (ren-pres ⊢P (⊢↑ᴿ ⊢ξ _)) (ren-pres ⊢z ⊢ξ)
          (ren-pres ⊢sc (⊢↑ᴿ (⊢↑ᴿ ⊢ξ _) _)) (ren-pres ⊢n ⊢ξ)
ren-pres (⊢conv ⊢a e) ⊢ξ = ⊢conv (ren-pres ⊢a ⊢ξ) (≡β-ren e)

⊢↑ˢ : ∀ {S₁ S₂} {σ : S₁ →ˢ S₂} {Γ₁ : Ctx S₁} {Γ₂ : Ctx S₂} →
  σ ∶ Γ₁ →ˢ Γ₂ → (t : S₁ ∶⊢ tm) →
  (σ ↑ˢ tm) ∶ (t ∷ₜ Γ₁) →ˢ ((t [ σ ]ˢ) ∷ₜ Γ₂)
⊢↑ˢ ⊢σ t zero    _ refl = ⊢var refl
⊢↑ˢ {σ = σ} {Γ₂ = Γ₂} ⊢σ t (suc x) _ refl =
  ren-pres (⊢σ x _ refl) (⊢wkᴿ {Γ = Γ₂} (t [ σ ]ˢ))

sub-pres : ∀ {S₁ S₂} {σ : S₁ →ˢ S₂} {Γ₁ : Ctx S₁} {Γ₂ : Ctx S₂}
  {e : S₁ ⊢ tm} {t : S₁ ⊢ tm} →
  Γ₁ ⊢ e ∶ t → σ ∶ Γ₁ →ˢ Γ₂ → Γ₂ ⊢ (e [ σ ]ˢ) ∶ (t [ σ ]ˢ)
sub-pres (⊢var ⊢x) ⊢σ = ⊢σ _ _ ⊢x
sub-pres ⊢U        ⊢σ = ⊢U
sub-pres {σ = σ} (⊢Pi ⊢A ⊢B)  ⊢σ =
  ⊢Pi (sub-pres {σ = σ} ⊢A ⊢σ) (sub-pres {σ = σ ↑ˢ tm} ⊢B (⊢↑ˢ {σ = σ} ⊢σ _))
sub-pres {σ = σ} (⊢lam ⊢A ⊢b) ⊢σ =
  ⊢lam (sub-pres {σ = σ} ⊢A ⊢σ) (sub-pres {σ = σ ↑ˢ tm} ⊢b (⊢↑ˢ {σ = σ} ⊢σ _))
-- definitional: probe 1.  ⊢app concludes at B [ a ]₀, so the two sides
-- are (B [ σ↑ ]) [ a[σ] ]₀ and (B [ a ]₀) [ σ ].
sub-pres {σ = σ} (⊢app ⊢f ⊢a) ⊢σ =
  ⊢app (sub-pres {σ = σ} ⊢f ⊢σ) (sub-pres {σ = σ} ⊢a ⊢σ)
sub-pres ⊢Nat   ⊢σ = ⊢Nat
sub-pres ⊢zeroN ⊢σ = ⊢zeroN
sub-pres {σ = σ} (⊢sucN ⊢n) ⊢σ = ⊢sucN (sub-pres {σ = σ} ⊢n ⊢σ)
-- definitional: probes 4 and 5.  The successor branch's type
-- `sucMotive P` must commute with the DOUBLE lift (σ↑)↑.
sub-pres {σ = σ} (⊢natrec ⊢P ⊢z ⊢sc ⊢n) ⊢σ =
  ⊢natrec (sub-pres {σ = σ ↑ˢ tm} ⊢P (⊢↑ˢ {σ = σ} ⊢σ _))
          (sub-pres {σ = σ} ⊢z ⊢σ)
          (sub-pres {σ = (σ ↑ˢ tm) ↑ˢ tm} ⊢sc (⊢↑ˢ {σ = σ ↑ˢ tm} (⊢↑ˢ {σ = σ} ⊢σ _) _))
          (sub-pres {σ = σ} ⊢n ⊢σ)
sub-pres {σ = σ} (⊢conv ⊢a e) ⊢σ =
  ⊢conv (sub-pres {σ = σ} ⊢a ⊢σ) (≡β-sub {σ = σ} e)

⊢[] : ∀ {S} {Γ : Ctx S} {e : S ⊢ tm} {t : S ⊢ tm} →
  Γ ⊢ e ∶ t → (e ∙ˢ idˢ) ∶ (t ∷ₜ Γ) →ˢ Γ
⊢[] ⊢e zero    _ refl = ⊢e
⊢[] ⊢e (suc x) _ refl = ⊢var refl

-- ═══ SUBJECT REDUCTION ═══════════════════════════════════════════

-- Subject reduction (preservation) for β and ι.
--
-- This file assumes NOTHING of its own.  It uses `Pi-inj`, which
-- this file PROVES from Church-Rosser for the
-- untyped calculus), a theorem orthogonal to the substitution machinery.



-- ════════════════════════════════════════════════════════════════════
-- 0.  Conversion in the substituted ARGUMENT.
--
-- Note the trick: no induction on the term is needed, because
-- conversion is symmetric and t [ a ]₀ is a β-reduct of app (lam U t) a.
-- ════════════════════════════════════════════════════════════════════

sub-arg-≡β : ∀ {S} (t : (tm ∷ S) ⊢ tm) {a a′ : S ⊢ tm} →
  a ↪ a′ → (t [ a ]₀) ≡β (t [ a′ ]₀)
sub-arg-≡β t {a} {a′} r =
  β-trans (β-sym (β-step (β-app {A = U} {b = t} {a = a})))
    (β-trans (β-step (ξ-app₂ {f = lam U t} r))
             (β-step (β-app {A = U} {b = t} {a = a′})))

-- ════════════════════════════════════════════════════════════════════
-- 1.  Context conversion.
-- ════════════════════════════════════════════════════════════════════

_≈_ : ∀ {S} → Ctx S → Ctx S → Set
_≈_ {S} Γ₁ Γ₂ = ∀ (x : S ∋ tm) → wk-telescope Γ₁ x ≡β wk-telescope Γ₂ x

-- both use only `≡β-ren`, itself an instance of `≡β-sub` (probe 6)
ext-≈ : ∀ {S} {Γ₁ Γ₂ : Ctx S} {A : S ⊢ tm} → Γ₁ ≈ Γ₂ → (A ∷ₜ Γ₁) ≈ (A ∷ₜ Γ₂)
ext-≈ c zero    = β-refl
ext-≈ c (suc x) = ≡β-ren (c x)

cons-≈ : ∀ {S} {Γ : Ctx S} {A A′ : S ⊢ tm} → A ≡β A′ → (A ∷ₜ Γ) ≈ (A′ ∷ₜ Γ)
cons-≈ e zero    = ≡β-ren e
cons-≈ e (suc x) = β-refl

ctx-conv : ∀ {S} {Γ₁ Γ₂ : Ctx S} {e A : S ⊢ tm} →
  Γ₁ ≈ Γ₂ → Γ₁ ⊢ e ∶ A → Γ₂ ⊢ e ∶ A
ctx-conv c (⊢var {x = x} refl)  = ⊢conv (⊢var refl) (β-sym (c x))
ctx-conv c ⊢U                   = ⊢U
ctx-conv c (⊢Pi ⊢A ⊢B)          = ⊢Pi (ctx-conv c ⊢A) (ctx-conv (ext-≈ c) ⊢B)
ctx-conv c (⊢lam ⊢A ⊢b)         = ⊢lam (ctx-conv c ⊢A) (ctx-conv (ext-≈ c) ⊢b)
ctx-conv c (⊢app ⊢f ⊢a)         = ⊢app (ctx-conv c ⊢f) (ctx-conv c ⊢a)
ctx-conv c ⊢Nat                 = ⊢Nat
ctx-conv c ⊢zeroN               = ⊢zeroN
ctx-conv c (⊢sucN ⊢n)           = ⊢sucN (ctx-conv c ⊢n)
ctx-conv c (⊢natrec ⊢P ⊢z ⊢sc ⊢n) =
  ⊢natrec (ctx-conv (ext-≈ c) ⊢P) (ctx-conv c ⊢z)
          (ctx-conv (ext-≈ (ext-≈ c)) ⊢sc) (ctx-conv c ⊢n)
ctx-conv c (⊢conv ⊢a e)         = ⊢conv (ctx-conv c ⊢a) e

-- ════════════════════════════════════════════════════════════════════
-- 2.  Inversion.  Both go through ⊢conv without needing injectivity.
-- ════════════════════════════════════════════════════════════════════

inv-sucN : ∀ {S} {Γ : Ctx S} {n A : S ⊢ tm} → Γ ⊢ (sucN n) ∶ A → Γ ⊢ n ∶ Nat
inv-sucN (⊢sucN ⊢n)  = ⊢n
inv-sucN (⊢conv ⊢t e) = inv-sucN ⊢t

inv-lam : ∀ {S} {Γ : Ctx S} {A₀ C : S ⊢ tm} {b : (tm ∷ S) ⊢ tm} →
  Γ ⊢ (lam A₀ b) ∶ C →
  ∃[ B ] ((C ≡β Pi A₀ B) × ((A₀ ∷ₜ Γ) ⊢ b ∶ B))
inv-lam (⊢lam ⊢A ⊢b)  = _ , β-refl , ⊢b
inv-lam (⊢conv ⊢t e) with inv-lam ⊢t
... | B , eq , ⊢b = B , β-trans (β-sym e) eq , ⊢b

-- ════════════════════════════════════════════════════════════════════
-- 3.  Pi-injectivity comes from mltt-cr, where it is PROVED from the
-- proved Church-Rosser theorem for the untyped calculus.
-- ════════════════════════════════════════════════════════════════════

-- ════════════════════════════════════════════════════════════════════
-- 4.  The typed map for the ι-suc redex.
-- ════════════════════════════════════════════════════════════════════

⊢ιmap : ∀ {S} {Γ : Ctx S} {P : (tm ∷ S) ⊢ tm} {z : S ⊢ tm}
  {sc : (tm ∷ tm ∷ S) ⊢ tm} {n : S ⊢ tm} →
  Γ ⊢ (natrec P z sc n) ∶ (P [ n ]₀) → Γ ⊢ n ∶ Nat →
  (natrec P z sc n ∙ˢ (n ∙ˢ idˢ)) ∶ (P ∷ₜ (Nat ∷ₜ Γ)) →ˢ Γ
-- definitional: (weaken P) [ natrec .. ∙ˢ (n ∙ˢ idˢ) ]ˢ  reduces to
-- P [ n ]₀ by interact; the other two entries likewise.
⊢ιmap ⊢nr ⊢n zero          _ refl = ⊢nr
⊢ιmap ⊢nr ⊢n (suc zero)    _ refl = ⊢n
⊢ιmap ⊢nr ⊢n (suc (suc x)) _ refl = ⊢var refl

-- ════════════════════════════════════════════════════════════════════
-- 5.  Subject reduction.
-- ════════════════════════════════════════════════════════════════════

sr : ∀ {S} {Γ : Ctx S} {e e′ A : S ⊢ tm} → Γ ⊢ e ∶ A → e ↪ e′ → Γ ⊢ e′ ∶ A

-- β.  Needs Pi-inj (via inv-lam): ⊢f may have gone through ⊢conv, so
-- the Pi in ⊢app's premise need not be the lam's own Pi syntactically.
-- definitional: probe 1 -- the conclusion B [ a ]₀ is exactly what
-- sub-pres delivers, no substitution lemma applied.
sr (⊢app {A = A} {B = B} {a = a} ⊢f ⊢a) β-app with inv-lam ⊢f
... | B₀ , eq , ⊢b with Pi-inj eq
... | eA , eB =
  ⊢conv (sub-pres {σ = a ∙ˢ idˢ} ⊢b (⊢[] (⊢conv ⊢a eA)))
        (≡β-sub {σ = a ∙ˢ idˢ} (β-sym eB))

-- ι-zero.  The conclusion type P [ zeroN ]₀ is literally ⊢z's type.
sr (⊢natrec ⊢P ⊢z ⊢sc ⊢n) ι-zero = ⊢z

-- ι-suc.  definitional: the sucMotive law (probe 4) instantiated at the
-- ι-substitution; sub-pres delivers exactly P [ sucN n ]₀.
sr (⊢natrec {P = P} {z = z} {sc = sc} ⊢P ⊢z ⊢sc ⊢sn) (ι-suc {n = n}) =
  let ⊢n = inv-sucN ⊢sn
      ⊢nr = ⊢natrec ⊢P ⊢z ⊢sc ⊢n
  in sub-pres {σ = natrec P z sc n ∙ˢ (n ∙ˢ idˢ)} ⊢sc (⊢ιmap ⊢nr ⊢n)

-- congruences
sr (⊢Pi ⊢A ⊢B)  (ξ-Pi₁ r) = ⊢Pi (sr ⊢A r) (ctx-conv (cons-≈ (β-step r)) ⊢B)
sr (⊢Pi ⊢A ⊢B)  (ξ-Pi₂ r) = ⊢Pi ⊢A (sr ⊢B r)
sr (⊢lam ⊢A ⊢b) (ξ-lam₁ r) =
  ⊢conv (⊢lam (sr ⊢A r) (ctx-conv (cons-≈ (β-step r)) ⊢b))
        (β-sym (β-step (ξ-Pi₁ r)))
sr (⊢lam ⊢A ⊢b) (ξ-lam₂ r) = ⊢lam ⊢A (sr ⊢b r)
sr (⊢app ⊢f ⊢a) (ξ-app₁ r) = ⊢app (sr ⊢f r) ⊢a
sr (⊢app {B = B} ⊢f ⊢a) (ξ-app₂ r) =
  ⊢conv (⊢app ⊢f (sr ⊢a r)) (β-sym (sub-arg-≡β B r))
sr (⊢sucN ⊢n) (ξ-sucN r) = ⊢sucN (sr ⊢n r)
sr (⊢natrec {P = P} {n = n} ⊢P ⊢z ⊢sc ⊢n) (ξ-natrec₁ r) =
  ⊢conv (⊢natrec (sr ⊢P r)
                 (⊢conv ⊢z (≡β-sub {σ = zeroN ∙ˢ idˢ} (β-step r)))
                 (⊢conv (ctx-conv (cons-≈ (β-step r)) ⊢sc)
                        (β-step (↪-ren {ξ = wkᴿ tm}
                           (↪-sub {σ = sucN (var zero) ∙ˢ wkˢ tm} r))))
                 ⊢n)
        (β-sym (β-step (↪-sub {σ = n ∙ˢ idˢ} r)))
sr (⊢natrec ⊢P ⊢z ⊢sc ⊢n) (ξ-natrec₂ r) = ⊢natrec ⊢P (sr ⊢z r) ⊢sc ⊢n
sr (⊢natrec ⊢P ⊢z ⊢sc ⊢n) (ξ-natrec₃ r) = ⊢natrec ⊢P ⊢z (sr ⊢sc r) ⊢n
sr (⊢natrec {P = P} ⊢P ⊢z ⊢sc ⊢n) (ξ-natrec₄ r) =
  ⊢conv (⊢natrec ⊢P ⊢z ⊢sc (sr ⊢n r)) (β-sym (sub-arg-≡β P r))

sr (⊢conv ⊢t e) st = ⊢conv (sr ⊢t st) e

-- ═══ PROGRESS ═══════════════════════════════════════════

-- Progress for closed terms.
--
-- Assumes nothing of its own.  Uses Pi-inj / U≁Pi / Nat≁Pi / U≁Nat from
-- above, all PROVED from the Church-Rosser theorem.



-- ─── values (weak head normal forms) ────────────────────────────────

data Val {S} : S ⊢ tm → Set where
  vU     : Val U
  vPi    : ∀ {A B} → Val (Pi A B)
  vNat   : Val Nat
  vlam   : ∀ {A b} → Val (lam A b)
  vzeroN : Val zeroN
  vsucN  : ∀ {n} → Val (sucN n)

-- ─── inversion: the principal type of each value former, up to ≡β ────
-- All go through ⊢conv without needing any confluence fact.

inv-U-ty : ∀ {S} {Γ : Ctx S} {C : S ⊢ tm} → Γ ⊢ U ∶ C → C ≡β U
inv-U-ty ⊢U           = β-refl
inv-U-ty (⊢conv ⊢t e) = β-trans (β-sym e) (inv-U-ty ⊢t)

inv-Pi-ty : ∀ {S} {Γ : Ctx S} {A C : S ⊢ tm} {B : (tm ∷ S) ⊢ tm} →
  Γ ⊢ (Pi A B) ∶ C → C ≡β U
inv-Pi-ty (⊢Pi _ _)    = β-refl
inv-Pi-ty (⊢conv ⊢t e) = β-trans (β-sym e) (inv-Pi-ty ⊢t)

inv-Nat-ty : ∀ {S} {Γ : Ctx S} {C : S ⊢ tm} → Γ ⊢ Nat ∶ C → C ≡β U
inv-Nat-ty ⊢Nat          = β-refl
inv-Nat-ty (⊢conv ⊢t e)  = β-trans (β-sym e) (inv-Nat-ty ⊢t)

inv-zeroN-ty : ∀ {S} {Γ : Ctx S} {C : S ⊢ tm} → Γ ⊢ zeroN ∶ C → C ≡β Nat
inv-zeroN-ty ⊢zeroN        = β-refl
inv-zeroN-ty (⊢conv ⊢t e)  = β-trans (β-sym e) (inv-zeroN-ty ⊢t)

inv-sucN-ty : ∀ {S} {Γ : Ctx S} {n C : S ⊢ tm} → Γ ⊢ (sucN n) ∶ C → C ≡β Nat
inv-sucN-ty (⊢sucN _)     = β-refl
inv-sucN-ty (⊢conv ⊢t e)  = β-trans (β-sym e) (inv-sucN-ty ⊢t)

-- ─── canonical forms ────────────────────────────────────────────────

cf-Pi : ∀ {S} {Γ : Ctx S} {v A : S ⊢ tm} {B : (tm ∷ S) ⊢ tm} →
  Γ ⊢ v ∶ (Pi A B) → Val v → ∃[ A₀ ] ∃[ b ] (v ≡ lam A₀ b)
cf-Pi ⊢v vU     = ⊥-elim (U≁Pi   (β-sym (inv-U-ty     ⊢v)))
cf-Pi ⊢v vPi    = ⊥-elim (U≁Pi   (β-sym (inv-Pi-ty    ⊢v)))
cf-Pi ⊢v vNat   = ⊥-elim (U≁Pi   (β-sym (inv-Nat-ty   ⊢v)))
cf-Pi ⊢v vzeroN = ⊥-elim (Nat≁Pi (β-sym (inv-zeroN-ty ⊢v)))
cf-Pi ⊢v vsucN  = ⊥-elim (Nat≁Pi (β-sym (inv-sucN-ty  ⊢v)))
cf-Pi ⊢v vlam   = _ , _ , refl

cf-Nat : ∀ {S} {Γ : Ctx S} {v : S ⊢ tm} →
  Γ ⊢ v ∶ Nat → Val v → (v ≡ zeroN) ⊎ (∃[ n ] (v ≡ sucN n))
cf-Nat ⊢v vU     = ⊥-elim (U≁Nat   (β-sym (inv-U-ty   ⊢v)))
cf-Nat ⊢v vPi    = ⊥-elim (U≁Nat   (β-sym (inv-Pi-ty  ⊢v)))
cf-Nat ⊢v vNat   = ⊥-elim (U≁Nat   (β-sym (inv-Nat-ty ⊢v)))
cf-Nat ⊢v vlam   with inv-lam ⊢v
... | _ , eq , _ = ⊥-elim (Nat≁Pi eq)
cf-Nat ⊢v vzeroN = inj₁ refl
cf-Nat ⊢v vsucN  = inj₂ (_ , refl)

-- ─── progress ───────────────────────────────────────────────────────

∅ : Ctx []
∅ _ ()

progress : ∀ {e A : [] ⊢ tm} → ∅ ⊢ e ∶ A → Val e ⊎ ∃[ e′ ] (e ↪ e′)
progress (⊢var {x = ()} _)
progress ⊢U            = inj₁ vU
progress (⊢Pi _ _)     = inj₁ vPi
progress (⊢lam _ _)    = inj₁ vlam
progress ⊢Nat          = inj₁ vNat
progress ⊢zeroN        = inj₁ vzeroN
progress (⊢sucN _)     = inj₁ vsucN
progress (⊢app ⊢f ⊢a) with progress ⊢f
... | inj₂ (f′ , r) = inj₂ (_ , ξ-app₁ r)
... | inj₁ vf with cf-Pi ⊢f vf
... | A₀ , b , refl = inj₂ (_ , β-app)
progress (⊢natrec ⊢P ⊢z ⊢sc ⊢n) with progress ⊢n
... | inj₂ (n′ , r) = inj₂ (_ , ξ-natrec₄ r)
... | inj₁ vn with cf-Nat ⊢n vn
... | inj₁ refl        = inj₂ (_ , ι-zero)
... | inj₂ (n′ , refl) = inj₂ (_ , ι-suc)
progress (⊢conv ⊢t e) = progress ⊢t

-- ─── type safety ────────────────────────────────────────────────────

sr* : ∀ {e e′ A : [] ⊢ tm} → ∅ ⊢ e ∶ A → e ↠ e′ → ∅ ⊢ e′ ∶ A
sr* ⊢e ↠-refl        = ⊢e
sr* ⊢e (↠-step r rs) = sr* (sr ⊢e r) rs

safety : ∀ {e e′ A : [] ⊢ tm} →
  ∅ ⊢ e ∶ A → e ↠ e′ → Val e′ ⊎ ∃[ e″ ] (e′ ↪ e″)
safety ⊢e rs = progress (sr* ⊢e rs)

-- ═══ POSITIVE CONTROLS ═══════════════════════════════════════════

-- POSITIVE CONTROL for the metatheory: the typing judgment is inhabited
-- by genuinely DEPENDENT closed terms.  Without this, `sr` and
-- `progress` could be vacuously true.
--
-- Every type below is checked DEFINITIONALLY: in particular
-- `polyid·Nat` requires
--     (Pi (var zero) (var (suc zero))) [ Nat ]₀  ≡  Pi Nat Nat
-- which is the substitution machinery computing under the rewrites.



-- the polymorphic identity, MLTT-style: (X : U) → X → X
polyid : ∅ ⊢ lam U (lam (var zero) (var zero))
           ∶ Pi U (Pi (var zero) (var (suc zero)))
polyid = ⊢lam ⊢U (⊢lam (⊢var refl) (⊢var refl))

-- instantiating it at Nat: the RESULT TYPE is computed by substitution
polyid·Nat : ∅ ⊢ app (lam U (lam (var zero) (var zero))) Nat ∶ Pi Nat Nat
polyid·Nat = ⊢app polyid ⊢Nat

-- and the substitution really did happen, definitionally
instantiation-computed :
  (Pi (var zero) (var (suc zero))) [ Nat ]₀ ≡ Pi {S = []} Nat Nat
instantiation-computed = refl

-- a natrec at the UNIVERSE: the eliminator computing a TYPE
natrec-type : ∅ ⊢ natrec U Nat (var zero) zeroN ∶ U
natrec-type = ⊢natrec ⊢U ⊢Nat (⊢var refl) ⊢zeroN

-- subject reduction applied to it: it ι-reduces to Nat, still at U
natrec-type-sr : ∅ ⊢ Nat ∶ U
natrec-type-sr = sr natrec-type ι-zero

-- progress applied to the redex: it steps
polyid·Nat-steps : ∃[ e′ ] (app (lam U (lam (var zero) (var zero))) Nat ↪ e′)
polyid·Nat-steps with progress polyid·Nat
... | inj₁ ()
... | inj₂ p = p

-- a β-reduction whose reduct is typed by preservation
beta-reduct : ∅ ⊢ lam Nat (var zero) ∶ Pi Nat Nat
beta-reduct = sr polyid·Nat β-app
